--06:11:53--  http://www.webhosting.gr:80/
           => `www.webhosting.gr/index.html'
Connecting to www.webhosting.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]

    0K -> .

06:11:54 (1.15 MB/s) - `www.webhosting.gr/index.html' saved [1211]

Loading robots.txt; please ignore errors.
--06:11:54--  http://www.webhosting.gr:80/no-robots.txt
           => `www.webhosting.gr/no-robots.txt'
Connecting to www.webhosting.gr:80... connected!
HTTP request sent, awaiting response... 404 Not Found
06:11:54 ERROR 404: Not Found.

--06:11:54--  http://www.webhosting.gr:80/Movie4.swf
           => `www.webhosting.gr/Movie4.swf'
Connecting to www.webhosting.gr:80... connected!
HTTP request sent, awaiting response... 404 Not Found
06:11:54 ERROR 404: Not Found.

--06:11:55--  http://www.webhosting.gr:80/nitrogear.gif
           => `www.webhosting.gr/nitrogear.gif'
Connecting to www.webhosting.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 9,883 [image/gif]

    0K -> .........                                              [100%]

06:11:55 (66.56 KB/s) - `www.webhosting.gr/nitrogear.gif' saved [9883/9883]

Converting www.webhosting.gr/index.html... done.

FINISHED --06:11:55--
Downloaded: 11,094 bytes in 2 files
Converting www.webhosting.gr/index.html... done.
