<HTML><HEAD>
<!--begin title.tmpl-->
<TITLE>BroadcastAMERICA.com</TITLE>
<!--end title.tmpl-->

<link rel=stylesheet href="/home/master.css" type="text/css">

<script language="Javascript">
<!--
function fbwindow() {
	var feedback = window.open('http://www.broadcastamerica.com/feedback/index.html','feedback','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,width=360,height=360');
	feedback.focus();
}
//-->
</script>

<script language="Javascript" src="../home/js/launch.js"></script>

<script LANGUAGE="javascript">
<!--
this.name="home"
//-->
</script>

<META NAME="KEYWORDS" CONTENT="Music, Sports,Talk, Television,News,BroadcastAmerica.com,Live,Radio,Movies,Clubs,BroadcastSports.com,BroadcastTVNews.com/BroadcastTalk.com,BroadcastClubs.com">
<META NAME="DESCRIPTION" CONTENT="BroadcastAmerica.com: the worlds largest streaming media company with over 600 exclusive live radio stations and thousands of On Demand streams">
<META HTTP-EQUIV="Refresh" CONTENT="300; URL=http://music.broadcastamerica.com/">

</HEAD>
<BODY BACKGROUND="http://images.broadcastamerica.com/main/bg.gif" TEXT="#FFFFFF" BGCOLOR="#333333" LINK="#FFFFFF" VLINK="#FFFFFF" ALINK="#FFFF99" TOPMARGIN="5" LEFTMARGIN="5" MARGINWIDTH="5" MARGINHEIGHT="5">

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
<!--begin logo.phtml-->
	<TD ALIGN="Left" VALIGN="Top" WIDTH="255"><a href="../index.html"><IMG SRC="http://images.broadcastamerica.com/main/ba_logo.gif" WIDTH="255" HEIGHT="81" BORDER="0" ALT="BroadcastAmerica.com"></a></TD>

<!--end logo.phtml-->
<!--begin main_ad_top.phtml-->
<TD ALIGN="CENTER" VALIGN="MIDDLE"><A HREF="http://ad.doubleclick.net/jump/ba.dart/bannertop;sz=468x60;ord=3917605006137?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/bannertop;sz=468x60;ord=3917605006137?" border=0 height="60" width="468"></A></TD>

<!--end main_ad_top.phtml-->
</TR>

<TR>
	<TD COLSPAN="2" ALIGN="Left" VALIGN="Top">
<!--begin navbar.phtml-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_l.gif" WIDTH="13" HEIGHT="36"></TD>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_r.gif" WIDTH="13" HEIGHT="36"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Middle" WIDTH="739" HEIGHT="28">
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="220">
<FORM ACTION="http://search.broadcastamerica.com/results.phtml" METHOD="GET">
<TR><TD>
<font id="a12"><SELECT NAME="which">
<OPTION value=site>Search Channels</OPTION>
<OPTION value=web>Search Web</OPTION>
<OPTION value=music>Music</OPTION>
<OPTION value=sports>Sports</OPTION>
<OPTION value=clubs>Clubs</OPTION>
<OPTION value=talk>Talk</OPTION>
<OPTION value=tvnews>TV News</OPTION>
<OPTION value=movies>Movies</OPTION>
<OPTION value=urban>Urban</OPTION>
<OPTION value=bible>Christian</OPTION>
<OPTION value=comedy>Comedy</OPTION>
<OPTION value=wisdom>Wisdom</OPTION>
</SELECT></font>
</TD>
<TD><INPUT NAME="spec" TYPE=Text SIZE="8" MAXLENGTH="40"></TD><TD><INPUT NAME="FIND" TYPE=Submit VALUE="Find"></TD>
<TD ALIGN="Left" VALIGN="MIDDLE"><A HREF="http://www.goto.com/"><IMG SRC="http://images.broadcastamerica.com/main/goto_logo.gif" WIDTH="37" HEIGHT="23" BORDER="0"></A></TD></TR>
</FORM>
</TABLE>
</TD>

	<TD ALIGN="RIGHT" VALIGN="MIDDLE"><font id=a17><A HREF="../index.html">Home</A> | <A HREF="../mail/index.html">Free Voice/Fax/Email</A> | <A HREF="../news/index.html">World News</A> | <A HREF="../weather/scripts/index.html">Weather</A> | <A HREF="../customize/index.html">Customize</A> | <A HREF="../help/index.html">Help</A></font></TD>
</TR>
</TABLE>

</TD>
</TR>
<TR>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="BOTTOM"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
</TR>
</TABLE>

<!--end navbar.phtml-->
	</TD>
</TR>
</TABLE>
<!--End Top Table	-->


<!--Begin Body Table	-->

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
<!--Begin LEFT TD-->
	<TD ALIGN="Left" VALIGN="Top">
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="116" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="600"></TD>

	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" HEIGHT="100%">

<!--begin leftnav_loc.tmpl-->

<!--end leftnav_loc.tmpl-->

<!--begin main_ad_1l.phtml-->
<center><A HREF="http://ad.doubleclick.net/jump/ba.dart/stream;sz=116x58;ord=5261196470820?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/stream;sz=116x58;ord=5261196470820?" border=0 height="58" width="116"></A></center><P>


<!--end main_ad_1l.phtml-->
	
<!--begin leftnav_main.phtml-->
<IMG SRC="http://images.broadcastamerica.com/main/t_streamchan.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12><a HREF="http://music.broadcastamerica.com/">Music Radio</a><BR>
<a HREF="http://sports.broadcastamerica.com/">Sports Radio</a><BR>
<a HREF="http://talk.broadcastamerica.com/">Talk Radio</a><BR>
<a HREF="http://tvnews.broadcastamerica.com/">Local TV News</a><BR>
<a HREF="http://weather.broadcastamerica.com/">Weather</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://bible.broadcastamerica.com/">Christian Radio</a><BR>
<a HREF="http://urban.broadcastamerica.com/">Urban Music Radio</a><BR>
<a HREF="http://latino.broadcastamerica.com/">Latin Radio</a><BR>
<a HREF="http://www.broadcasteurope.com/">European Radio</a><BR>
<a HREF="http://movies.broadcastamerica.com/">Movies and More</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://comedy.broadcastamerica.com/">Comedy</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://clubs.broadcastamerica.com/">Club Music</a><BR>
<a HREF="http://kids.broadcastamerica.com/">Kid's Radio</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://inspiration.broadcastamerica.com/">Wisdom</a><BR></font><P>

<A HREF="http://ad.doubleclick.net/jump/ba.dart/siaudio;sz=116x58;ord=9578956714832?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/siaudio;sz=116x58;ord=9578956714832?" border=0 height="58" width="116"></A>

<IMG SRC="http://images.broadcastamerica.com/main/t_shopping.gif" WIDTH="116" HEIGHT="28" vspace="3"><BR>
<a href="http://service.bfast.com/bfast/click?bfmid=2181&sourceid=35523158&categoryid=rn_bestsellers"><font id=a46>Barnes & Noble</font></a><br>
<a href="http://service.bfast.com/bfast/click?bfmid=22282494&siteid=35522081&bfpage=homepage"><font id=a46>Gifts.com</font></a><br>
<a href="http://service.bfast.com/bfast/click?bfmid=70780&sourceid=35521430&categoryid=banners"><font id=a46>proflowers.com</font></a><br>
<font id=a12>
<a HREF="../channels/onlinepsychic/index.html">Psychic Readings</a><BR>
<a HREF="../channels/connection/index.html">Personals</a></font><P>

<IMG SRC="http://images.broadcastamerica.com/main/t_thecompany.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12>
<a HREF="factsheet.phtml">Fact Sheet</a><BR>
<a HREF="about.phtml">About Us</a><BR>
<a HREF="chanover.phtml">Channel Overview</a><BR>
<a HREF="bios.phtml">Officer Bios</a><BR>
<a HREF="investor.phtml">Investor Info</a><BR>
<a HREF="../advertising/index.html">Advertising</a><BR>
<a HREF="contact.phtml">Contact Info</a><BR>
<a HREF="press.phtml">Press Releases</a><BR>
<a HREF="inthenews.phtml">In the News</a><BR>
<a HREF="../jobs/index.html">Jobs @</a></font><P>

<IMG SRC="http://images.broadcastamerica.com/main/t_helpfaq.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12><a HREF="../help/index.html">Help</a><BR>
<a HREF="../help/index.phtml#rm">Real Media</a><BR>
<a HREF="../help/index.phtml#wm">Windows Media</a><BR>
<a HREF="../help/index.phtml#qf">Quick Fixes</a><BR>
<a HREF="../help/station_finder.phtml">Station Finder</a><BR>
<A HREF="javascript:fbwindow()">Feedback</a><BR>
<a HREF="../help/index.phtml#form">Write to us</a></font><P>

<CENTER><a HREF="http://www.real.com/products/player/downloadrealplayer.html?wp=dl0899&src=hp_butn" TARGET="_blank"><img SRC="http://images.broadcastamerica.com/main/freerealplayer7.gif" WIDTH="88" HEIGHT="32" VSPACE="5" BORDER="0"></a><BR>

<A HREF="http://www.microsoft.com/windows/mediaplayer/en/download/default.asp"><IMG SRC="http://images.broadcastamerica.com/main/wmedia.gif" WIDTH="89" HEIGHT="32" BORDER="0" vspace="5"></A></CENTER>

<!--end leftnav_main.phtml-->
</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Middle"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>

<TR>
	<TD COLSPAN="3">
<!--begin main_ad_2l.phtml-->
<CENTER><a href="http://www.promoclick.com"><IMG SRC="http://images.broadcastamerica.com/ads/proclk_100x70.gif" WIDTH="100" HEIGHT="70" border="0" alt="ad banner" VSPACE="5"></A></CENTER>
<!--end main_ad_2l.phtml-->
	</TD>
</TR>
</TABLE>	

</TD>
<!--End LEFT TD-->

<!--Begin CENTER AREA TD-->
	<TD ALIGN="CENTER" VALIGN="Top">
<IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="17"><br>	

<table WIDTH="460px" BORDER="0" CELLSPACING="0" CELLPADDING="5">
<tr>
<td ALIGN="left">				
<font id=a10>Company History</font>
<br>
</td>
</tr>
<tr><td ALIGN="left"> 
<p><font id=a17>An Uncommon Vision</font>

<p><font id=a13><IMG SRC="http://images.broadcastamerica.com/company/alex2.jpg" WIDTH="131" HEIGHT="200" align="right" hspace="3">
In the fast-paced and often cut-throat world of Internet entrepreneurship, BroadcastAmerica refreshingly stands apart in the field. Headquartered in Portland, Maine, BroadcastAmerica has taken a different approach to the Internet entertainment business - from its business model to its recruiting strategies - and that may be the secret of the Company's success.</font>
<p><font id=a13>When CEO Alex Lauchlan and President John Brier opened shop with BroadcastAmerica in 1998 (formerly known as BroadcastMusic.com), they had the business savvy and technical know-how necessary to launch the Company. They also had the strength and determination to build BroadcastAmerica on their own terms - and in Maine - a winning combination that has put them well on their way to becoming one of the world's leading entertainment networks.</font>
<p><font id=a17>Company Beginnings</font>
<p><font id=a13>After graduating from the University of Maine in 1988, Brier started out in the entertainment industry, managing a number of local nightclubs with a group of college friends. In following years, Brier began to develop Web sites for various projects, and eventually decided to join his work on the Web with his long-time interest in entertainment. 
</font>
<p><font id=a13>The idea of BroadcastAmerica had its humble beginnings when Brier was discussing starting an online music store with a friend in a Web chat room. It was his friend who introduced him to Alex Lauchlan, a retired Scottish businessman who had spent 20 years in the development and construction of gas and oil facilities in the Canadian Arctic, the North Sea and around the world. Although Lauchlan had little Internet experience, he had plenty of management expertise, and brought unparalleled success in global business development, management and negotiation. 
</font>
<p><IMG SRC="http://images.broadcastamerica.com/company/john2.jpg" WIDTH="200" HEIGHT="131" align="left" hspace="3"><font id=a13>In October 1998, Brier began to do some research into the radio industry and the idea of building an online entertainment network to complement his plan for an online music store. It was while doing this research that he became acquainted with John Garabedian, host of the popular, nationally syndicated, Saturday night radio program, "John Garabedian's Open House Party." They quickly struck a deal, and Brier agreed to broadcast Garabedian's show for free over the Internet in exchange for live on-air mentions and advertising.
</font>
<p><font id=a13>Immensely popular in the Maine radio market, and nationwide, Brier realized that he was on the threshold of a tremendous opportunity with Garabedian's program. Internet technology could allow Garabedian's <a href="http://www.openhouseparty.com"><font id=a13>Open House Party</font></a> to expand its devoted listener base exponentially, and while Mainers listened, so could the country, and even the world.</font>
<p><font id=a13>With one success in his pocket, Brier approached two local radio stations in Maine, and secured content partnerships with both. In the meantime, Lauchlan had agreed to find investors for the venture and they began pooling resources. In January 1999, they opened a physical office in the Congress Street neighborhood of Portland, Maine with only Brier and Lauchlan. By that point, Brier had signed 100 contracts with radio stations and Lauchlan had successfully secured financing. 
</font>
<p><font id=a17>The BroadcastAmerica Family</font>
<p><IMG SRC="http://images.broadcastamerica.com/company/design2.jpg" WIDTH="131" HEIGHT="200" align="right" hspace="3"><font id=a13>As BroadcastAmerica began to grow, so did its family. From the original two employees, they have grown to more than 85 in less than two years. While many of BroadcastAmerica's peers have set up shop in Silicon Valley and New York City, Brier and Lauchlan express their strong desire to keep their business in Maine. Poised at the tip of America's East Coast, Portland provides BroadcastAmerica with a dynamic small-city location. They have also attracted a talented staff of people who want to contribute to the Internet industry, but who also value a high quality of life. "Maine is a wonderful place to live, and one of the greatest things about the Internet business is that it can literally be conducted from anywhere," said Brier.</font>
<p><font id=a13>Lauchlan agrees, and is happy to know that BroadcastAmerica has allowed a lot of people to live and work in Maine who might otherwise have had to uproot their families to pursue their dreams. Carl Grooms, Senior Vice President of strategy, left a job with Disney in Florida to return to his home state of Maine and work for BroadcastAmerica. Lauchlan says, "What makes me feel really good is that when I walk around the office and talk to each person, I know that I would hire every single one of them if I had to do it all over again."</font>
<p><font id=a13>Lauchlan and Brier take the same attentive and individualistic approach to their business partners. In addition, their unique business model provides free "streaming" services, where they broadcast their partners' live and archived shows over the Internet, in exchange for advertising on those programs.
</font>
<p><font id=a17>Continuing Growth</font>
<p><font id=a13>In December 1999, BroadcastAmerica changed its name from BroadcastMusic.com to better suit the breadth of its content, which includes more than eleven integrated content channels. To date, BroadcastAmerica has signed exclusive deals with John Garabedian's Open House Party, SupeRadio, One-On-One Sports, Talk Radio Network, Good Day USA, i.e. America and over 700 individual radio stations and 70 local TV stations around the country. </font>
<p><font id=a13>The continuous addition of more quality video and audio programming has helped BroadcastAmerica attract a rapidly growing audience. By May 2000, BroadcastAmerica had evolved from a vision to the largest Internet broadcasting company in the world, surpassing Yahoo!'s Broadcast.com. What began as a new medium for the distribution of terrestrial radio signals, was now delivering more than 700,000 hours of streaming audio and video content per month and growing. From live college hockey games to TV news broadcasts, Brier and Lauchlan are continuing to develop the Company to become one of the most comprehensive and diverse entertainment companies of the fourth medium.</font>
<p><font id=a17>Celebrity Spokespersons Garner Publicity</font>
<p><font id=a13>Late in 1999, BroadcastAmerica was selected to stream the content of his <a href="http://www.unitedstations.com">United Stations</a> Radio Networks which includes Dick Clark's Rock N' Roll Remembers, Conan O'Brien's Comedy segment, Ramsey Lewis' Legends of Jazz Show, and more. The partnership gives BroadcastAmerica exclusive Internet rights to programming that reaches an audience of 87 million per week in the U.S. alone.
</font>
<p><font id=a13>BroadcastAmerica signed internationally known performer Wayne Newton as a Company spokesperson in April 2000. As an unparalleled global entertainer with an outstanding reputation and energy level, Newton is helping to attract an even larger audience to the BroadcastAmerica family of content channels.  
</font>
<p><font id=a13>To further penetrate the sports consumer market, particularly in the northern U.S. and Canada, BroadcastAmerica brought future Hall of Famer and Captain of the New York Rangers, Mark Messier, on board as a spokesperson in August 2000. Messier and BroadcastAmerica launched "Bids for Kids," a sports-memorabilia, charity-fundraising program together in September 2000.
</font>
<p><font id=a17>Endless Possibilities
</font>
<p><IMG SRC="http://images.broadcastamerica.com/company/bocroom2.jpg" WIDTH="131" HEIGHT="200" align="left" hspace="3"><font id=a13>With all the growth and success the Company is enjoying, Brier, Lauchlan and their associates are well on the way to achieving their goal of becoming the world's leading Internet entertainment network. "Our immediate goal is simply to continue to attract quality content to our site, laying the foundation for a leading role in this industry," said Lauchlan. "There is no text book for us to consult as we develop our game plan, so it's a very thrilling time where we make up the rules and explore new opportunities."
</font>
<p><font id=a13>Brier also feels the excitement of the possibilities. "Everything has happened so quickly, there's hardly any time to stop and reflect," he said. "I think the most rewarding aspect of my job is the knowledge that we are building something that will be valued, used and enjoyed by millions of people around the world. That's extremely gratifying to me."</font></td>
</tr>
<tr>
<td>
<p><font id=a3>Media Inquiries:</font><br>
<font id=a13>BroadcastAmerica welcomes media, public relations and marketing inquiries. To schedule a media interview, inquire about corporate advertising or marketing opportunities, or to offer a speaking opportunity at an upcoming
trade show or seminar, please email us your name, organization and phone
number. Our Corporate Communications Department will get back to you right
away.</font><br><font id=a13><a HREF="mailto:communications@broadcastamerica.com">communications@broadcastamerica.com</a></font>
</td>
</tr>
</table>	


<!--END genre_list.tmpl-->
	</TD>
<!--END CENTER TD-->


<!--Begin RIGHT TD-->
	<TD ALIGN="Left" VALIGN="Top" WIDTH="140">
<!--Begin Right Nav Table BLACK-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="116" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%" HEIGHT="100%">

<!--begin main_ad_1r.phtml-->
<CENTER><A
HREF="http://ad.doubleclick.net/jump/ba.dart/msponsor;sz=88x31;ord=5074420548045?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/msponsor;sz=88x31;ord=5074420548045?" border=0 height="31" width="88"></A></CENTER><p>
<!--end main_ad_1r.phtml-->

<!--begin event.tmpl-->
<IMG SRC="http://images.broadcastamerica.com/main/t_events.gif" WIDTH="116" HEIGHT="28"><BR>
<IMG SRC="http://images.broadcastamerica.com/station_logos/music/superV_special.gif" WIDTH="116" HEIGHT="94"><BR>

<font id=a17>SUPER V</font><BR>
<font id=a16>Interactive Music TV<BR>
An EXCLUSIVE collaboration of Superadio and BroadcastAmerica<BR>
Coming soon!</font><P>

<font id=a17>Open House Party</font><BR>
<font id=a16>Live Broadcast<BR>
Saturdays<BR>
7pm est - Midnight</font><P>

<!--end event.tmpl-->

<!--begin new.tmpl-->
<IMG SRC="http://images.broadcastamerica.com/main/t_new.gif" WIDTH="116" HEIGHT="28" BORDER="0">

<font id=a31><BR>Clubs</font><BR>
<A HREF="http://Clubs.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Paul%20Oakenfold/bio?call=pauloak_bc"><font id=a17> Paul Oakenfold<BR>
</font></A><font id=a13>(World's #1 DJ)</font><P>

<font id=a31>Music</font><BR>
<A HREF="http://Music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/KRBI/bio?call=krbi_fm_bm"><font id=a17>KRBI</font></A><font id=a13> - 105.5 FM<BR>
Contemporary<BR>
St. Peter, MN</font><P>

<font id=a31>Sports</font><BR>
<A HREF="http://Sports.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WTAZ/bio?call=wtaz_am_bs"><font id=a17>WTAZ</font></A><font id=a13> - 1350 AM<BR>
Sports Talk/News<BR>
Peoria, IL</font><P>

<font id=a31>Talk</font><BR>
<A HREF="http://Talk.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WCGR/bio?call=wcgr_am_bt"><font id=a17>WCGR</font></A><font id=a13> - 1550 AM<BR>
News/Talk<BR>
Canandaigua, NY</font><P>

<font id=a31>TV News</font><BR>
<A HREF="http://Tvnews.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/KXD/bio?call=kkxd_tv"><font id=a17>KKXD</font></A><font id=a13> - CBS 13<BR>
Fairbanks, AK</font><P>





<!--end new.tmpl-->

</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
</TABLE>
<!--End Right Nav Table BLACK-->	

<!--BEGIN SPACER-->
<IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10">
<!--END SPACER-->

<!--begin main_ad_2r.phtml-->
<CENTER></CENTER>
<!--end main_ad_2r.phtml-->

<!--END RIGHT TD-->	
	
	
	</TD>
</TR>
</TABLE>	
	
<!--End Body Table	-->

<!--Begin Bottom Table	-->

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

<TR>
	<TD COLSPAN="2" ALIGN="Left" VALIGN="Top">
<!--begin navbar.phtml bottom-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_l.gif" WIDTH="13" HEIGHT="36"></TD>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_r.gif" WIDTH="13" HEIGHT="36"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Middle" WIDTH="739" HEIGHT="28">
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="220">
<FORM ACTION="http://search.broadcastamerica.com/results.phtml" METHOD="GET">
<TR><TD>
<font id="a12"><SELECT NAME="which">
<OPTION value=site>Search Channels</OPTION>
<OPTION value=web>Search Web</OPTION>
<OPTION value=music>Music</OPTION>
<OPTION value=sports>Sports</OPTION>
<OPTION value=clubs>Clubs</OPTION>
<OPTION value=talk>Talk</OPTION>
<OPTION value=tvnews>TV News</OPTION>
<OPTION value=movies>Movies</OPTION>
<OPTION value=urban>Urban</OPTION>
<OPTION value=bible>Christian</OPTION>
<OPTION value=comedy>Comedy</OPTION>
<OPTION value=wisdom>Wisdom</OPTION>
</SELECT></font>
</TD>
<TD><INPUT NAME="spec" TYPE=Text SIZE="8" MAXLENGTH="40"></TD><TD><INPUT NAME="FIND" TYPE=Submit VALUE="Find"></TD>
<TD ALIGN="Left" VALIGN="MIDDLE"><A HREF="http://www.goto.com/"><IMG SRC="http://images.broadcastamerica.com/main/goto_logo.gif" WIDTH="37" HEIGHT="23" BORDER="0"></A></TD></TR>
</FORM>
</TABLE>
</TD>

	<TD ALIGN="RIGHT" VALIGN="MIDDLE"><font id=a17><A HREF="../index.html">Home</A> | <A HREF="../mail/index.html">Free Voice/Fax/Email</A> | <A HREF="../news/index.html">World News</A> | <A HREF="../weather/scripts/index.html">Weather</A> | <A HREF="../customize/index.html">Customize</A> | <A HREF="../help/index.html">Help</A></font></TD>
</TR>
</TABLE>

</TD>
</TR>
<TR>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="BOTTOM"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
</TR>
</TABLE>

<!--end navbar.phtml bottom-->
	</TD>
</TR>

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

<!--begin copyright.tmpl-->
<TR>
<TD COLSPAN="2" ALIGN="CENTER"><font id=a12>© Copyright 2000, BroadcastAmerica.com All rights reserved.<BR>
digiQue © Copyright 1999, BroadcastAmerica.com.</font></TD></TR>

<!--end copyright.tmpl-->

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

</TABLE>

<!--begin loc.phtml-->
<div ID="currentloc" STYLE="position:absolute; text-align:right; left:332; top:123; width:430; height:20; z-index:3; font-family:arial,helvetica; color:#FFFFFF; font-size:12px; clip:rect(0,430,16,0);">
<I><a href="../index.html">Home</a></I></div>

<!--end loc.phtml-->


</BODY>
</HTML>
