<HTML><HEAD>
<!--begin title.tmpl-->
<TITLE>BroadcastAMERICA.com</TITLE>
<!--end title.tmpl-->

<link rel=stylesheet href="/home/master.css" type="text/css">

<script language="Javascript">
<!--
function fbwindow() {
	var feedback = window.open('http://www.broadcastamerica.com/feedback/index.html','feedback','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,width=360,height=360');
	feedback.focus();
}
//-->
</script>

<script language="Javascript" src="../home/js/launch.js"></script>

<script LANGUAGE="javascript">
<!--
this.name="home"
//-->
</script>

<META NAME="KEYWORDS" CONTENT="Music, Sports,Talk, Television,News,BroadcastAmerica.com,Live,Radio,Movies,Clubs,BroadcastSports.com,BroadcastTVNews.com/BroadcastTalk.com,BroadcastClubs.com">
<META NAME="DESCRIPTION" CONTENT="BroadcastAmerica.com: the worlds largest streaming media company with over 600 exclusive live radio stations and thousands of On Demand streams">
<META HTTP-EQUIV="Refresh" CONTENT="300; URL=http://music.broadcastamerica.com/">

</HEAD>
<BODY BACKGROUND="http://images.broadcastamerica.com/main/bg.gif" TEXT="#FFFFFF" BGCOLOR="#333333" LINK="#FFFFFF" VLINK="#FFFFFF" ALINK="#FFFF99" TOPMARGIN="5" LEFTMARGIN="5" MARGINWIDTH="5" MARGINHEIGHT="5">

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
<!--begin logo.phtml-->
	<TD ALIGN="Left" VALIGN="Top" WIDTH="255"><a href="../index.html"><IMG SRC="http://images.broadcastamerica.com/main/ba_logo.gif" WIDTH="255" HEIGHT="81" BORDER="0" ALT="BroadcastAmerica.com"></a></TD>

<!--end logo.phtml-->
<!--begin main_ad_top.phtml-->
<TD ALIGN="CENTER" VALIGN="MIDDLE"><A HREF="http://ad.doubleclick.net/jump/ba.dart/bannertop;sz=468x60;ord=2750713690185?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/bannertop;sz=468x60;ord=2750713690185?" border=0 height="60" width="468"></A></TD>

<!--end main_ad_top.phtml-->
</TR>

<TR>
	<TD COLSPAN="2" ALIGN="Left" VALIGN="Top">
<!--begin navbar.phtml-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_l.gif" WIDTH="13" HEIGHT="36"></TD>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_r.gif" WIDTH="13" HEIGHT="36"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Middle" WIDTH="739" HEIGHT="28">
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="220">
<FORM ACTION="http://search.broadcastamerica.com/results.phtml" METHOD="GET">
<TR><TD>
<font id="a12"><SELECT NAME="which">
<OPTION value=site>Search Channels</OPTION>
<OPTION value=web>Search Web</OPTION>
<OPTION value=music>Music</OPTION>
<OPTION value=sports>Sports</OPTION>
<OPTION value=clubs>Clubs</OPTION>
<OPTION value=talk>Talk</OPTION>
<OPTION value=tvnews>TV News</OPTION>
<OPTION value=movies>Movies</OPTION>
<OPTION value=urban>Urban</OPTION>
<OPTION value=bible>Christian</OPTION>
<OPTION value=comedy>Comedy</OPTION>
<OPTION value=wisdom>Wisdom</OPTION>
</SELECT></font>
</TD>
<TD><INPUT NAME="spec" TYPE=Text SIZE="8" MAXLENGTH="40"></TD><TD><INPUT NAME="FIND" TYPE=Submit VALUE="Find"></TD>
<TD ALIGN="Left" VALIGN="MIDDLE"><A HREF="http://www.goto.com/"><IMG SRC="http://images.broadcastamerica.com/main/goto_logo.gif" WIDTH="37" HEIGHT="23" BORDER="0"></A></TD></TR>
</FORM>
</TABLE>
</TD>

	<TD ALIGN="RIGHT" VALIGN="MIDDLE"><font id=a17><A HREF="../index.html">Home</A> | <A HREF="../mail/index.html">Free Voice/Fax/Email</A> | <A HREF="../news/index.html">World News</A> | <A HREF="../weather/scripts/index.html">Weather</A> | <A HREF="../customize/index.html">Customize</A> | <A HREF="../help/index.html">Help</A></font></TD>
</TR>
</TABLE>

</TD>
</TR>
<TR>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="BOTTOM"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
</TR>
</TABLE>

<!--end navbar.phtml-->
	</TD>
</TR>
</TABLE>
<!--End Top Table	-->


<!--Begin Body Table	-->

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
<!--Begin LEFT TD-->
	<TD ALIGN="Left" VALIGN="Top">
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="116" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="600"></TD>

	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" HEIGHT="100%">

<!--begin leftnav_loc.tmpl-->

<!--end leftnav_loc.tmpl-->

<!--begin main_ad_1l.phtml-->
<center><A HREF="http://ad.doubleclick.net/jump/ba.dart/stream;sz=116x58;ord=4256145763211?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/stream;sz=116x58;ord=4256145763211?" border=0 height="58" width="116"></A></center><P>


<!--end main_ad_1l.phtml-->
	
<!--begin leftnav_main.phtml-->
<IMG SRC="http://images.broadcastamerica.com/main/t_streamchan.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12><a HREF="http://music.broadcastamerica.com/">Music Radio</a><BR>
<a HREF="http://sports.broadcastamerica.com/">Sports Radio</a><BR>
<a HREF="http://talk.broadcastamerica.com/">Talk Radio</a><BR>
<a HREF="http://tvnews.broadcastamerica.com/">Local TV News</a><BR>
<a HREF="http://weather.broadcastamerica.com/">Weather</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://bible.broadcastamerica.com/">Christian Radio</a><BR>
<a HREF="http://urban.broadcastamerica.com/">Urban Music Radio</a><BR>
<a HREF="http://latino.broadcastamerica.com/">Latin Radio</a><BR>
<a HREF="http://www.broadcasteurope.com/">European Radio</a><BR>
<a HREF="http://movies.broadcastamerica.com/">Movies and More</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://comedy.broadcastamerica.com/">Comedy</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://clubs.broadcastamerica.com/">Club Music</a><BR>
<a HREF="http://kids.broadcastamerica.com/">Kid's Radio</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://inspiration.broadcastamerica.com/">Wisdom</a><BR></font><P>

<A HREF="http://ad.doubleclick.net/jump/ba.dart/siaudio;sz=116x58;ord=9608013038524?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/siaudio;sz=116x58;ord=9608013038524?" border=0 height="58" width="116"></A>

<IMG SRC="http://images.broadcastamerica.com/main/t_shopping.gif" WIDTH="116" HEIGHT="28" vspace="3"><BR>
<a href="http://service.bfast.com/bfast/click?bfmid=2181&sourceid=35523158&categoryid=rn_bestsellers"><font id=a46>Barnes & Noble</font></a><br>
<a href="http://service.bfast.com/bfast/click?bfmid=22282494&siteid=35522081&bfpage=homepage"><font id=a46>Gifts.com</font></a><br>
<a href="http://service.bfast.com/bfast/click?bfmid=70780&sourceid=35521430&categoryid=banners"><font id=a46>proflowers.com</font></a><br>
<font id=a12>
<a HREF="../channels/onlinepsychic/index.html">Psychic Readings</a><BR>
<a HREF="../channels/connection/index.html">Personals</a></font><P>

<IMG SRC="http://images.broadcastamerica.com/main/t_thecompany.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12>
<a HREF="factsheet.phtml">Fact Sheet</a><BR>
<a HREF="about.phtml">About Us</a><BR>
<a HREF="chanover.phtml">Channel Overview</a><BR>
<a HREF="bios.phtml">Officer Bios</a><BR>
<a HREF="investor.phtml">Investor Info</a><BR>
<a HREF="../advertising/index.html">Advertising</a><BR>
<a HREF="contact.phtml">Contact Info</a><BR>
<a HREF="press.phtml">Press Releases</a><BR>
<a HREF="inthenews.phtml">In the News</a><BR>
<a HREF="../jobs/index.html">Jobs @</a></font><P>

<IMG SRC="http://images.broadcastamerica.com/main/t_helpfaq.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12><a HREF="../help/index.html">Help</a><BR>
<a HREF="../help/index.phtml#rm">Real Media</a><BR>
<a HREF="../help/index.phtml#wm">Windows Media</a><BR>
<a HREF="../help/index.phtml#qf">Quick Fixes</a><BR>
<a HREF="../help/station_finder.phtml">Station Finder</a><BR>
<A HREF="javascript:fbwindow()">Feedback</a><BR>
<a HREF="../help/index.phtml#form">Write to us</a></font><P>

<CENTER><a HREF="http://www.real.com/products/player/downloadrealplayer.html?wp=dl0899&src=hp_butn" TARGET="_blank"><img SRC="http://images.broadcastamerica.com/main/freerealplayer7.gif" WIDTH="88" HEIGHT="32" VSPACE="5" BORDER="0"></a><BR>

<A HREF="http://www.microsoft.com/windows/mediaplayer/en/download/default.asp"><IMG SRC="http://images.broadcastamerica.com/main/wmedia.gif" WIDTH="89" HEIGHT="32" BORDER="0" vspace="5"></A></CENTER>

<!--end leftnav_main.phtml-->
</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Middle"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>

<TR>
	<TD COLSPAN="3">
<!--begin main_ad_2l.phtml-->
<CENTER><a href="http://www.promoclick.com"><IMG SRC="http://images.broadcastamerica.com/ads/proclk_100x70.gif" WIDTH="100" HEIGHT="70" border="0" alt="ad banner" VSPACE="5"></A></CENTER>
<!--end main_ad_2l.phtml-->
	</TD>
</TR>
</TABLE>	

</TD>
<!--End LEFT TD-->

<!--Begin CENTER AREA TD-->
	<TD ALIGN="CENTER" VALIGN="Top">
<IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="17"><br>	

<table WIDTH="460px" BORDER="0" CELLSPACING="0" CELLPADDING="5">
<tr>
<td ALIGN="left"><font id=a19b>Officer Biographies</font><br>
<img SRC="http://images.broadcastamerica.com/main/trans.gif" ALT="" WIDTH="440" HEIGHT="1" BORDER="0" ALIGN="left"></td>
</tr>
<tr>
<td ALIGN="left"> <p><font id=a8>The BroadcastAmerica.com Senior Management Team</font><p>
<a name="al"><font id=a13>An experienced management team devoted to financing, marketing and operations professionally manages BroadcastAmerica.com, Inc. Management depth includes MBAs from Wharton, Harvard and Stanford. A brief overview of the leadership team follows:</font><p>
<font id=a8>Alex Lauchlan, Chief Executive Officer</font><br>
<table BORDER="0" WIDTH="100%" CELLSPACING="5" CELLPADDING="0">
<tr>
<td VALIGN="TOP"><img SRC="http://images.broadcastamerica.com/company/alex.jpg" WIDTH="164" HEIGHT="234" BORDER="0"></td>

<td VALIGN="TOP"><p><font id=a13>Alex Lauchlan is a successful entrepreneur with extensive international experience. To his new role as CEO of BroadcastAmerica.com - with responsibilities for contract negotiation, management, legal affairs, financing and investor relations - he brings unsurpassed management skill and resourcefulness, as well as credibility in the worldwide arena.</font><p>
<font id=a13>Over the course of his career, Alex has played a leading role in the international business community. In 1980, he formed Thistle Consultants of Alberta, Canada, supplying expert assistance to ESSO Petroleum and other companies involved in Arctic and offshore oil construction. In 1985, he formed Thistle Construction Services, dedicated to building facilities for major petroleum and gas producers around the world. He has also served as consultant to several development projects in the Canadian Arctic, the United Kingdom, the North Sea and Sweden. </font><p>
<font id=a13>Proving the power of effective international negotiation, Alex has gained a reputation for integrity and success - even when economic downturns have made growth difficult to achieve. Alex is a graduate of Scotland's Irvine royal Academy.</font><br>
<a name="jb"></td>
</tr>
</table>

<p><font id=a8>John Brier, President and COO </font><br>

<table BORDER="0" WIDTH="100%" CELLSPACING="5" CELLPADDING="0">
<tr><td VALIGN="TOP">
<img SRC="http://images.broadcastamerica.com/company/john.jpg" WIDTH="164" HEIGHT="234" BORDER="0"></td>

<td VALIGN="TOP"><font id=a13>John Brier began his career with the University of Maine by developing a comprehensive Web site for a nation-wide Community Justice Program after serving as an officer in the U.S. Army.  Following his employment with the University of Maine, he founded GlobalStore.com, a successful Internet store that is now a public company.  John has extensive knowledge regarding the successful marketing concepts required to build the BroadcastAmerica.com site into one of the Internet's most sought after destinations. </font><p>
<font id=a13>John holds a Bachelors of Science in Business from the University of Maine and a Masters of Business Administration from Thomas College.  John is responsible for the operations and management of BroadcastAmerica.com, which includes marketing strategy, traditional media advertising, Internet advertising, strategic planning and development, and strategic partnerships.</font><br>
<a name="hs"></td>
</tr>
</table>

<p><font id=a8>Harvey L. Schein, Senior Vice President, Finance and CFO</font><BR>
<font id=a13>Joining the company in December 1999, Harvey Schein brings over 25 years of 
significant financial and business management expertise in audio and 
technology based companies. His strong financial credentials include 
successful finance, merger and acquisition and IPO efforts, domestically and 
internationally.<P>

Prior to joining BroadcastAmerica.com, Harvey was President and former CFO of 
Lexicon, Incorporated of Bedford, MA, a $30 million developer and distributor 
of digital audio equipment to musical entertainment, broadcast and film 
markets worldwide.  Instrumental in driving a 700% increase in revenue, 
Harvey led the company's original IPO and subsequent merger with Harman 
International.  A graduate of Boston University, he began his career working 
as a CPA for the "Big 5" accounting firm of PriceWaterhouseCoopers.<P>

As SVP, Finance and CFO, Harvey will help manage the company's rapid growth 
and will oversee the company's financial operations and financing strategy.</font><a name="cg"><p>

<P><font id=a8>Carlton Grooms, Senior Vice President of Corporate Strategy</font><BR>
<font id=a13>Carl Grooms began his career flying A-6E Intruder bombers for the United States Navy. After six years of military service, he successfully transitioned into business by receiving a Masters of Business Administration in Entrepreneurial Management from the renowned Wharton School of Business at the University of Pennsylvania. After graduation, he accepted a position working for Walt Disney Attractions in Orlando, Florida. </font><p>
<font id=a13>During Carl's two years at Disney, he worked briefly on their vacation planning Web site and played an important role in the development of plans for the new Disney theme park in Hong Kong. In early 1999, Carl relocated to Maine and joined BroadcastAmerica.com as senior vice president of corporate strategy.</font><p>
<font id=a8>Stephen Moulton, Senior Vice President of Design and New Media</font><BR>
<font id=a13>Stephen Moulton has been involved in numerous projects in the field of applied digital media. He is a graduate of the Parsons School of Design and the American Academy of Dramatic Arts, both located in New York City. A computer graphics and video professional, Stephen's clients include L.L. Bean Incorporated and Sensus Technologies. </font><p>
<font id=a13>Stephen has directed and produced several television documentaries airing all over the world, including Poland, Saudi Arabia and Argentina. He uses the extensive experience he has gained from video and audio production to master the art of Internet production.</font><p>
<font id=a13>As senior vice president of design and technology for BroadcastAmerica.com, Stephen is responsible for the total personality of all the company's online projects. He expertly brings together content, engineering, design and new media technologies to form a cohesive product experience for the end user.</font><p>
<font id=a8>Robert Flagg, Vice President of Engineering </font><BR>
<font id=a13>Bob Flagg is an accomplished electrical engineer with a true entrepreneurial spirit. Bob brings extensive experience from his years with Central Maine Power Company (Maine's largest public utility), to his role at BroadcastAmerica.com where he is responsible for designing and building encoder boxes, negotiating technical contracts, bringing radio stations online and acting as a technical liaison and personnel manager.</font><p>
<font id=a13>In 1996, Bob left CMP to form his own computer consulting company, Bonfire Enterprises. An instant success, one of his first assignments was to provide technical assistance in the sale of his former employer, CMP, and their nuclear power plant, Maine Yankee. Bob joined BroadcastAmerica.com after being presented with a challenge that was "just too good to resist." Bob earned his degree in Electrical Engineering from the University of Maine at Orono.</font><p>
<font id=a8>Mark Wood, Senior Vice President of Business Development</font><BR>
<font id=a13>Mark Wood brings extensive high-level management experience in sales, marketing and operations to BroadcastAmerica.com. After graduating magna cum laude from the University of Rochester in 1987, Mark served seven years in the Navy as a carrier pilot and Operations Officer. He flew missions and directed the logistic support of four aircraft carriers during the Persian Gulf War. </font><p>
<font id=a13>In 1996, Mark earned his Masters of Business Administration from Harvard Business School in Cambridge, Massachusetts. That year, he joined Genzyme, a Cambridge-based biotechnology company, where he spent three years managing the inside-sales department, formulating strategic marketing plans and performing market research and business analysis.</font><p>
<font id=a8>Vince Ciampi, Vice President of Advertising Acquisition
and Business Development</font><BR>
<font id=a13>Vince Ciampi is a senior sales executive with over 25 years experience in wholesale and retail sales.  As Vice President of Advertising Sales, he brings to BroadcastAmerica.com a strong history of marketing, managerial and motivational skills.  As national sales manager for Cortex Technologies of Cambridge, MA, he was instrumental in launching and marketing a new software product, CardScan, by developing a highly successful sales force and telemarketing division.  He personally closed the largest sale in the company's history, a multi-million-dollar contract with Office Max.  This lead to an opportunity to become Executive Vice President of Sales for IT Networks, a leader in the streaming audio and audiotex industries in Dallas, Texas.  In addition to successfully leading their national sales force to record sales, he directed their training and motivational programs.<p>
Prior to joining BroadcastAmerica.com, Vince was Vice President of Advertising Sales for Anyday.com in Cambridge, MA, where he was responsible for all advertising revenue.  In addition to his extensive experience in the high-tech industry, he spent 18 years as co-owner of Portland Appliance, a retail/wholesale operation in Portland, ME.<p>
A graduate of the University of Maine, he enjoys family, travel and sports.<font><p>
<font id=a8>Michael McPherson, VP Sales & Marketing</font><br>
<font id=a13>As one of the original members of BroadcastAmerica.com, Michael brings 17 years of broadcast experience to his role as VP Sales & Marketing at BroadcastAmerica. Over the course of his career, Michael's key positions have been program director and sales manager. He has initiated and acquired such content relationships as SuperRadio, John Garabedian's Open House Party and 100's of radio affiliates. In addition to sales and marketing, Michael continues to manage the business development content strategies for both the music channel and the company's international offices.  
</font></td>
</tr>
<tr>
<td>
<p><font id=a3>Media Inquiries:</font><br>
<font id=a13>BroadcastAmerica welcomes media, public relations and marketing inquiries. To schedule a media interview, inquire about corporate advertising or marketing opportunities, or to offer a speaking opportunity at an upcoming
trade show or seminar, please email us your name, organization and phone
number. Our Corporate Communications Department will get back to you right
away.</font><br><font id=a13><a HREF="mailto:communications@broadcastamerica.com">communications@broadcastamerica.com</a></font>
</td>
</tr>
<tr><td ALIGN="left"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="1" HEIGHT="20"></td>
</tr>
</table>	


<!--END genre_list.tmpl-->
	</TD>
<!--END CENTER TD-->


<!--Begin RIGHT TD-->
	<TD ALIGN="Left" VALIGN="Top" WIDTH="140">
<!--Begin Right Nav Table BLACK-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="116" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%" HEIGHT="100%">

<!--begin main_ad_1r.phtml-->
<CENTER><A
HREF="http://ad.doubleclick.net/jump/ba.dart/msponsor;sz=88x31;ord=2245854716748?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/msponsor;sz=88x31;ord=2245854716748?" border=0 height="31" width="88"></A></CENTER><p>
<!--end main_ad_1r.phtml-->

<!--begin event.tmpl-->
<IMG SRC="http://images.broadcastamerica.com/main/t_events.gif" WIDTH="116" HEIGHT="28"><BR>
<IMG SRC="http://images.broadcastamerica.com/station_logos/music/superV_special.gif" WIDTH="116" HEIGHT="94"><BR>

<font id=a17>SUPER V</font><BR>
<font id=a16>Interactive Music TV<BR>
An EXCLUSIVE collaboration of Superadio and BroadcastAmerica<BR>
Coming soon!</font><P>

<font id=a17>Open House Party</font><BR>
<font id=a16>Live Broadcast<BR>
Saturdays<BR>
7pm est - Midnight</font><P>

<!--end event.tmpl-->

<!--begin new.tmpl-->
<IMG SRC="http://images.broadcastamerica.com/main/t_new.gif" WIDTH="116" HEIGHT="28" BORDER="0">

<font id=a31><BR>Clubs</font><BR>
<A HREF="http://Clubs.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Paul%20Oakenfold/bio?call=pauloak_bc"><font id=a17> Paul Oakenfold<BR>
</font></A><font id=a13>(World's #1 DJ)</font><P>

<font id=a31>Music</font><BR>
<A HREF="http://Music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/KRBI/bio?call=krbi_fm_bm"><font id=a17>KRBI</font></A><font id=a13> - 105.5 FM<BR>
Contemporary<BR>
St. Peter, MN</font><P>

<font id=a31>Sports</font><BR>
<A HREF="http://Sports.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WTAZ/bio?call=wtaz_am_bs"><font id=a17>WTAZ</font></A><font id=a13> - 1350 AM<BR>
Sports Talk/News<BR>
Peoria, IL</font><P>

<font id=a31>Talk</font><BR>
<A HREF="http://Talk.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WCGR/bio?call=wcgr_am_bt"><font id=a17>WCGR</font></A><font id=a13> - 1550 AM<BR>
News/Talk<BR>
Canandaigua, NY</font><P>

<font id=a31>TV News</font><BR>
<A HREF="http://Tvnews.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/KXD/bio?call=kkxd_tv"><font id=a17>KKXD</font></A><font id=a13> - CBS 13<BR>
Fairbanks, AK</font><P>





<!--end new.tmpl-->

</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
</TABLE>
<!--End Right Nav Table BLACK-->	

<!--BEGIN SPACER-->
<IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10">
<!--END SPACER-->

<!--begin main_ad_2r.phtml-->
<CENTER></CENTER>
<!--end main_ad_2r.phtml-->

<!--END RIGHT TD-->	
	
	
	</TD>
</TR>
</TABLE>	
	
<!--End Body Table	-->

<!--Begin Bottom Table	-->

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

<TR>
	<TD COLSPAN="2" ALIGN="Left" VALIGN="Top">
<!--begin navbar.phtml bottom-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_l.gif" WIDTH="13" HEIGHT="36"></TD>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_r.gif" WIDTH="13" HEIGHT="36"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Middle" WIDTH="739" HEIGHT="28">
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="220">
<FORM ACTION="http://search.broadcastamerica.com/results.phtml" METHOD="GET">
<TR><TD>
<font id="a12"><SELECT NAME="which">
<OPTION value=site>Search Channels</OPTION>
<OPTION value=web>Search Web</OPTION>
<OPTION value=music>Music</OPTION>
<OPTION value=sports>Sports</OPTION>
<OPTION value=clubs>Clubs</OPTION>
<OPTION value=talk>Talk</OPTION>
<OPTION value=tvnews>TV News</OPTION>
<OPTION value=movies>Movies</OPTION>
<OPTION value=urban>Urban</OPTION>
<OPTION value=bible>Christian</OPTION>
<OPTION value=comedy>Comedy</OPTION>
<OPTION value=wisdom>Wisdom</OPTION>
</SELECT></font>
</TD>
<TD><INPUT NAME="spec" TYPE=Text SIZE="8" MAXLENGTH="40"></TD><TD><INPUT NAME="FIND" TYPE=Submit VALUE="Find"></TD>
<TD ALIGN="Left" VALIGN="MIDDLE"><A HREF="http://www.goto.com/"><IMG SRC="http://images.broadcastamerica.com/main/goto_logo.gif" WIDTH="37" HEIGHT="23" BORDER="0"></A></TD></TR>
</FORM>
</TABLE>
</TD>

	<TD ALIGN="RIGHT" VALIGN="MIDDLE"><font id=a17><A HREF="../index.html">Home</A> | <A HREF="../mail/index.html">Free Voice/Fax/Email</A> | <A HREF="../news/index.html">World News</A> | <A HREF="../weather/scripts/index.html">Weather</A> | <A HREF="../customize/index.html">Customize</A> | <A HREF="../help/index.html">Help</A></font></TD>
</TR>
</TABLE>

</TD>
</TR>
<TR>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="BOTTOM"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
</TR>
</TABLE>

<!--end navbar.phtml bottom-->
	</TD>
</TR>

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

<!--begin copyright.tmpl-->
<TR>
<TD COLSPAN="2" ALIGN="CENTER"><font id=a12>© Copyright 2000, BroadcastAmerica.com All rights reserved.<BR>
digiQue © Copyright 1999, BroadcastAmerica.com.</font></TD></TR>

<!--end copyright.tmpl-->

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

</TABLE>

<!--begin loc.phtml-->
<div ID="currentloc" STYLE="position:absolute; text-align:right; left:332; top:123; width:430; height:20; z-index:3; font-family:arial,helvetica; color:#FFFFFF; font-size:12px; clip:rect(0,430,16,0);">
<I><a href="../index.html">Home</a></I></div>

<!--end loc.phtml-->


</BODY>
</HTML>
