<HTML><HEAD>
<!--begin title.tmpl-->
<TITLE>BroadcastAMERICA.com</TITLE>
<!--end title.tmpl-->

<link rel=stylesheet href="/home/master.css" type="text/css">

<script language="Javascript">
<!--
function fbwindow() {
	var feedback = window.open('http://www.broadcastamerica.com/feedback/index.html','feedback','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,width=360,height=360');
	feedback.focus();
}
//-->
</script>

<script language="Javascript" src="../home/js/launch.js"></script>

<script LANGUAGE="javascript">
<!--
this.name="home"
//-->
</script>

<META NAME="KEYWORDS" CONTENT="Music, Sports,Talk, Television,News,BroadcastAmerica.com,Live,Radio,Movies,Clubs,BroadcastSports.com,BroadcastTVNews.com/BroadcastTalk.com,BroadcastClubs.com">
<META NAME="DESCRIPTION" CONTENT="BroadcastAmerica.com: the worlds largest streaming media company with over 600 exclusive live radio stations and thousands of On Demand streams">
<META HTTP-EQUIV="Refresh" CONTENT="300; URL=http://music.broadcastamerica.com/">

</HEAD>
<BODY BACKGROUND="http://images.broadcastamerica.com/main/bg.gif" TEXT="#FFFFFF" BGCOLOR="#333333" LINK="#FFFFFF" VLINK="#FFFFFF" ALINK="#FFFF99" TOPMARGIN="5" LEFTMARGIN="5" MARGINWIDTH="5" MARGINHEIGHT="5">

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
<!--begin logo.phtml-->
	<TD ALIGN="Left" VALIGN="Top" WIDTH="255"><a href="../index.html"><IMG SRC="http://images.broadcastamerica.com/main/ba_logo.gif" WIDTH="255" HEIGHT="81" BORDER="0" ALT="BroadcastAmerica.com"></a></TD>

<!--end logo.phtml-->
<!--begin main_ad_top.phtml-->
<TD ALIGN="CENTER" VALIGN="MIDDLE"><A HREF="http://ad.doubleclick.net/jump/ba.dart/bannertop;sz=468x60;ord=523626008072?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/bannertop;sz=468x60;ord=523626008072?" border=0 height="60" width="468"></A></TD>

<!--end main_ad_top.phtml-->
</TR>

<TR>
	<TD COLSPAN="2" ALIGN="Left" VALIGN="Top">
<!--begin navbar.phtml-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_l.gif" WIDTH="13" HEIGHT="36"></TD>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_r.gif" WIDTH="13" HEIGHT="36"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Middle" WIDTH="739" HEIGHT="28">
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="220">
<FORM ACTION="http://search.broadcastamerica.com/results.phtml" METHOD="GET">
<TR><TD>
<font id="a12"><SELECT NAME="which">
<OPTION value=site>Search Channels</OPTION>
<OPTION value=web>Search Web</OPTION>
<OPTION value=music>Music</OPTION>
<OPTION value=sports>Sports</OPTION>
<OPTION value=clubs>Clubs</OPTION>
<OPTION value=talk>Talk</OPTION>
<OPTION value=tvnews>TV News</OPTION>
<OPTION value=movies>Movies</OPTION>
<OPTION value=urban>Urban</OPTION>
<OPTION value=bible>Christian</OPTION>
<OPTION value=comedy>Comedy</OPTION>
<OPTION value=wisdom>Wisdom</OPTION>
</SELECT></font>
</TD>
<TD><INPUT NAME="spec" TYPE=Text SIZE="8" MAXLENGTH="40"></TD><TD><INPUT NAME="FIND" TYPE=Submit VALUE="Find"></TD>
<TD ALIGN="Left" VALIGN="MIDDLE"><A HREF="http://www.goto.com/"><IMG SRC="http://images.broadcastamerica.com/main/goto_logo.gif" WIDTH="37" HEIGHT="23" BORDER="0"></A></TD></TR>
</FORM>
</TABLE>
</TD>

	<TD ALIGN="RIGHT" VALIGN="MIDDLE"><font id=a17><A HREF="../index.html">Home</A> | <A HREF="../mail/index.html">Free Voice/Fax/Email</A> | <A HREF="../news/index.html">World News</A> | <A HREF="../weather/scripts/index.html">Weather</A> | <A HREF="../customize/index.html">Customize</A> | <A HREF="../help/index.html">Help</A></font></TD>
</TR>
</TABLE>

</TD>
</TR>
<TR>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="BOTTOM"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
</TR>
</TABLE>

<!--end navbar.phtml-->
	</TD>
</TR>
</TABLE>
<!--End Top Table	-->


<!--Begin Body Table	-->

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
<!--Begin LEFT TD-->
	<TD ALIGN="Left" VALIGN="Top">
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="116" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="600"></TD>

	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" HEIGHT="100%">

<!--begin leftnav_loc.tmpl-->

<!--end leftnav_loc.tmpl-->

<!--begin main_ad_1l.phtml-->
<center><A HREF="http://ad.doubleclick.net/jump/ba.dart/stream;sz=116x58;ord=8559063002468?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/stream;sz=116x58;ord=8559063002468?" border=0 height="58" width="116"></A></center><P>


<!--end main_ad_1l.phtml-->
	
<!--begin leftnav_main.phtml-->
<IMG SRC="http://images.broadcastamerica.com/main/t_streamchan.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12><a HREF="http://music.broadcastamerica.com/">Music Radio</a><BR>
<a HREF="http://sports.broadcastamerica.com/">Sports Radio</a><BR>
<a HREF="http://talk.broadcastamerica.com/">Talk Radio</a><BR>
<a HREF="http://tvnews.broadcastamerica.com/">Local TV News</a><BR>
<a HREF="http://weather.broadcastamerica.com/">Weather</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://bible.broadcastamerica.com/">Christian Radio</a><BR>
<a HREF="http://urban.broadcastamerica.com/">Urban Music Radio</a><BR>
<a HREF="http://latino.broadcastamerica.com/">Latin Radio</a><BR>
<a HREF="http://www.broadcasteurope.com/">European Radio</a><BR>
<a HREF="http://movies.broadcastamerica.com/">Movies and More</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://comedy.broadcastamerica.com/">Comedy</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://clubs.broadcastamerica.com/">Club Music</a><BR>
<a HREF="http://kids.broadcastamerica.com/">Kid's Radio</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://inspiration.broadcastamerica.com/">Wisdom</a><BR></font><P>

<A HREF="http://ad.doubleclick.net/jump/ba.dart/siaudio;sz=116x58;ord=7363068461419?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/siaudio;sz=116x58;ord=7363068461419?" border=0 height="58" width="116"></A>

<IMG SRC="http://images.broadcastamerica.com/main/t_shopping.gif" WIDTH="116" HEIGHT="28" vspace="3"><BR>
<a href="http://service.bfast.com/bfast/click?bfmid=2181&sourceid=35523158&categoryid=rn_bestsellers"><font id=a46>Barnes & Noble</font></a><br>
<a href="http://service.bfast.com/bfast/click?bfmid=22282494&siteid=35522081&bfpage=homepage"><font id=a46>Gifts.com</font></a><br>
<a href="http://service.bfast.com/bfast/click?bfmid=70780&sourceid=35521430&categoryid=banners"><font id=a46>proflowers.com</font></a><br>
<font id=a12>
<a HREF="../channels/onlinepsychic/index.html">Psychic Readings</a><BR>
<a HREF="../channels/connection/index.html">Personals</a></font><P>

<IMG SRC="http://images.broadcastamerica.com/main/t_thecompany.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12>
<a HREF="factsheet.phtml">Fact Sheet</a><BR>
<a HREF="about.phtml">About Us</a><BR>
<a HREF="chanover.phtml">Channel Overview</a><BR>
<a HREF="bios.phtml">Officer Bios</a><BR>
<a HREF="investor.phtml">Investor Info</a><BR>
<a HREF="../advertising/index.html">Advertising</a><BR>
<a HREF="contact.phtml">Contact Info</a><BR>
<a HREF="press.phtml">Press Releases</a><BR>
<a HREF="inthenews.phtml">In the News</a><BR>
<a HREF="../jobs/index.html">Jobs @</a></font><P>

<IMG SRC="http://images.broadcastamerica.com/main/t_helpfaq.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12><a HREF="../help/index.html">Help</a><BR>
<a HREF="../help/index.phtml#rm">Real Media</a><BR>
<a HREF="../help/index.phtml#wm">Windows Media</a><BR>
<a HREF="../help/index.phtml#qf">Quick Fixes</a><BR>
<a HREF="../help/station_finder.phtml">Station Finder</a><BR>
<A HREF="javascript:fbwindow()">Feedback</a><BR>
<a HREF="../help/index.phtml#form">Write to us</a></font><P>

<CENTER><a HREF="http://www.real.com/products/player/downloadrealplayer.html?wp=dl0899&src=hp_butn" TARGET="_blank"><img SRC="http://images.broadcastamerica.com/main/freerealplayer7.gif" WIDTH="88" HEIGHT="32" VSPACE="5" BORDER="0"></a><BR>

<A HREF="http://www.microsoft.com/windows/mediaplayer/en/download/default.asp"><IMG SRC="http://images.broadcastamerica.com/main/wmedia.gif" WIDTH="89" HEIGHT="32" BORDER="0" vspace="5"></A></CENTER>

<!--end leftnav_main.phtml-->
</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Middle"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>

<TR>
	<TD COLSPAN="3">
<!--begin main_ad_2l.phtml-->
<CENTER><a href="http://www.promoclick.com"><IMG SRC="http://images.broadcastamerica.com/ads/proclk_100x70.gif" WIDTH="100" HEIGHT="70" border="0" alt="ad banner" VSPACE="5"></A></CENTER>
<!--end main_ad_2l.phtml-->
	</TD>
</TR>
</TABLE>	

</TD>
<!--End LEFT TD-->

<!--Begin CENTER AREA TD-->
	<TD ALIGN="CENTER" VALIGN="Top">
<IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="17"><br>	

<table WIDTH="460px" BORDER="0" CELLSPACING="0" CELLPADDING="5">

<tr><td ALIGN="left"> 
<font id=a19b>In the news....</font>
<p><font id=a17>Downloadable PDF's | <a href="#vidpress">Video Press</a></font>
<p><font id=a13>The Boston Globe - August 27,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/BGlobe.pdf">BGlobe.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/BGlobe.pdf.sit">BGlobe.pdf.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/BGlobe.exe">BGlobe.exe</a></font><br>
<p><font id=a13>Billboard - June 3,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/Billboard.pdf">Billboard.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/Billboard.pdf.sit">Billboard.pdf.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/Billboard.exe">Billboard.exe</a></font><br>
<p><font id=a13>Boston Herald - June 12,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/BostonH.pdf">BostonH.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/BostonH.pdf.sit">BostonH.pdf.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/BostonH.exe">BostonH.exe</a></font><br>
<p><font id=a13>Black Radio Exclusive - May 5,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/Bre.pdf">Bre.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/Bre.sit">Bre.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/BRE.exe">BRE.exe</a></font><br>
<p><font id=a13>Detroit News - April 14,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/Detroit.pdf">Detroit.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/Detroit.pdf.sit">Detroit.pdf.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/Detroit.exe">Detroit.exe</a></font><br>
<p><font id=a13>The Industry Standard - July 24,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/IndStandr.pdf">IndStandr.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/IndStandr.pdf.sit">IndStandr.pdf.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/IndStandr.exe">IndStandr.exe</a></font><br>
<p><font id=a13>Media Week - April 10,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/MediaWeek.pdf">MediaWeek.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/MediaWeek.pdf.sit">MediaWeek.pdf.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/MediaWeek.exe">MediaWeek.exe</a></font><br>
<p><font id=a13>Philadelphia Inquirer - June 15,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/PhiliInq.pdf">PhiliInq.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/PhiliInq.pdf.sit">PhiliInq.pdf.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/PhiliInq.exe">PhiliInq.exe</a></font><br>
<p><font id=a13>Portland Press Herald - June 06,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/PortPress.pdf">PortPress.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/PortPress.pdf.sit">PortPress.pdf.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/PortPress.exe">PortPress.exe</a></font><br>
<p><font id=a13>San Francisco Chronicle - June 12,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/SanFran.pdf">SanFran.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/SanFran.pdf.sit">SanFran.pdf.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/SanFran.exe">SanFran.exe</a></font><br>
<p><font id=a13>Streaming Magazine - October,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/Streaming.pdf">Streaming.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/Streaming.pdf.sit">Streaming.pdf.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/Streaming.exe">Streaming.exe</a></font><br>
<p><font id=a13>Telegram and Gazette - June 7,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/Telegram.pdf">Telegram.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/Telegram.pdf.sit">Telegram.pdf.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/Telegram.exe">Telegram.exe</a></font><br>
<p><font id=a13>Interface Tech News - November 1,2000</font><br>
<font id=a13>Uncompressed PDF - <a href="http://images.broadcastamerica.com/company/pdfs/ITN.pdf">ITN.pdf</a></font><br>
<font id=a13>For Mac - <a href="http://images.broadcastamerica.com/company/pdfs/ITN.pdf.sit">ITN.pdf.sit</a></font><br>
<font id=a13>For PC - <a href="http://images.broadcastamerica.com/company/pdfs/ITN.exe">ITN.exe</a></font><br>
</td>
</tr>
<a name="vidpress">
<TR><TD><font id=a17>Video Press</font><BR>
<a name="vidpress">
<font id=a13>Check out the outstanding video coverage of BroadcastAmerica's newest offering, BroadcastEurope.com.</font><p>
<TR>
	<TD ALIGN="Left" VALIGN="Top"><FORM name="be_prs"><SELECT NAME="codec" SIZE=1><OPTION value="NO">Select Player Format<OPTION VALUE="R100">Real Player - 100K<OPTION VALUE="R56">Real Player - 56K</SELECT>&nbsp;&nbsp;</FORM><A HREF="javascript:openPlayer('be_prs',document.be_prs.codec.options[document.be_prs.codec.selectedIndex].value,'http://media.broadcastamerica.com:8080/ramgen/bmc/europe/press/be_press.rm');"><IMG SRC="http://images.broadcastamerica.com/main/b_watch.gif" BORDER="0"></A>
<p>
<font id=a13>Listen to the BBC coverage of the launch.</font><p>
<p><FORM name="be_pr2"><SELECT NAME="codec" SIZE=1><OPTION value="NO">Select Player Format<OPTION VALUE="R56">Real Player - 56K<OPTION VALUE="R28">Real Player - 28K</SELECT>&nbsp;&nbsp;</FORM><A HREF="javascript:openPlayer('be_pr2',document.be_pr2.codec.options[document.be_pr2.codec.selectedIndex].value,'http://media.broadcastamerica.com:8080/ramgen/bmc/europe/press/europe_bbc.rm');"><IMG SRC="http://images.broadcastamerica.com/main/b_listen.gif" BORDER="0"></A>
<p><font id=a13>BroadcastAmerica interview with CNN.</font><p>
<p><FORM name="bacnn"><SELECT NAME="codec" SIZE=1><OPTION value="NO">Select Player Format<OPTION VALUE="R250">Real Player - 250K<OPTION VALUE="R100">Real Player - 100K<OPTION VALUE="R56">Real Player - 56K</SELECT>&nbsp;&nbsp;</FORM><A HREF="javascript:openPlayer('bacnn',document.bacnn.codec.options[document.bacnn.codec.selectedIndex].value,'http://media.broadcastamerica.com:8080/ramgen/bmc/press/CNN.rm');"><IMG SRC="http://images.broadcastamerica.com/main/b_watch.gif" BORDER="0"></A></TD>
</tr>
<tr>
<td>
<p><font id=a3>Media Inquiries:</font><br>
<font id=a13>BroadcastAmerica welcomes media, public relations and marketing inquiries. To schedule a media interview, inquire about corporate advertising or marketing opportunities, or to offer a speaking opportunity at an upcoming
trade show or seminar, please email us your name, organization and phone
number. Our Corporate Communications Department will get back to you right
away.</font><br><font id=a13><a HREF="mailto:communications@broadcastamerica.com">communications@broadcastamerica.com</a></font>
</td>
</tr>
</table>	


<!--END genre_list.tmpl-->
	</TD>
<!--END CENTER TD-->


<!--Begin RIGHT TD-->
	<TD ALIGN="Left" VALIGN="Top" WIDTH="140">
<!--Begin Right Nav Table BLACK-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="116" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%" HEIGHT="100%">

<!--begin main_ad_1r.phtml-->
<CENTER><A
HREF="http://ad.doubleclick.net/jump/ba.dart/msponsor;sz=88x31;ord=9066820167937?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/msponsor;sz=88x31;ord=9066820167937?" border=0 height="31" width="88"></A></CENTER><p>
<!--end main_ad_1r.phtml-->

<!--begin event.tmpl-->
<IMG SRC="http://images.broadcastamerica.com/main/t_events.gif" WIDTH="116" HEIGHT="28"><BR>
<IMG SRC="http://images.broadcastamerica.com/station_logos/music/superV_special.gif" WIDTH="116" HEIGHT="94"><BR>

<font id=a17>SUPER V</font><BR>
<font id=a16>Interactive Music TV<BR>
An EXCLUSIVE collaboration of Superadio and BroadcastAmerica<BR>
Coming soon!</font><P>

<font id=a17>Open House Party</font><BR>
<font id=a16>Live Broadcast<BR>
Saturdays<BR>
7pm est - Midnight</font><P>

<!--end event.tmpl-->

<!--begin new.tmpl-->
<IMG SRC="http://images.broadcastamerica.com/main/t_new.gif" WIDTH="116" HEIGHT="28" BORDER="0">

<font id=a31><BR>Clubs</font><BR>
<A HREF="http://Clubs.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Paul%20Oakenfold/bio?call=pauloak_bc"><font id=a17> Paul Oakenfold<BR>
</font></A><font id=a13>(World's #1 DJ)</font><P>

<font id=a31>Music</font><BR>
<A HREF="http://Music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/KRBI/bio?call=krbi_fm_bm"><font id=a17>KRBI</font></A><font id=a13> - 105.5 FM<BR>
Contemporary<BR>
St. Peter, MN</font><P>

<font id=a31>Sports</font><BR>
<A HREF="http://Sports.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WTAZ/bio?call=wtaz_am_bs"><font id=a17>WTAZ</font></A><font id=a13> - 1350 AM<BR>
Sports Talk/News<BR>
Peoria, IL</font><P>

<font id=a31>Talk</font><BR>
<A HREF="http://Talk.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WCGR/bio?call=wcgr_am_bt"><font id=a17>WCGR</font></A><font id=a13> - 1550 AM<BR>
News/Talk<BR>
Canandaigua, NY</font><P>

<font id=a31>TV News</font><BR>
<A HREF="http://Tvnews.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/KXD/bio?call=kkxd_tv"><font id=a17>KKXD</font></A><font id=a13> - CBS 13<BR>
Fairbanks, AK</font><P>





<!--end new.tmpl-->

</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
</TABLE>
<!--End Right Nav Table BLACK-->	

<!--BEGIN SPACER-->
<IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10">
<!--END SPACER-->

<!--begin main_ad_2r.phtml-->
<CENTER></CENTER>
<!--end main_ad_2r.phtml-->

<!--END RIGHT TD-->	
	
	
	</TD>
</TR>
</TABLE>	
	
<!--End Body Table	-->

<!--Begin Bottom Table	-->

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

<TR>
	<TD COLSPAN="2" ALIGN="Left" VALIGN="Top">
<!--begin navbar.phtml bottom-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_l.gif" WIDTH="13" HEIGHT="36"></TD>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_r.gif" WIDTH="13" HEIGHT="36"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Middle" WIDTH="739" HEIGHT="28">
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="220">
<FORM ACTION="http://search.broadcastamerica.com/results.phtml" METHOD="GET">
<TR><TD>
<font id="a12"><SELECT NAME="which">
<OPTION value=site>Search Channels</OPTION>
<OPTION value=web>Search Web</OPTION>
<OPTION value=music>Music</OPTION>
<OPTION value=sports>Sports</OPTION>
<OPTION value=clubs>Clubs</OPTION>
<OPTION value=talk>Talk</OPTION>
<OPTION value=tvnews>TV News</OPTION>
<OPTION value=movies>Movies</OPTION>
<OPTION value=urban>Urban</OPTION>
<OPTION value=bible>Christian</OPTION>
<OPTION value=comedy>Comedy</OPTION>
<OPTION value=wisdom>Wisdom</OPTION>
</SELECT></font>
</TD>
<TD><INPUT NAME="spec" TYPE=Text SIZE="8" MAXLENGTH="40"></TD><TD><INPUT NAME="FIND" TYPE=Submit VALUE="Find"></TD>
<TD ALIGN="Left" VALIGN="MIDDLE"><A HREF="http://www.goto.com/"><IMG SRC="http://images.broadcastamerica.com/main/goto_logo.gif" WIDTH="37" HEIGHT="23" BORDER="0"></A></TD></TR>
</FORM>
</TABLE>
</TD>

	<TD ALIGN="RIGHT" VALIGN="MIDDLE"><font id=a17><A HREF="../index.html">Home</A> | <A HREF="../mail/index.html">Free Voice/Fax/Email</A> | <A HREF="../news/index.html">World News</A> | <A HREF="../weather/scripts/index.html">Weather</A> | <A HREF="../customize/index.html">Customize</A> | <A HREF="../help/index.html">Help</A></font></TD>
</TR>
</TABLE>

</TD>
</TR>
<TR>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="BOTTOM"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
</TR>
</TABLE>

<!--end navbar.phtml bottom-->
	</TD>
</TR>

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

<!--begin copyright.tmpl-->
<TR>
<TD COLSPAN="2" ALIGN="CENTER"><font id=a12>© Copyright 2000, BroadcastAmerica.com All rights reserved.<BR>
digiQue © Copyright 1999, BroadcastAmerica.com.</font></TD></TR>

<!--end copyright.tmpl-->

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

</TABLE>

<!--begin loc.phtml-->
<div ID="currentloc" STYLE="position:absolute; text-align:right; left:332; top:123; width:430; height:20; z-index:3; font-family:arial,helvetica; color:#FFFFFF; font-size:12px; clip:rect(0,430,16,0);">
<I><a href="../index.html">Home</a></I></div>

<!--end loc.phtml-->


</BODY>
</HTML>
