<HTML>
<HEAD>
<TITLE>ｻｰﾋﾞｽ説明</TITLE>
<!--Generated by iDomo Ver.1.0-->
</HEAD>
<BODY>
<center>
<font color="red"><b>ﾒｰﾘﾝｸﾞｻｰﾋﾞｽとは?</b></font>
</center>
<hr size=1>
iﾎﾟｽﾄに集められてくるお得な情報の中から厳選した情報をいち早く利用者に、E-ﾒｰﾙで配信するｻｰﾋﾞｽです。本ｻｰﾋﾞｽは登録が必要になります。もちろん入会金、年会費など一切ありません。<br>
<hr size=1>
<center>
<A HREF="../Menu.asp">ﾎｰﾑ</A>
</center>
</BODY>
</HTML>
