<HTML>
<HEAD>
<TITLE>ｻｰﾋﾞｽ特典</TITLE>
<!--Generated by iDomo Ver.1.0-->
</HEAD>
<BODY>
<center>
<font color="red"><b>登録利用者のはこんな特典!!</b></font>
</center>
<hr size=1>
<b>●素敵なﾌﾟﾚｾﾞﾝﾄ</b><br> 
　登録してから1年ごと、誕生日、結婚記念日に素敵なﾌﾟﾚｾﾞﾝﾄもらえる!<br>
<b>●ｴｷｻｲﾃｨﾝｸﾞｽﾛｯﾄ</b><br> 
　各ｺｰﾅｰにｱｸｾｽするとｽﾛｯﾄｹﾞｰﾑが楽しめる!大当たりすると、後日素敵な景品と交換!!<br>
<b>●ｸﾘｯｸ・ｸﾘｯｸ ﾖｳｲﾄﾞﾝ</b><br> 
　お店紹介の各ﾍﾟｰｼﾞに隠されたﾎﾞﾀﾝを探してｸﾘｯｸ!最初にｸﾘｯｸした人に素敵なﾌﾟﾚｾﾞﾝﾄ!!<br>
<b>●ｱﾝｹｰﾄに答えてﾎﾟｲﾝﾄGET</b><br> 
　ｱﾝｹｰﾄに答えるとﾎﾟｲﾝﾄが加算。貯まったﾎﾟｲﾝﾄは商品券や景品などと交換できる!!<br><br>
<hr size=1>
<center>
<A HREF="EntryForm2.asp" ACCESSKEY="0">今すぐ登録</A><br>
</center>
<hr size=1>
<center>
<A HREF="../Menu.asp">ﾎｰﾑ</A>
</center>
</BODY>
</HTML>
