--11:58:29--  http://www.nintendo.gr:80/
           => `www.nintendo.gr/index.html'
Connecting to www.nintendo.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 993 [text/html]

    0K ->                                                        [100%]

11:58:31 (969.73 KB/s) - `www.nintendo.gr/index.html' saved [993/993]

Loading robots.txt; please ignore errors.
--11:58:31--  http://www.nintendo.gr:80/no-robots.txt
           => `www.nintendo.gr/no-robots.txt'
Connecting to www.nintendo.gr:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
11:58:32 ERROR 404: Object Not Found.

--11:58:32--  http://www.nintendo.gr:80/index.gif
           => `www.nintendo.gr/index.gif'
Connecting to www.nintendo.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 3,629 [image/gif]

    0K -> ...                                                    [100%]

11:58:34 (5.26 KB/s) - `www.nintendo.gr/index.gif' saved [3629/3629]

Converting www.nintendo.gr/index.html... done.

FINISHED --11:58:34--
Downloaded: 4,622 bytes in 2 files
Converting www.nintendo.gr/index.html... done.
