--21:46:31--  http://www.europa.sk:80/
           => `www.europa.sk/index.html'
Connecting to www.europa.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 6,836 [text/html]

    0K -> ......                                                 [100%]

21:46:32 (35.70 KB/s) - `www.europa.sk/index.html' saved [6836/6836]

Loading robots.txt; please ignore errors.
--21:46:32--  http://www.europa.sk:80/robots.txt
           => `www.europa.sk/robots.txt'
Connecting to www.europa.sk:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
21:46:32 ERROR 404: Object Not Found.

--21:46:32--  http://www.europa.sk:80/cyberz.gif
           => `www.europa.sk/cyberz.gif'
Connecting to www.europa.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 25,961 [image/gif]

    0K -> .......... .......... .....                            [100%]

21:46:34 (28.88 KB/s) - `www.europa.sk/cyberz.gif' saved [25961/25961]

--21:46:34--  http://www.europa.sk:80/trabalhoinfo.jpg
           => `www.europa.sk/trabalhoinfo.jpg'
Connecting to www.europa.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 10,541 [image/jpeg]

    0K -> ..........                                             [100%]

21:46:35 (23.56 KB/s) - `www.europa.sk/trabalhoinfo.jpg' saved [10541/10541]

--21:46:35--  http://www.europa.sk:80/trabalhoinfo2.jpg
           => `www.europa.sk/trabalhoinfo2.jpg'
Connecting to www.europa.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 21,505 [image/jpeg]

    0K -> .......... .......... .                                [100%]

21:46:36 (28.23 KB/s) - `www.europa.sk/trabalhoinfo2.jpg' saved [21505/21505]

--21:46:36--  http://www.europa.sk:80/trabalhoinfo3.jpg
           => `www.europa.sk/trabalhoinfo3.jpg'
Connecting to www.europa.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 23,458 [image/jpeg]

    0K -> .......... .......... ..                               [100%]

21:46:37 (25.88 KB/s) - `www.europa.sk/trabalhoinfo3.jpg' saved [23458/23458]

--21:46:37--  http://www.europa.sk:80/linda1.jpg
           => `www.europa.sk/linda1.jpg'
Connecting to www.europa.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 16,110 [image/jpeg]

    0K -> .......... .....                                       [100%]

21:46:38 (24.09 KB/s) - `www.europa.sk/linda1.jpg' saved [16110/16110]

--21:46:38--  http://www.europa.sk:80/campBR.jpg
           => `www.europa.sk/campBR.jpg'
Connecting to www.europa.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 10,191 [image/jpeg]

    0K -> .........                                              [100%]

21:46:39 (19.98 KB/s) - `www.europa.sk/campBR.jpg' saved [10191/10191]

--21:46:39--  http://www.europa.sk:80/montagem3.jpg
           => `www.europa.sk/montagem3.jpg'
Connecting to www.europa.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 17,054 [image/jpeg]

    0K -> .......... ......                                      [100%]

21:46:40 (24.00 KB/s) - `www.europa.sk/montagem3.jpg' saved [17054/17054]

Converting www.europa.sk/index.html... done.

FINISHED --21:46:40--
Downloaded: 131,656 bytes in 8 files
Converting www.europa.sk/index.html... done.
