<HTML>
<HEAD>
<TITLE>i-Post</TITLE>
<!--Generated by iDomo Ver.1.0-->
</HEAD>

<!-- saved from url=(0022)http://internet.e-mail -->
<html>

<head>
<meta http-equiv="content-type" content="text/html;charset=x-sjis">
<meta name="GENERATOR" content="Microsoft FrontPage 3.0">
<title>iポストtop</title>
</head>


<body bgcolor="white">


<p align="center"><img src="img/mozimryo.gif"><br>
<img height="250" width="250" src="img/ipost.jpg"><br>
<font size="1" color="#000066">iポストのiはインフォメーション、インターネット、iモードなどの携帯端末を意味します。</font><b><font
size="5"></font></p>
<div align="center"><center>

<!--<table border="1" bgcolor="#0000FF">
  <tr>
    <td><font color="#FFFF80" size="+2"><b>006311</b></font></td>
  </tr>
</table>-->
</center></div>

<p align="center"><font size="5" color="black">iポストは</font><font size="7"
color="red"><img src="img/mojitoku.gif" align="absbottom"></font><font size="5">する情報を提供するサービスです。</font><br>
</p>

<hr align="center">
<p align="center">
<b>★お知らせ★</b><br>
9/1(金) AM3:00～AM7:00までの間ﾈｯﾄﾜｰｸ工事の為、i-postに接続できません。ご迷惑をおかけしますが宜しくお願い致します。<br>
</p>
<hr align="center">
<font color="#000066" size="5">

<p align="center">2000年9月サービス開始予定</font><font color="#000066"><br>
</p>

<hr align="center">
</font>

<p align="center"><br>
<font size="5">★</font><font size="5" color="red"><b>無料メーリングサービスとは</b></font><font
size="5">★</font><br>
<font color="#000066">無料メーリングサービスは、iポストに集められてくるお得な情報の中から厳選した情報をいち早く利用者にE-メールで配信するサービスです。このサービスは登録が必要です。もちろん無料（入会金、年会費など一切ありません）<a href="NEC/mailsv.asp">メーリングサービスの流れはこちら</a>
<br>
</font><br>
<a href="NEC/hgde.asp"><font size="5" color="#000066">登録するとこんなことが！！</font></a><br><br>
<b><font color="#000099">キャンペーン中（2000.8.31まで）に登録して頂いた方の中から抽選で</font><font
size="1"><br>
</font></b></p>
<div align="center"><center>

<table border="0" cellpadding="2" cellspacing="0" width="73" bgcolor="red">
  <tr>
    <td><table border="0" cellpadding="0" cellspacing="0" width="383" height="303">
      <tr height="25">
        <td height="42" colspan="3" bgcolor="red"><p align="center"><font size="5" color="white"><b>ビックプレゼント</b></font> 
        </td>
      </tr>
      <tr>
        <td width="134" align="center" bgcolor="white" height="135"><img height="83" width="129"
        src="img/zitensya.jpg"></td>
        <td rowspan="2" align="center" bgcolor="white" height="261"><img height="200" width="113"
        src="img/ps2.jpg"></td>
        <td bgcolor="white" height="135"><img height="84" width="132" src="img/kome2.jpg"></td>
      </tr>
      <tr>
        <td width="134" align="center" bgcolor="white" height="126"><img height="89" width="101"
        src="img/ky.jpg"></td>
        <td align="center" bgcolor="white" height="126"><img height="56" width="111"
        src="img/ken.jpg"></td>
      </tr>
    </table>
    </td>
  </tr>
</table>
</center></div>
<br><center>当選発表は9月上旬の「青いポストあきた」に掲載します。また、E-メールでもお知らせします。</center><br>
<p align="center"><br>
<a href="NEC/EntryForm2.asp"><font size="5"><b>★いますぐ登録!!★</b></font></a><br>
</p>

<hr align="center">

<p align="center">◆お問合せ・ご意見・ご感想　株式会社マクゼス<br>
〒010-0816　秋田市泉登木219-1<br>
TEL018-865-6383・FAX018-865-6382<br>
E-mail <a href="mailto:info@i-post.co.jp">info@i-post.co.jp</a><br>
<br>
　　　　　　 </p>
</body>
</html>


</HTML>