--22:53:31--  http://core.vtg.com.ua:80/
           => `core.vtg.com.ua/index.html'
Connecting to core.vtg.com.ua:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 3,363 [text/html]

    0K -> ...                                                    [100%]

22:53:33 (4.98 KB/s) - `core.vtg.com.ua/index.html' saved [3363/3363]

Converting core.vtg.com.ua/index.html... done.

FINISHED --22:53:33--
Downloaded: 3,363 bytes in 1 files
Converting core.vtg.com.ua/index.html... done.
