--15:13:28--  http://www.macintosh.odessa.ua:80/
           => `www.macintosh.odessa.ua/index.html'
Connecting to www.macintosh.odessa.ua:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 363 [text/html]

    0K ->                                                        [100%]

15:13:30 (354.49 KB/s) - `www.macintosh.odessa.ua/index.html' saved [363/363]

Loading robots.txt; please ignore errors.
--15:13:30--  http://www.macintosh.odessa.ua:80/no-robots.txt
           => `www.macintosh.odessa.ua/no-robots.txt'
Connecting to www.macintosh.odessa.ua:80... connected!
HTTP request sent, awaiting response... 404 Not Found
15:13:32 ERROR 404: Not Found.

--15:13:32--  http://www.macintosh.odessa.ua:80/rhsck.gif
           => `www.macintosh.odessa.ua/rhsck.gif'
Connecting to www.macintosh.odessa.ua:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,199 [image/gif]

    0K -> ....                                                   [100%]

15:13:35 (4.05 KB/s) - `www.macintosh.odessa.ua/rhsck.gif' saved [4199/4199]

Converting www.macintosh.odessa.ua/index.html... done.

FINISHED --15:13:35--
Downloaded: 4,562 bytes in 2 files
Converting www.macintosh.odessa.ua/index.html... done.
