<html>
<head>
<title>Briefme: Affiliate Login</title>
</head>
<body bgColor="#FFFFFF" text="#000000" link="#111111" vlink="#111111">
<table width="600" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td width="37" height="37" bgcolor="#ccff9a">&#160;&#160;</td>
	<td width="64" height="37" bgcolor="#006464">&#160;</td>
	<td width="50" height="37"><img src="../subimages/topcircle.jpg" width="50" height="37"></td>
	<td width="356" height="37" bgcolor="#006464">&#160;&#160;</td>
	<td width="93" height="37"><img src="../subimages/ladylean.jpg" width="93" height="37"></td>
</tr>
</table>
<table width="600" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td width="37" height="29" bgcolor="#ccff9a">&#160;</td>
	<td width="125" height="29" bgcolor="#000000"><img src="../subimages/0.gif" width="127" height="29"></td>
	<td width="82" height="29" bgcolor="#000000"><a href="../subscribe/sub.cgi"><img src="../subimages/1.gif" border="0" width="82" height="29" name="subscribe"></a></td>
	<td width="94" height="29" bgcolor="#000000"><a href="../advertise/"><img src="../subimages/2.gif" border="0" width="94" height="29" name="advertise"></a></td>
	<td width="106" height="29" bgcolor="#000000"><a href="../editor/"><img src="../subimages/3.gif" border="0" width="112" height="29" name="editor"></a></td>
	<td width="90" height="29" bgcolor="#000000"><a href="../archive/"><img src="../subimages/4.gif" border="0" width="90" height="29" name="archives"></a></td>
	<td width="60" height="29" bgcolor="#000000"><a href="../"><img src="../subimages/5.gif" border="0" width="60" height="29" name="home"></a></td>
	</tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="600">
<tr>
	<td width="37" height="56" bgcolor="#ccff9a">&#160;</td>
	<td valign="top" width="117" height="56" bgcolor="#ccff9a"><img src="../subimages/buttomcircle.jpg" align="top" width="117" height="19"></td>
	<td width="446" height="56" bgcolor="#ccff9a"><img src="images/title.jpg" width="446" height="56"></td>
</tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="600">
<tr>
	<td width="37" bgcolor="#ccff9a">&#160;</td>
	<td valign="top" width="109" bgcolor="#ccff9a">&#160;</td>
	<td width="16" bgcolor="#ccff9a">&#160;</td>
	<td valign="top" width="438" bgcolor="#ccff9a">
	<table width="430" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td><font size="-1" face="arial, helvetica">
		<font size=3><b>Existing Affiliates, Please Login Below. <font color="#FF0000"><b></b></font></b></font><font color="#FF0000"><b></b></font>		<form method="POST" action="account.phtml">
		<table cellspacing=0 cellpadding=3 border=0>
		<tr>
			<td valign=center><font size=2><b>Affiliate Email</td>
			<td valign=center><font size=3>: <input type="text" name="uid" size=25 maxlength=50 value=""></td>
		</tr>
		<tr>
			<td valign=center><font size=2><b>Password</td>
			<td valign=center><font size=3>: <input type="password" name="pid" size=11 maxlength=10></td>
		</tr>
		<tr>
			<td colspan=2><br><font size=3><input type="submit" value="Click to Login"> <input type="reset" value="Clear Input"></td>
		</tr>
		</table>
		</form>
		<hr>
		<br>
		<b>If you are a NEW Affiliate, <big><a href="member.cgi">Click Here</a></big></b>!
		<br><br>
		</td>
	</tr></table>
	</td>
</tr>
<tr>
	<td height="10" bgcolor="#000000">&#160;</td>
	<td height="10" bgcolor="#000000">&#160;</td>
	<td height="10" bgcolor="#000000">&#160;</td>
	<td height="10" bgcolor="#000000">&#160;</td>
</tr>
</table>
</body>
</html>
