--17:06:08--  http://www.pharmanet.gr:80/
           => `www.pharmanet.gr/index.html'
Connecting to www.pharmanet.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 981 [text/html]

    0K ->                                                        [100%]

17:06:09 (958.01 KB/s) - `www.pharmanet.gr/index.html' saved [981/981]

Loading robots.txt; please ignore errors.
--17:06:09--  http://www.pharmanet.gr:80/no-robots.txt
           => `www.pharmanet.gr/no-robots.txt'
Connecting to www.pharmanet.gr:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
17:06:10 ERROR 404: Object Not Found.

--17:06:10--  http://www.pharmanet.gr:80/Index.jpg
           => `www.pharmanet.gr/Index.jpg'
Connecting to www.pharmanet.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 35,550 [image/jpeg]

    0K -> .......... .......... .......... ....                  [100%]

17:06:22 (3.11 KB/s) - `www.pharmanet.gr/Index.jpg' saved [35550/35550]

Converting www.pharmanet.gr/index.html... done.

FINISHED --17:06:22--
Downloaded: 36,531 bytes in 2 files
Converting www.pharmanet.gr/index.html... done.
