--21:00:12--  http://www.amtel.sk:80/
           => `www.amtel.sk/index.html'
Connecting to www.amtel.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 59 [text/html]

    0K ->                                                        [100%]

21:00:12 (57.62 KB/s) - `www.amtel.sk/index.html' saved [59/59]

Converting www.amtel.sk/index.html... done.

FINISHED --21:00:12--
Downloaded: 59 bytes in 1 files
