--18:26:28--  http://www.tzanet.gr:80/
           => `www.tzanet.gr/index.html'
Connecting to www.tzanet.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 439 [text/html]

    0K ->                                                        [100%]

18:26:28 (428.71 KB/s) - `www.tzanet.gr/index.html' saved [439/439]

Converting www.tzanet.gr/index.html... done.

FINISHED --18:26:28--
Downloaded: 439 bytes in 1 files
