--01:42:03--  http://www.horehron.sk:80/
           => `www.horehron.sk/index.html'
Connecting to www.horehron.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 790 [text/html]

    0K ->                                                        [100%]

01:42:04 (2.99 KB/s) - `www.horehron.sk/index.html' saved [790/790]

Loading robots.txt; please ignore errors.
--01:42:04--  http://www.horehron.sk:80/no-robots.txt
           => `www.horehron.sk/no-robots.txt'
Connecting to www.horehron.sk:80... connected!
HTTP request sent, awaiting response... 404 Not Found
01:42:04 ERROR 404: Not Found.

--01:42:04--  http://www.horehron.sk:80/kkkisgay.gif
           => `www.horehron.sk/kkkisgay.gif'
Connecting to www.horehron.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 63,474 [image/gif]

    0K -> .......... .......... .......... .......... .......... [ 80%]
   50K -> .......... .                                           [100%]

01:42:08 (17.96 KB/s) - `www.horehron.sk/kkkisgay.gif' saved [63474/63474]

Converting www.horehron.sk/index.html... done.

FINISHED --01:42:08--
Downloaded: 64,264 bytes in 2 files
Converting www.horehron.sk/index.html... done.
