--01:05:29--  http://www.aion.gr:80/
           => `www.aion.gr/index.html'
Connecting to www.aion.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 484 [text/html]

    0K ->                                                        [100%]

01:05:30 (472.66 KB/s) - `www.aion.gr/index.html' saved [484/484]

Loading robots.txt; please ignore errors.
--01:05:30--  http://www.aion.gr:80/no-robots.txt
           => `www.aion.gr/no-robots.txt'
Connecting to www.aion.gr:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
01:05:30 ERROR 404: Object Not Found.

--01:05:30--  http://www.aion.gr:80/morfeu.gif
           => `www.aion.gr/morfeu.gif'
Connecting to www.aion.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 5,664 [image/gif]

    0K -> .....                                                  [100%]

01:05:31 (11.87 KB/s) - `www.aion.gr/morfeu.gif' saved [5664/5664]

Converting www.aion.gr/index.html... done.

FINISHED --01:05:31--
Downloaded: 6,148 bytes in 2 files
Converting www.aion.gr/index.html... done.
