--22:33:13--  http://www.college.gr:80/
           => `www.college.gr/index.html'
Connecting to www.college.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 965 [text/html]

    0K ->                                                        [100%]

22:33:17 (942.38 KB/s) - `www.college.gr/index.html' saved [965/965]

Converting www.college.gr/index.html... done.

FINISHED --22:33:17--
Downloaded: 965 bytes in 1 files
