--03:05:53--  http://delphi.slovakia2000.sk:80/
           => `delphi.slovakia2000.sk/index.html'
Connecting to delphi.slovakia2000.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 789 [text/html]

    0K ->                                                        [100%]

03:05:54 (2.16 KB/s) - `delphi.slovakia2000.sk/index.html' saved [789/789]

Loading robots.txt; please ignore errors.
--03:05:54--  http://delphi.slovakia2000.sk:80/no-robots.txt
           => `delphi.slovakia2000.sk/no-robots.txt'
Connecting to delphi.slovakia2000.sk:80... connected!
HTTP request sent, awaiting response... 404 Not Found
03:05:54 ERROR 404: Not Found.

--03:05:54--  http://delphi.slovakia2000.sk:80/kkkisgay.gif
           => `delphi.slovakia2000.sk/kkkisgay.gif'
Connecting to delphi.slovakia2000.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 63,474 [image/gif]

    0K -> .......... .......... .......... .......... .......... [ 80%]
   50K -> .......... .                                           [100%]

03:05:58 (19.41 KB/s) - `delphi.slovakia2000.sk/kkkisgay.gif' saved [63474/63474]

Converting delphi.slovakia2000.sk/index.html... done.

FINISHED --03:05:58--
Downloaded: 64,263 bytes in 2 files
Converting delphi.slovakia2000.sk/index.html... done.
