--12:35:55--  http://dinamo.com.ua:80/
           => `dinamo.com.ua/index.html'
Connecting to dinamo.com.ua:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 820 [text/html]

    0K ->                                                        [100%]

12:35:58 (800.78 KB/s) - `dinamo.com.ua/index.html' saved [820/820]

Loading robots.txt; please ignore errors.
--12:36:00--  http://dinamo.com.ua:80/no-robots.txt
           => `dinamo.com.ua/no-robots.txt'
Connecting to dinamo.com.ua:80... connected!
HTTP request sent, awaiting response... 404 Not Found
12:36:02 ERROR 404: Not Found.

--12:36:02--  http://dinamo.com.ua:80/index1.htm
           => `dinamo.com.ua/index1.htm'
Connecting to dinamo.com.ua:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 7,911 [text/html]

    0K -> .......                                                [100%]

12:36:05 (7.78 KB/s) - `dinamo.com.ua/index1.htm' saved [7911/7911]

Converting dinamo.com.ua/index1.htm... done.
--12:36:11--  http://dinamo.com.ua:80/enter.gif
           => `dinamo.com.ua/enter.gif'
Connecting to dinamo.com.ua:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 11,329 [image/gif]

    0K -> .......... .                                           [100%]

12:36:18 (2.47 KB/s) - `dinamo.com.ua/enter.gif' saved [11329/11329]

Converting dinamo.com.ua/index.html... done.

FINISHED --12:36:18--
Downloaded: 20,060 bytes in 3 files
Converting dinamo.com.ua/index.html... done.
Converting dinamo.com.ua/index1.htm... done.
