--17:01:25--  http://www.idex.sk:80/
           => `www.idex.sk/index.html'
Connecting to www.idex.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 7,665 [text/html]

    0K -> .......                                                [100%]

17:01:26 (12.43 KB/s) - `www.idex.sk/index.html' saved [7665/7665]

Loading robots.txt; please ignore errors.
--17:01:26--  http://www.idex.sk:80/no-robots.txt
           => `www.idex.sk/no-robots.txt'
Connecting to www.idex.sk:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
17:01:27 ERROR 404: Object Not Found.

--17:01:27--  http://www.idex.sk:80/wfd2.jpg
           => `www.idex.sk/wfd2.jpg'
Connecting to www.idex.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 19,715 [image/jpeg]

    0K -> .......... .........                                   [100%]

17:01:29 (17.86 KB/s) - `www.idex.sk/wfd2.jpg' saved [19715/19715]

Converting www.idex.sk/index.html... done.

FINISHED --17:01:33--
Downloaded: 27,380 bytes in 2 files
Converting www.idex.sk/index.html... done.
