--21:05:14--  http://shop.chemolak.sk:80/
           => `shop.chemolak.sk/index.html'
Connecting to shop.chemolak.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 196 [text/html]

    0K ->                                                        [100%]

21:05:15 (191.41 KB/s) - `shop.chemolak.sk/index.html' saved [196/196]

Converting shop.chemolak.sk/index.html... done.

FINISHED --21:05:15--
Downloaded: 196 bytes in 1 files
