<html>
<head>
<title>Nullsoft SHOUTcast</title>
</head> 
<body marginwidth="2" marginheight="2" topmargin="2" leftmargin="2" bgcolor="#000000" text="#FFC800" link="#CCCCCC" alink="#FFFFFF" vlink="#CCCCCC">

  <table border="0" width="100%" cellspacing="0" cellpadding="3" align="center">
    <tr>
      <td width="6" nowrap bgcolor="#FFC800"></td>
      <td width="100%" bgcolor="#FFC800">
        <font color="#000000" face="Arial, Helvetica" size="4">
        <b>Nullsoft SHOUTcast Disclaimer/Copyright Complaints</b></font></td>
    </tr>
    <tr>
      <td width="100%" colspan="2">
        <br>     
        <table width="95%" border="0" cellspacing="0" cellpadding="0" align="center">
        <tr>
        <td align="center">
        <font face="Arial, Helvetica" size="1">
        <a href="javascript:parent.close()">Click Here to Close</a></td>
        </td>
    </tr>

        <tr>
        <td align="left">
        <font color="#FFFFFF" face="Arial, Helvetica" size="2">
<b>Terms of Use</b>
<p>
   The SHOUTcast directory listings and other content available on and 
through this website (collectively, the "Directory") are provided by Nullsoft 
for your personal use only. By using this website, you agree that you will 
not store, reproduce, transmit, publicly display, publicly perform, 
distribute, publish, broadcast or otherwise make available the Directory or 
any portion of the Directory, whether electronically or in any other form, 
and whether for commercial purposes or any purpose other than your own 
personal use, unless approved in writing by Nullsoft. Any portion of the 
Directory which is downloaded or otherwise reproduced from this website may 
be retained only for a temporary period of time. Systematic retrieval of data 
or other content from the Directory or other use of such data and other 
content, directly or indirectly, to create or compile a collection, database 
or directory without written permission from Nullsoft is prohibited. The 
Directory is provided "AS IS." Nullsoft does not pre-screen any of the 
channel listings or related content available through the Directory, and 
Nullsoft makes no representations or warranties regarding such channel 
listings and content. Nullsoft expressly disclaims any warranty of 
merchantability, fitness for a particular purpose or non-infringement. 
Nullsoft may change the terms of use for this site at any time. 
<p>
</td>
</tr>

        <tr>
        <td align="left">
        <font color="#FFFFFF" face="Arial, Helvetica" size="2">
<b>Disclaimer</b>
<p>
        <b>Nullsoft, Inc.</b> and its parent company, America Online, Inc., is not responsible for the content of any broadcast. 
        Nullsoft, Inc. believes in the First Amendment to the US Constitution and will 
        not review or censure any broadcast. Those who listen to any broadcast listed or 
        served herein assume all risk of being offended or suffering any other form of damage.
<p>
<b>Copyright Complaints </b>
<p>
<b>Nullsoft Inc.</b> and its parent company, America Online, 
Inc., respect the intellectual property of others, and we ask our Content 
providers to do the same. 
<p>
If you believe that your copyrighted work has been copied and is accessible 
on the Nullsoft, Winamp or SHOUTcast websites in a way 
that constitutes copyright infringement, you may notify Nullsoft by 
providing our copyright agent the following information: 
<p>
<ol>
 <li>an electronic or physical signature of the owner of the copyright or the 
person authorized to act on the owner's behalf. 
  <li>a description of the copyrighted work that you claim has been infringed 
and a description of the infringing activity. 
 <li>identification of the location where the original or an authorized copy 
of the copyrighted work exists, for example the URL (i.e., web page address) 
where it is posted or the name of the book in which it has been published. 
 <li>identification of the URL or other specific location on the 
[Nullsoft/Spinner] site where the material that you claim is infringing is 
located, including enough information to allow us to locate the material. 
 <li>your name, address, telephone number, and email address. 
 <li>a statement by you that you have a good faith belief that the disputed 
use is not authorized by the copyright owner, its agent, or the law. 
 <li>a statement by you, made under penalty of perjury, that the above 
information in your Notice is accurate and that you are the copyright owner 
or authorized to act on the copyright owner's behalf. 
<p>
Nullsoft's agent for notice of claims of copyright infringement 
on this site can be reached as follows: 
<p>

                                    By mail:<br>
                                    Jim Bramson<br>
                                    Counsel<br>
                                    America Online, Inc.<br>
                                    22000 AOL Way<br>
                                    Dulles, VA 20166<br>
<p>

                        By fax:<br>
                        (703) 265-1075                            <br>
<p>
                        By phone:<br>
                                    (703) 265-0094<br>
<p>
                                    By email:<br>
                                    AOLCopyright@aol.com
<p>
        </font></blockquote></td>
        </tr>
        <tr>
        <td align="center">
        <font face="Arial, Helvetica" size="1">
        <a href="javascript:parent.close()">Click Here to Close</a></td></tr>
        </table></td>
    </tr>
  </table>
</body>
</html>
