
<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="Mon, 01 Jan 1990 12:00:00 GMT">
<meta name="keywords" content="radio, MP3, internet, stream, free, winamp, skins, plugins, shoutcast, icecast, real, player, internet radio, web, radio station, broadcast, listen, netradio, live, jukebox, audio, free download, classic rock, online radio, media player, top 40, hip hop, blues, electronica, fusion, new wave, dance, oldies, country, techno, industrial,  adult contemporary, rock, alternative, modern, world music, talk radio, sports, international, classical, urban, Christian, jazz, streaming, tuner, concert, media, free, rush limbaugh, britney spears, will smith, ricky martin, big punisher, boston, dionne warwick, dj spooky, eels, elliot smith, aerosmith, madonna, tom petty, alanis morissette, nullsoft, fun, aidop. tunes, classic, beastie boys, tori amos, julian lennon, mc lyte, depeche mode, rick springfield, matchbox 20, blink 182, pearljam, primus, offspring, smashmouth, xtc, john mellencamp, bruce springsteen, wav, mod, wma, M3U, mp2, s3m">
<meta name="description" content="Using Nullsoft Winamp, anyone can become a D.J. over night! Powered by Nullsoft SHOUTcast technology, anyone with an average analog modem can have the ability to broadcast audio to audiences without huge equipment and massive loads of bandwidth. Anyone can be an online d.j. with virtually no time!">

<title>SHOUTcast - HOME</title>
<style type="text/css">
  <!--
     a:link {color: #888888; font-family:Arial, Helvetica; font-size:9pt; text-decoration: underline;}
     a:visited {color: #888888; font-family:Arial, Helvetica; font-size:9pt; text-decoration: underline;}
     a:hover {color: red; font-family:Arial, Helvetica; font-size:9pt; font-weight:strong;}
     #navlinks {color: #000000; font-family:Arial, Helvetica; font-size:9pt; font-weight:regular; text-decoration:none;}
     #forum {color: #FFFFFF; font-family:Arial, Helvetica; font-size:8pt; font-weight:strong; text-decoration:none;}
     #links {color: #FFAA00; font-family:Arial, Helvetica; font-size:16pt; font-weight:strong; text-decoration:none;}
     #dirlinks {color:#C89600; font-family:Arial, Helvetica; font-size:8pt; text-decoration: underline; font-weight:strong;}
     #listlinks {color:#AAAAAA; font-family:Arial, Helvetica; font-size:9pt; text-decoration: none;}
     #listlinks:hover {color:#FFC800; font-family:Arial, Helvetica; font-size:9pt; text-decoration: underline;}
     #docslinks {color:C89600; font-family:Arial, Helvetica; font-size:8pt; text-decoration: none;}     
     #mblistlinks {color:#AAAAAA; font-family:Arial, Helvetica; font-size:7pt; text-decoration: none;}
     #mblistlinks:hover {color:#FFC800; font-family:Arial, Helvetica; font-size:7pt; text-decoration: underline;}
     #chatstuff {color:#FFC800; font-family:Arial, Helvetica; font-size:9pt; text-decoration: none;}
     #chatstuff:hover {color:#FF0000; font-family:Arial, Helvetica; font-size:9pt; text-decoration: underline;}
  -->
</style>
<script language="Javascript">
<!--//
function setWin(newLoc, newWidth, newHeight) {
        newWin = open("",newLoc,"scrollbars=yes,resizable=no,status=no,height=" + newHeight + ",width=" + newWidth);
}
//-->
</script>

</head>

<body marginheight="0" marginwidth="0" topmargin="0" leftmargin="0" bgcolor="#000000" text="#FFC800" link="#CCCCCC" alink="#FFFFFF" vlink="#CCCCCC">

<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td width="100%">
      <table border="0" width="100%" cellspacing="0" cellpadding="0">
<!-- Top Logos -->
        <tr>
          <td width="100%">
            <a href="index.phtml">
            <img border="0" src="images/sc-logo.gif" width="350" height="97" hspace="0"></a></td>
          <td align="right" nowrap valign="middle">
            <table border="1" bordercolor="#FFFFFF" cellspacing="0" cellpadding="0"><tr><td>
            <table width="100" border="0" cellpadding="1" cellspacing="0">
             <tr>
              <td align="center" bgcolor="#005AAA" colspan="2">
               <font face="Arial, Helvetica" size="1" color="#FFFFFF">
               <b>Current Statistics:</b></font></td>
             </tr>
             <tr>
              <td width="2" nowrap bgcolor="#000000"></td>
              <td align="left" nowrap bgcolor="#000000">
               <font face="Arial, Helvetica" size="1" color="#FFFFFF"><font size="2">
               <b>Listeners - <font color="#FF0000">9157</font><br>Servers - <font color="#FF0000">3626</font><br></font>
               All Natural<br>
               No Preservatives<br>
               98% FAT FREE!</b></font></td>
             </tr>
            </table></td></tr></table></td>
          <td width="10" nowrap></td>
        </tr>
<!-- END Top Logos -->
        <tr>
          <td colspan="4" align="center">
            <img border="0" src="images/bluebar.gif" width="100%" height="2"></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td width="100%">
      <table border="0" width="100%" cellspacing="0" cellpadding="2">
        <tr>
          <td width="100%" bgcolor="#FFC800">
            <font face="Arial" color="#000000" size="2">
            <b>&nbsp;
              <a href="http://yp.shoutcast.com" ID="navlinks">listen</a> | 
              <a href="index.phtml" ID="navlinks">home</a> | 
              <a href="index.phtml#news" ID="navlinks">latest news</a> | 
              <a href="download/index.html" ID="navlinks">download shoutcast</a> | 
              <a href="http://www.winamp.com/winamp/download/" target="outside" ID="navlinks">download winamp</a> |
              <a href="support/docs/index.html" ID="navlinks">online documentation</a>
<!--              <a href="http://www.shoutcast.com/forums/" ID="navlinks">forums</a> -->
              </b></font>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>


<!-- Begin TOP TEN! -->

<table border="0" width="100%">
  <tr>
    <td width="170">
      <img border="0" src="images/sc-showcase.gif" width="165" height="66">
    </td>
    <td width="100%" nowrap>
      
<!--** $Id: ad-banner.inc,v 1.5 1999/09/29 19:09:56 irogers Exp $ **-->

<!----- BEGIN AD -----> 

<center>
<a href="http://ads.web.aol.com/link/7007440/html?badsc=B0bZCoRrROY3Od9oTUaCOjV6cWAnxkFCJcNmiftnyDBkGKd9wMltxwN-DwcaQHaqjjIxYyhIAEm8LbxdgxrcX1OEQKYGg8Jr-S9UooTrRZ0FA$" target="yes"><img src="http://ads.web.aol.com/content/B0/0/iBL1O95LGrmfhtey6QEZXed5_17CpaPb3vA4nkXrnfJRrAUw7En0qCrWYcZ64Ltd0UZ3Aln_8CMHouJSHZMjJ8fAh1Jaj7UMTpwr3EHYmSw$/aol" border="0" height="60" width="468"></a>
</center>
 
<!----- END AD ----->
    </td>
  </tr>
</table>

<script language="Javascript">
<!--//
function setWin(newLoc, newWidth, newHeight) {
        newWin =
open("",newLoc,"scrollbars=no,resizable=no,status=no,height=" + newHeight +
",width=" + newWidth);
}
//-->
</script>


  <table border="0" width="96%" cellpadding="0" cellspacing="0" align="center">
    <tr>
      <td width="35" nowrap align="center"><font face="Arial, Helvetica" size="1">Rank</font></td>
      <td nowrap align="center" width="10"></td>
      <td nowrap align="center"><font face="Arial, Helvetica" size="1">Action</font></td>
      <td nowrap align="center" width="10"></td>
      <td width="100%" nowrap align="center"><font face="Arial, Helvetica" size="1">Genre [Description]</font></td>
      <td nowrap align="center" width="10"></td>
      <td nowrap align="center"><font face="Arial, Helvetica" size="1">Listeners/Max</font></td>
      <td nowrap align="center" width="10"></td>
      <td nowrap align="center"><font face="Arial, Helvetica" size="1">Bitrate</font></td>
      <td nowrap align="center" width="10"></td>
    </tr>
    <tr>
      <td colspan="10" align="center" valign="middle" height="4"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><img border="0" src="images/bluebar.gif" width="100%" height="2"></font></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>1</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><a href="sbin/shoutcast-playlist.pls?rn=140439&addr=195.19.200.132:31337&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=HAX0R" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E5A"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[HAX0R]</font></b> <a id="listlinks" target="_scurl" href="http://mp3.com/category5">www.mp3.com/category5-ytcracker-owns-you-no-limit-ughhh</a></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="red">823/823</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">128</font></td>
      <td nowrap align="center" bgcolor="#001E5A" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>2</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><a href="sbin/shoutcast-playlist.pls?rn=200222&addr=205.188.245.34:8004&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=Techno Trance GOA&dc=tagstrance" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E32"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[Techno Trance GOA]</font></b> <a id="listlinks" target="_scurl" href="http://www.tagstrance.com/">`Tag`s Trance Trip</a><br>
<font size="1"><a id="chatstuff" href="aim:goim?screenname=AcidTag">[ AIM ]</a>&nbsp;<font color="#FF0000">Now Playing:</font> Masaray - Ether Relay</font></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">491/700</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">96</font></td>
      <td nowrap align="center" bgcolor="#001E32" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>3</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><a href="sbin/shoutcast-playlist.pls?rn=14938&addr=216.32.166.94:8076&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=80s rock pop" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E5A"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[80s rock pop]</font></b> <a id="listlinks" target="_scurl" href="http://www.upbeat80s.com"> Upbeat80's! Added hours of new songs!  http://www.upbeat80s.com</a></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">334/700</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">56</font></td>
      <td nowrap align="center" bgcolor="#001E5A" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>4</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><a href="sbin/shoutcast-playlist.pls?rn=3641&addr=207.199.1.25:8000&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=Alternative Rock" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E32"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[Alternative Rock]</font></b> <font color=#ff0000 size=-2>CLUSTER </font><a id="listlinks" target="_scurl" href="http://www.radiospy.com">Official RadioSpy Alternative</a><br>
<font size="1"><font color="#FF0000">Now Playing:</font> Stone Temple Pilots-Core - Sex Type Thing</font></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">275/352</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">56</font></td>
      <td nowrap align="center" bgcolor="#001E32" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>5</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><a href="sbin/shoutcast-playlist.pls?rn=12224&addr=216.32.166.83:6338&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=Dance Techno Trance" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E5A"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[Dance Techno Trance]</font></b> <a id="listlinks" target="_scurl" href="http://www.digitallyimported.com"> D I G I T A L L Y - I M P O R T E D - The best of Euro Hi-NRG, Techno, & Trance</a></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">254/365</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">56</font></td>
      <td nowrap align="center" bgcolor="#001E5A" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>6</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><a href="sbin/shoutcast-playlist.pls?rn=2835&addr=209.51.160.180:8000&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=techno trance house&dc=repruhzent" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E32"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[techno trance house]</font></b> <font color=#ff0000 size=-2>CLUSTER </font><a id="listlinks" target="_scurl" href="http://www.repruhzent.com">(rep`ruh`zent) - Only the BEST in Techno, Trance, House, Electronica and more [#repruhzent|EFnet]</a><br>
<font size="1"><font color="#FF0000">Now Playing:</font> Various - One True Parker Promo Mix CD</font></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">252/1000</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">128</font></td>
      <td nowrap align="center" bgcolor="#001E32" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>7</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><a href="sbin/shoutcast-playlist.pls?rn=12638&addr=216.32.166.94:19206&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=pop 80s" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E5A"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[pop 80s]</font></b> <a id="listlinks" target="_scurl" href="http://www.live365.com"> Smash Hits From The 80's & 90's UPDATED!!!</a></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">250/500</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">56</font></td>
      <td nowrap align="center" bgcolor="#001E5A" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>8</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><a href="sbin/shoutcast-playlist.pls?rn=408306&addr=216.32.166.94:8002&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=techno" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E32"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[techno]</font></b> <a id="listlinks" target="_scurl" href="http://www.live365.com"> Afternoon Nap 2.1 by dj dusty [triphop / ambient / downtempo]</a></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">202/365</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">56</font></td>
      <td nowrap align="center" bgcolor="#001E32" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>9</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><a href="sbin/shoutcast-playlist.pls?rn=6971&addr=24.8.109.88:8000&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=hip hop rap" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E5A"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[hip hop rap]</font></b> <font color=#ff0000 size=-2>CLUSTER </font><a id="listlinks" target="_scurl" href="http://www.simplyradio.com">The Simply Underground Hip-Hop Network Call us on the request line #516-355-5239</a><br>
<font size="1"><font color="#FF0000">Now Playing:</font> Live Content</font></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">156/176</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">24</font></td>
      <td nowrap align="center" bgcolor="#001E5A" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>10</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><a href="sbin/shoutcast-playlist.pls?rn=539579&addr=216.32.166.89:17952&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=jazz" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E32"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[jazz]</font></b> <a id="listlinks" target="_scurl" href="http://www.donfx.com">  Fresh & Smooth &#45; Jazz by DonFX</a></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">148/365</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">56</font></td>
      <td nowrap align="center" bgcolor="#001E32" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>11</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><a href="sbin/shoutcast-playlist.pls?rn=47448&addr=208.184.87.89:8000&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=User  s Choice" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E5A"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[User  s Choice]</font></b> <a id="listlinks" target="_scurl" href="http://abv-icy1.myplay.com/launch.html">MyPlay Highlights - The Best Playlists From myplay.com</a><br>
<font size="1"><font color="#FF0000">Now Playing:</font> Old Devil Moon by Ann Hampton Callaway</font></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">145/1000</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">32</font></td>
      <td nowrap align="center" bgcolor="#001E5A" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>12</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><a href="sbin/shoutcast-playlist.pls?rn=468018&addr=216.32.166.83:8676&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=techno jazz hip hop" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E32"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[techno jazz hip hop]</font></b> <a id="listlinks" target="_scurl" href="http://www.thedownbeat.org/"> ..thedownbeat..::..bedroombeats..</a></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">130/365</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">56</font></td>
      <td nowrap align="center" bgcolor="#001E32" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>13</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><a href="sbin/shoutcast-playlist.pls?rn=307836&addr=216.218.245.235:8020&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=Adult Alt  Rock&dc=#shoutcast" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E5A"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[Adult Alt  Rock]</font></b> <a id="listlinks" target="_scurl" href="http://www.radioparadise.com/winamp">Radio Paradise: eclectic intelligent rock - hi-fi sound @ 24kb</a><br>
<font size="1"><font color="#FF0000">Now Playing:</font> Eric says: `Really like the concept of the station. Very different & so is the music`</font></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">107/256</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">24</font></td>
      <td nowrap align="center" bgcolor="#001E5A" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>14</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><a href="sbin/shoutcast-playlist.pls?rn=99751&addr=216.122.37.2:8400&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=rock 70s 80s mixed v" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E32"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[rock 70s 80s mixed v]</font></b> <a id="listlinks" target="_scurl" href="http://netrockradio.com">NET ROCK!!!  Classic Rock, Modern Rock, Some 80`s. Great Mix of the Best Music!</a></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">103/125</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">24</font></td>
      <td nowrap align="center" bgcolor="#001E32" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>15</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><a href="sbin/shoutcast-playlist.pls?rn=513728&addr=216.32.166.94:6000&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=classical" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E5A"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[classical]</font></b> <a id="listlinks" target="_scurl" href="http://afghany.tripod.com/VibeMaster/Welcome.html"> Fine Chamber Music by the VibeMaster_Your Favorite Classical Hits</a></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">96/365</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">56</font></td>
      <td nowrap align="center" bgcolor="#001E5A" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>16</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><a href="sbin/shoutcast-playlist.pls?rn=11024&addr=212.236.79.195:8000&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=Pop  Rock  Misc" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E32"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[Pop  Rock  Misc]</font></b> <a id="listlinks" target="_scurl" href="http://www.xxlradio.at">XXLarge Radio Austria</a></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">93/1000</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">24</font></td>
      <td nowrap align="center" bgcolor="#001E32" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>17</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><a href="sbin/shoutcast-playlist.pls?rn=8230&addr=208.148.74.173:8000&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=Rock Metal Alt" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E5A"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[Rock Metal Alt]</font></b> <font color=#ff0000 size=-2>CLUSTER </font><a id="listlinks" target="_scurl" href="http://www.radiostorm.com">Radiostorm.com: WORLDWIDE HARDROCK</a><br>
<font size="1"><font color="#FF0000">Now Playing:</font> Korn - Make Me Bad</font></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">92/1532</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">24</font></td>
      <td nowrap align="center" bgcolor="#001E5A" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>18</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><a href="sbin/shoutcast-playlist.pls?rn=672195&addr=216.32.166.89:7294&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=comedy various talk" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E32"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[comedy various talk]</font></b> <a id="listlinks" target="_scurl" href="http://www.live365.com/cgi-bin/directory.cgi?autostart=doug1015"> > Stand&#45;Up Comedy (Jerry Seinfeld, Dennis Miller, Bill Hicks, + more new stuff)</a></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">92/365</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">24</font></td>
      <td nowrap align="center" bgcolor="#001E32" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>19</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><a href="sbin/shoutcast-playlist.pls?rn=179073&addr=216.32.166.89:5944&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=80s rock pop" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E5A">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E5A"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[80s rock pop]</font></b> <a id="listlinks" target="_scurl" href="http://www.audiosoft.net"> Audiosoft Network - New Upbeat Mix of the 80`s - CD Quality</a></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">85/365</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E5A">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E5A"><font face="Arial, Helvetica" size="2" color="#FFFFFF">128</font></td>
      <td nowrap align="center" bgcolor="#001E5A" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>

    <tr>
      <td width="35" nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><b>20</b></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><a href="sbin/shoutcast-playlist.pls?rn=2071&addr=207.136.100.50:9000&file=filename.pls"><img src="images/tunein.gif" border="0" width="49" height="15"></a>&nbsp;<a href="chat.phtml?g=Mixed Pop" target="chat" onClick="setWin('chat',600,440)"><img src="images/chat.gif" border="0" width="49" height="15"></a></font></td>
      <td width="10" nowrap align="center" bgcolor="#001E32">&nbsp;</td>
      <td width="100%" align="left" bgcolor="#001E32"><font face="Arial" size="2" color="#FFFFFF"><font size="1"><b>[Mixed Pop]</font></b> <font color=#ff0000 size=-2>CLUSTER </font><a id="listlinks" target="_scurl" href="http://radio.tucows.com">ParaRadio</a><br>
<font size="1"><font color="#FF0000">Now Playing:</font> Pop/24/Alanis_Morissette_-_Hand_in_my_pocket.mp3</font></font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">79/512</font></td>
      <td nowrap align="center" width="10" bgcolor="#001E32">&nbsp;</td>
      <td nowrap align="center" bgcolor="#001E32"><font face="Arial, Helvetica" size="2" color="#FFFFFF">24</font></td>
      <td nowrap align="center" bgcolor="#001E32" width="10">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10" nowrap align="center"></td>
    </tr>


    <tr>
      <td colspan="10" align="center" valign="middle" height="4"><font face="Arial, Helvetica" size="1" color="#FFFFFF"><img border="0" src="images/bluebar.gif" width="100%" height="2"></font></td>
    </tr>
    <tr>
      <td width="35" nowrap align="center"><font face="Arial, Helvetica" size="1">Rank</font></td>
      <td nowrap align="center" width="10"></td>
      <td nowrap align="center"><font face="Arial, Helvetica" size="1">Action</font></td>
      <td nowrap align="center" width="10"></td>
      <td width="100%" nowrap align="center"><font face="Arial, Helvetica" size="1">Genre [Description]</font></td>
      <td nowrap align="center" width="10"></td>
      <td nowrap align="center"><font face="Arial, Helvetica" size="1">Listeners/Max</font></td>
      <td nowrap align="center" width="10"></td>
      <td nowrap align="center"><font face="Arial, Helvetica" size="1">Bitrate</font></td>
      <td nowrap align="center" width="10"></td>
    </tr>
  </table>

<table cellpadding="5" cellspacing="5" border="0" align="center">
  <tr>
    <td align="left" valign="top" nowrap>
      <form action="http://yp.shoutcast.com">
      <font face="Arial, Helvetica" size="1">List by Genre:<br>
      <SELECT name="genre" onChange="top.location.href='http://yp.shoutcast.com/?genre=' + this.options[selectedIndex].value;">
      <OPTION VALUE="TopTen" selected>-- Choose a genre --
      <OPTION VALUE="TopTen">-=[Top 25 Streams]=-
      <OPTION VALUE="Classical">Classical
      <OPTION VALUE="Comedy">Comedy
      <OPTION VALUE="Country">Country
      <OPTION VALUE="Techno">Techno
      <OPTION VALUE="Dance">Dance/House
      <OPTION VALUE="Funk">Funk
      <OPTION VALUE="Jazz">Jazz
      <OPTION VALUE="Metal">Metal
      <OPTION VALUE="Mixed">Mixed
      <OPTION VALUE="Pop">Pop
      <OPTION VALUE="R%26B">R&amp;B
      <OPTION VALUE="Rap">Rap
      <OPTION VALUE="Rock">Rock/Alternative
      <OPTION VALUE="Talk">Talk
      <OPTION VALUE="Various">Various
      <OPTION VALUE="80s">The '80s
      <OPTION VALUE="70s">The '70s
      </SELECT> 
      &nbsp;<input border="0" src="images/list.gif" type="image" value="List" width="39" height="20" valign="bottom"></font></form>

</td>
    <td width="25" nowrap></td>
    <td align="left" valign="top" nowrap>
      <FORM action="http://yp.shoutcast.com/index.phtml">
      <font face="Arial, Helvetica" size="1">Search for:<br>
      <INPUT name="s" size=20>
      &nbsp;<input border="0" src="images/search.gif" type="image" value="List" width="56" height="20" valign="absbottom"><br>
      <INPUT name="st" type=radio value="gs" CHECKED>Genre or Stream Title<br> 
      <INPUT name="st" type=radio value="st">Song or Artist played in past 30 minutes<br> 
      <font size="2">Limit search to
      <SELECT name="l">
      <OPTION value="5">5
      <OPTION value="10">10
      <OPTION value="25" selected>25
      <OPTION value="30">30
      <OPTION value="50">50
      <OPTION value="100">100
      </SELECT>
      results.</font></font></td>
  </tr>
  <tr>
  <td colspan="3" align="center">
      <form action="http://yp.shoutcast.com/">
<!--      <form action="http://yp.shoutcast.com">  -->
      <table cellpadding="0" cellspacing="0" border="0">
      <tr>
      <td align="left">
      <font face="Arial, Helvetica" size="1">Limit by Bandwidth<br>
      <SELECT name="bitrate" onChange="top.location.href='http://yp.shoutcast.com/?bitratelessthan=' + this.options[selectedIndex].value;">
      <OPTION VALUE="any" > -- Any Internet Connection  --
      <OPTION VALUE="28" > 28.8 Modem
      <OPTION VALUE="33" > 33.6 Modem
      <OPTION VALUE="56" > 56K Modem
      <OPTION VALUE="128" > 128kbps ISDN
      <OPTION VALUE="any" > 256 DSL/Cable/LAN
      </SELECT></td>
      <td valign="bottom">&nbsp;<input border="0" src="images/list.gif" type="image" value="List" width="39" height="20" valign="bottom"></font></td></tr></table></form>
  </td>
  </tr>
</table>
<!-- Begin "What is Shoutcast!" -->

<br>
<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td width="50%">
      <img border="0" src="images/whatis.gif" width="180" height="50" hspace="10">
    </td>
    <td width="50%"></td>
  </tr>
  <tr>
    <td width="100%" colspan="2">
      <img border="0" src="images/bluebar.gif" width="100%" height="2">
   </td>
  </tr>
  <tr>
    <td widht="100%" colspan="2">
      <table align="center" border="0" width="96%" cellpadding="0" cellspacing="5">
        <tr>
          <td>
            <font face="Arial" Size="2" color="#FFFFFF"><b>SHOUTcast</b> is Nullsoft's Winamp-based distributed streaming audio system.
            Now you can listen to live streaming audio, and even broadcast your own SHOUTcast station from the comfort of your regular Internet connection. If you don't already have it, you'll need to <A HREF="http://www.winamp.com/download/">download Winamp</A> to experience SHOUTcast.  New users visit our tutorials for <a href="download/index.html">listening</a> or <a href="download/index.html">becoming a SHOUTcast DJ</a>.
            </font>
          </td>
        <tr>
      </table>
    </td>
  </tr>
</table>
<br>

<!-- Begin Main Content News Article -->

<table border="0" width="100%" height="20" cellspacing="0" cellpadding="0">
  <tr>
    <td width="50%"><a name="news"><img border="0" src="images/whatsnew.gif" hspace="10" width="180" height="50"></a><br><br></td>
    <td width="50%"></td>
  </tr>
  <tr>
    <td width="100%" colspan="2"><img border="0" src="images/bluebar.gif" width="100%" height="2"></td>
  </tr>
</table>
<br>

<!-- NEWS BEGINS -->
  <table border="0" width="96%" cellspacing="0" cellpadding="1" align="center">
    <tr>
      <td width="6" nowrap bgcolor="#FFC800"></td>
      <td width="100%" bgcolor="#FFC800">
        <font color="#000000" face="Arial">
        <b>NEW! SHOUTcast 1.6.0b1 AVAILABLE
      </td>
      <td valign="middle" align="center" bgcolor="#FFC800">
        <font size="1" face="Arial" color="#000000">Released<br>
        02.16.2000</font></td>
    </tr>
    <tr>
      <td width="100%" colspan="3">
        <br>
        <blockquote><font color="#FFFFFF" face="Arial, Helvetica" size="2">

Worth the download, this beta release includes new support for:
<BR>
<UL>
<LI>XML-based status queries (query via http://server:port/admin.cgi?pass=password&mode=viewxml) -- this feature will allow almost any server-side scripting language (PHP, Dynamo, ASP, whatever) to easily parse and display information in real-time about your SHOUTcast server, or you can peek at it in IE as well if you're into that sort of thing.  This feature was requested by the band that's responsible for everything warped about tom, the almighty <A HREF="http://www.chocodog.com/ween/">Ween</A>.  Someday I hope I can get them to make the Tom Pepper theme song.  Until then, buy their shit.
<LI>SHOUTcast now does on-demand content as well.  Gary G-Whiz, my bud over at <A HREF="http://www.bringthenoise.com">Bring The Noise!</A> wanted a way to put up archives of past shows while disabling that icky save-to-disk option in Winamp.  There you go.  To make it go, just drop .mp3 files in a directory named content in the same folder as sc_serv.  Then, play 'em back by pointing winamp at http://server:port/content/file.mp3.
<LI>But wait, we didn't stop there.  Just like SHOUTcast streams need a playlist to intermediate between winamp and the web browser, so does the on-demand content.  So, you can also point web browsers at http://server:port/content/file.pls, and the server will automatically generate a playlist file for a on-demand mp3 file with the same name in the content folder.
<LI>AOL has, like, a bazillion of these Digital Unix boxes.  So, now there's a SHOUTcast build for DEC OSF (digital Unix) 4.0.
<LI>Fixed a bug with 1.5.x where if the shoutcast server lost contact with yp.shoutcast.com, it would give up and never try to phone home until you restarted the server process.  Whoops.
<LI>Reduced the likelihood of an already difficult bug to bring out where the client thread would occasionally get stuck in a loop and listeners wouldn't be able to get any data while the source thread would keep chugging away happily.
</UL>

Here's the download links for the beta:

<blockquote>
<font face="Arial, Helvetica" size="2" color="#DDDDDD">
        <B><font color="#FF0000">SHOUTcast WIN32 Console/GUI server v1.6.0 beta 1</font> [<A HREF="http://scastweb2-qfe0.spinner.com/download/scast/shoutcast-1-6-0-b1-windows.zip">DOWNLOAD</A>]</B><BR>
        <BLOCKQUOTE>This SHOUTcast server runs on Windows 95, Windows 98, Windows NT, and Windows 2000 for Intel hardware.  You *CAN* run the shoutcast server on the same machine running Winamp and the SHOUTcast DSP Plu
g-in.</BLOCKQUOTE>

        <B><font color="#FF0000">SHOUTcast Solaris Sparc 2.7 server v1.6.0 beta 1</font> [<A HREF="http://scastweb2-qfe0.spinner.com/download/scast/shoutcast-1-6-0-b1-solaris-sparc.tar.gz">DOWNLOAD</A>]</B><BR>
        <BLOCKQUOTE>This SHOUTcast server runs on Solaris boxes with Sparc processors, and was compiled u
nder 2.7 (Solaris 7) using gcc 2.95.</BLOCKQUOTE>

        <B><font color="#FF0000">SHOUTcast FreeBSD server v1.6.0 beta 1</font> [<A HREF="http://scastweb2-qfe0.spinner.com/download/scast/shoutcast-1-6-0-b1-freebsd-elf.tar.gz">DOWNLOAD</A>]</B><BR>
        <BLOCKQUOTE>This SHOUTcast server runs on FreeBSD, and was built using gcc 2.95 under FreeBSD 4.0
.</BLOCKQUOTE>

        <B><font color="#FF0000">SHOUTcast Linux server (glibc) v1.6.0 beta 1</font> [<A HREF="http://scastweb2-qfe0.spinner.com/download/scast/shoutcast-1-6-0-b1-linux-glibc.tar.gz">DOWNLOAD</A>]</B><BR>
        <BLOCKQUOTE>This SHOUTcast server runs on most versions of Linux, and is an elf binary compiled with glibc.  It was built under kernel 2.2.14.  SHOUTcast no longer supports older Linux kernels running libc5.</BLOCKQUOTE>

        <B><font color="#FF0000">SHOUTcast DEC OSF 4.0 (Digital Unix) server v1.6.0 beta 1</font> [<A HREF="http://scastweb2-qfe0.spinner.com/download/scast/shoutcast-1-6-0-b1-osf-4.tar.gz">DOWNLOAD</A>]</B><BR>
        <BLOCKQUOTE>This SHOUTcast server runs on Digital Unix 4.0, and was compiled using gcc 2.95.</BLOCKQUOTE>

        <B><font color="#FF0000">SHOUTcast IRIX 6.x server v1.6.0 beta 1</font> [<A HREF="http://scastweb2-qfe0.
spinner.com/download/scast/shoutcast-1-6-0-b1-irix-6.tar.gz">DOWNLOAD</A>]</B><BR>
        <BLOCKQUOTE>This SHOUTcast server runs on SGI IRIX, and was compiled under 6.2 using the native S
GI compiler.  Most people running other versions of IRIX 6 claim it works there, too.</BLOCKQUOTE>


</BLOCKQUOTE>

Feedback (please no support emails) to <A HREF="mailto:tom@winamp.com?subject=SHOUTcast">me</A>.
        <br><br>-<font color="#FF0000">Tom's Grosse Krautwagen</font>
        </blockquote></td>

    </tr>
  </table>
<!-- ITEM END -->

<!-- NEWS BEGINS -->
  <table border="0" width="96%" cellspacing="0" cellpadding="1" align="center">
    <tr>
      <td width="6" nowrap bgcolor="#FFC800"></td>
      <td width="100%" bgcolor="#FFC800">
        <font color="#000000" face="Arial">
        <b>NEW! SHOUTcast 1.5.0 RELEASED
      </td>
      <td valign="middle" align="center" bgcolor="#FFC800">
        <font size="1" face="Arial" color="#000000">Released<br>
        01.20.2000</font></td>
    </tr>
    <tr>
      <td width="100%" colspan="3">
        <br>
        <blockquote><font color="#FFFFFF" face="Arial, Helvetica" size="2">

<B>IMPORTANT UPDATE</B>:  Everyone using the DSP plugin version 1.5.0b1 needs
to upgrade to 1.5.0b2 to get AIM, ICQ, and IRC functionality in the
directory.  It's available <A HREF="http://scastweb2-qfe0.spinner.com/download/scast/dsp150b2.exe">here</A>.<BR><BR> 

Well, we did a lot more than we were expecting.  SHOUTcast server has a new
spiffy web frontend, and a whole slew of new features, like:<BR>
<UL>
<LI>Complete rewrite of source
<LI>Now 4 thread model instead of n+3, much more efficient
<LI>Fixed annoying year 2000 log display anomaly (thank you tm struct)
<LI>Code no longer leaky on any supported OS to best of our knowledge
<LI>No more wierd signals sneaking in and killing sc_serv on Solaris
<LI>Addition of IRC, AIM, and ICQ flags for directory
<LI>Addition of Bans via web interface -- kick and ban the bastards
<LI>Addition of Reserved connects -- always permit connects by IP
<LI>Low-bandwidth status report for Palm VII (http://server/7.html)
<LI>New hyperleet web interface (thanks for the help Steve)
<LI>Last n songs integrated into web interface (1-20)
<LI>Admin and Broadcast passwords can optionally be different (no more excuses live365)
<LI>Listener list (http) now sorted by connect time
<LI>and more...
</UL>

Go get it on the ol' download pages.  There's a completely new broadcaster
plug-in, crossfading plug-in, and NULL output plug-in as well for you DJs.
Really good stuff, especially the feedback options with IRC, AIM, or ICQ.  Tag's had it up and running for quite some time with no problems under Win98.  using the stock config we've got (latest Winamp, fairly basic Win98 install, crossfader output, aureal vortex2 soundcard, and don't forget 3,500 Trance MP3s) you should experience the same pleasure.<BR><BR>
On a more personal note, I'm super proud of Tag's efforts to make 1.5.0 the best SHOUTcast server ever.  I'm hoping you'll agree with my assessment that 1.5.0 is a highly reliable, high-performance product.  I pass along feedback that goes either way.<BR><BR>
And now Tag and I bury our heads into a whole new version.  1.5.0 lays the groundwork for a whole new breed of product, which we're looking to launch on March 8th.  We'll see you then!<BR><BR>

Feedback (please no support emails) to <A HREF="mailto:tom@winamp.com?subject=SHOUTcast">me</A>.  And, yes, tech support en masse is very near.
        <br><br>-<font color="#FF0000">Tom, the Narcoleptic</font>
        </blockquote></td>
    </tr>
  </table>
<!-- ITEM END -->

<!-- NEWS BEGINS -->
  <table border="0" width="96%" cellspacing="0" cellpadding="1" align="center">
    <tr>
      <td width="6" nowrap bgcolor="#FFC800"></td>
      <td width="100%" bgcolor="#FFC800">
        <font color="#000000" face="Arial">
        <b>NEW! Mondo update
      </td>
      <td valign="middle" align="center" bgcolor="#FFC800">
        <font size="1" face="Arial" color="#000000">Released<br>
        01.10.2000</font></td>
    </tr>
    <tr>
      <td width="100%" colspan="3">
        <br>
        <blockquote><font color="#FFFFFF" face="Arial, Helvetica" size="2">
Greetings to all of you.  Hope the new year's treating you well.<BR><BR>

Sorry we've been silent for awhile, but we've been horribly busy getting servers
moved from the old homebase to AOL WHQ, and getting the new winamp.com up and running, 
which was a project started last September.  Part of that process, as most of you have
noticed, was the disappearance of .plans (finger updates) and the forums sections.  
Those are on the way back in, once the new database system gets in gear.  Code's 
already done for the new finger stuff as well, we're just waiting on some holes
in AOL's firewall to make it all kosher.<br><br>

So, some of you also noticed that chat's been added here, though most of you
have complained about not being able to control the channel name.  Patience.
You'll also be happy to learn that server 1.3 is due on January 20th, along
with the transfer of this site onto new hardware.  What's really significant
about 1.3 is a whole new model of how streams and threads are managed.  It's
about 10 times as stable as it was before.  Oh, yeah, and we fixed that annoying
xx/xx/100 log display bug everyone's complaining about.  Depending on how time
shapes up this week, there's a new feature or two as well that might sneak 
their way into 1.3.  Solaris users rejoice,
the primary development platform is now Sparc Solaris, for our own internal 
hardware availability and for our buddies over at live365.  Maybe we'll get
them to put streaming title support in someday...<br><br>

The biggest news, I can't tell you about unfortunately.  You'll just have
to wait until March 8th.<br><br>

Watch here.  Betas should be forthcoming this week.

        <br><br>-<font color="#FF0000">Tom, Brokaw</font>
        </blockquote></td>
    </tr>
  </table>
<!-- ITEM END -->


<!-- Begin Footer -->

<img border="0" src="images/bluebar.gif" width="100%" height="2">
<center>
<a href="index.phtml">
<img src="images/footer.gif" width="428" height="71" align="center" border="0"></a><br><br>
<font face="Arial" size="1" color="#AAAAAA">
Copyright Nullsoft Inc, 1999<br>
[<a href="disclaimer.phtml" target="Disclaimer" onClick="setWin('Disclaimer',500,300)">terms of use / disclaimer / copyright complaints</a>]
</font>
</center>

</body>
</html>



