--20:51:59--  http://www.elea.gr:80/
           => `www.elea.gr/index.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,683 [text/html]

    0K -> ....                                                   [100%]

20:52:01 (3.42 KB/s) - `www.elea.gr/index.html' saved [4683/4683]

Loading robots.txt; please ignore errors.
--20:52:01--  http://www.elea.gr:80/no-robots.txt
           => `www.elea.gr/no-robots.txt'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 404 Not Found
20:52:02 ERROR 404: Not Found.

--20:52:02--  http://www.elea.gr:80/imageSG7.JPG
           => `www.elea.gr/imageSG7.JPG'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 2,926 [image/jpeg]

    0K -> ..                                                     [100%]

20:52:03 (3.19 KB/s) - `www.elea.gr/imageSG7.JPG' saved [2926/2926]

--20:52:03--  http://www.elea.gr:80/imageJQD.JPG
           => `www.elea.gr/imageJQD.JPG'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 3,793 [image/jpeg]

    0K -> ...                                                    [100%]

20:52:05 (4.12 KB/s) - `www.elea.gr/imageJQD.JPG' saved [3793/3793]

--20:52:05--  http://www.elea.gr:80/index.old.html
           => `www.elea.gr/index.old.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 8,999 [text/html]

    0K -> ........                                               [100%]

20:52:08 (4.37 KB/s) - `www.elea.gr/index.old.html' saved [8999/8999]

--20:52:08--  http://www.elea.gr:80/backgrounds/bgmain.gif
           => `www.elea.gr/backgrounds/bgmain.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 50 [image/gif]

    0K ->                                                        [100%]

20:52:09 (140.06 B/s) - `www.elea.gr/backgrounds/bgmain.gif' saved [50/50]

--20:52:09--  http://www.elea.gr:80/backgrounds/backtop.gif
           => `www.elea.gr/backgrounds/backtop.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 226 [image/gif]

    0K ->                                                        [100%]

20:52:11 (651.30 B/s) - `www.elea.gr/backgrounds/backtop.gif' saved [226/226]

--20:52:11--  http://www.elea.gr:80/banner/topbanner.gif
           => `www.elea.gr/banner/topbanner.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 9,201 [image/gif]

    0K -> ........                                               [100%]

20:52:13 (4.60 KB/s) - `www.elea.gr/banner/topbanner.gif' saved [9201/9201]

--20:52:13--  http://www.elea.gr:80/images/elealogo.gif
           => `www.elea.gr/images/elealogo.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 3,624 [image/gif]

    0K -> ...                                                    [100%]

20:52:15 (4.12 KB/s) - `www.elea.gr/images/elealogo.gif' saved [3624/3624]

--20:52:15--  http://www.elea.gr:80/images/tablebg2.gif
           => `www.elea.gr/images/tablebg2.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 127 [image/gif]

    0K ->                                                        [100%]

20:52:16 (257.09 B/s) - `www.elea.gr/images/tablebg2.gif' saved [127/127]

--20:52:16--  http://www.elea.gr:80/html/eleainfo/1982.html
           => `www.elea.gr/html/eleainfo/1982.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 10,264 [text/html]

    0K -> ..........                                             [100%]

20:52:19 (4.72 KB/s) - `www.elea.gr/html/eleainfo/1982.html' saved [10264/10264]

--20:52:20--  http://www.elea.gr:80/html/automsg.html
           => `www.elea.gr/html/automsg.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 6,578 [text/html]

    0K -> ......                                                 [100%]

20:52:23 (4.38 KB/s) - `www.elea.gr/html/automsg.html' saved [6578/6578]

--20:52:23--  http://www.elea.gr:80/html/nea/nea.html
           => `www.elea.gr/html/nea/nea.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,714 [text/html]

    0K -> ....                                                   [100%]

20:52:25 (3.37 KB/s) - `www.elea.gr/html/nea/nea.html' saved [4714/4714]

--20:52:25--  http://www.elea.gr:80/html/glossa.html
           => `www.elea.gr/html/glossa.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,590 [text/html]

    0K -> ....                                                   [100%]

20:52:27 (3.40 KB/s) - `www.elea.gr/html/glossa.html' saved [4590/4590]

--20:52:27--  http://www.elea.gr:80/html/contact.html
           => `www.elea.gr/html/contact.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,684 [text/html]

    0K -> ....                                                   [100%]

20:52:29 (3.48 KB/s) - `www.elea.gr/html/contact.html' saved [4684/4684]

--20:52:29--  http://www.elea.gr:80/html/english/1982.html
           => `www.elea.gr/html/english/1982.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 8,926 [text/html]

    0K -> ........                                               [100%]

20:52:32 (4.64 KB/s) - `www.elea.gr/html/english/1982.html' saved [8926/8926]

--20:52:32--  http://www.elea.gr:80/images/tablebot2.gif
           => `www.elea.gr/images/tablebot2.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 1,199 [image/gif]

    0K -> .                                                      [100%]

20:52:33 (3.48 KB/s) - `www.elea.gr/images/tablebot2.gif' saved [1199/1199]

--20:52:33--  http://www.elea.gr:80/images/1982.gif
           => `www.elea.gr/images/1982.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,757 [image/gif]

    0K -> ....                                                   [100%]

20:52:36 (3.54 KB/s) - `www.elea.gr/images/1982.gif' saved [4757/4757]

--20:52:36--  http://www.elea.gr:80/banner/emkatbanner.gif
           => `www.elea.gr/banner/emkatbanner.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 58,489 [image/gif]

    0K -> .......... .......... .......... .......... .......... [ 87%]
   50K -> .......                                                [100%]

20:52:42 (10.57 KB/s) - `www.elea.gr/banner/emkatbanner.gif' saved [58489/58489]

--20:52:43--  http://www.elea.gr:80/banner/alfabanner.gif
           => `www.elea.gr/banner/alfabanner.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 15,458 [image/gif]

    0K -> .......... .....                                       [100%]

20:52:46 (5.94 KB/s) - `www.elea.gr/banner/alfabanner.gif' saved [15458/15458]

--20:52:47--  http://www.elea.gr:80/banner/alegro.gif
           => `www.elea.gr/banner/alegro.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 24,196 [image/gif]

    0K -> .......... .......... ...                              [100%]

20:52:51 (7.47 KB/s) - `www.elea.gr/banner/alegro.gif' saved [24196/24196]

--20:52:51--  http://www.elea.gr:80/banner/texnika.gif
           => `www.elea.gr/banner/texnika.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 57,772 [image/gif]

    0K -> .......... .......... .......... .......... .......... [ 88%]
   50K -> ......                                                 [100%]

20:52:58 (9.95 KB/s) - `www.elea.gr/banner/texnika.gif' saved [57772/57772]

--20:52:58--  http://www.elea.gr:80/banner/delta.gif
           => `www.elea.gr/banner/delta.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 3,221 [image/gif]

    0K -> ...                                                    [100%]

20:53:00 (3.76 KB/s) - `www.elea.gr/banner/delta.gif' saved [3221/3221]

--20:53:04--  http://www.elea.gr:80/banner/cgs.gif
           => `www.elea.gr/banner/cgs.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 15,974 [image/gif]

    0K -> .......... .....                                       [100%]

20:53:08 (6.10 KB/s) - `www.elea.gr/banner/cgs.gif' saved [15974/15974]

--20:53:08--  http://www.elea.gr:80/images/bgtables.gif
           => `www.elea.gr/images/bgtables.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 118 [image/gif]

    0K ->                                                        [100%]

20:53:09 (331.46 B/s) - `www.elea.gr/images/bgtables.gif' saved [118/118]

--20:53:09--  http://www.elea.gr:80/html/gov.html
           => `www.elea.gr/html/gov.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 10,290 [text/html]

    0K -> ..........                                             [100%]

20:53:12 (4.89 KB/s) - `www.elea.gr/html/gov.html' saved [10290/10290]

--20:53:12--  http://www.elea.gr:80/html/chmbers-list.html
           => `www.elea.gr/html/chmbers-list.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 27,973 [text/html]

    0K -> .......... .......... .......                          [100%]

20:53:16 (8.10 KB/s) - `www.elea.gr/html/chmbers-list.html' saved [27973/27973]

--20:53:16--  http://www.elea.gr:80/html/politikoi.html
           => `www.elea.gr/html/politikoi.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,830 [text/html]

    0K -> ....                                                   [100%]

20:53:18 (3.56 KB/s) - `www.elea.gr/html/politikoi.html' saved [4830/4830]

--20:53:18--  http://www.elea.gr:80/html/mesitika.html
           => `www.elea.gr/html/mesitika.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,278 [text/html]

    0K -> ....                                                   [100%]

20:53:20 (3.29 KB/s) - `www.elea.gr/html/mesitika.html' saved [4278/4278]

--20:53:20--  http://www.elea.gr:80/images/bgtablebot.gif
           => `www.elea.gr/images/bgtablebot.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 1,757 [image/gif]

    0K -> .                                                      [100%]

20:53:22 (2.42 KB/s) - `www.elea.gr/images/bgtablebot.gif' saved [1757/1757]

--20:53:22--  http://www.elea.gr:80/html%5Cnea%5Cdiktiothite.html
           => `www.elea.gr/html\nea\diktiothite.html'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 404 Not Found
20:53:23 ERROR 404: Not Found.

--20:53:23--  http://www.elea.gr:80/banner/diktiothite-banner.gif
           => `www.elea.gr/banner/diktiothite-banner.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 32,988 [image/gif]

    0K -> .......... .......... .......... ..                    [100%]

20:53:27 (8.41 KB/s) - `www.elea.gr/banner/diktiothite-banner.gif' saved [32988/32988]

--20:53:28--  http://www.elea.gr:80/banner/staroffice-anima.gif
           => `www.elea.gr/banner/staroffice-anima.gif'
Connecting to www.elea.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,865 [image/gif]

    0K -> ....                                                   [100%]

20:53:30 (3.38 KB/s) - `www.elea.gr/banner/staroffice-anima.gif' saved [4865/4865]

Converting www.elea.gr/index.old.html... done.
Converting www.elea.gr/index.html... done.

FINISHED --20:53:30--
Downloaded: 341,550 bytes in 31 files
Converting www.elea.gr/index.html... done.
Converting www.elea.gr/index.old.html... done.
Converting www.elea.gr/html/eleainfo/1982.html... done.
Converting www.elea.gr/html/automsg.html... done.
Converting www.elea.gr/html/nea/nea.html... done.
Converting www.elea.gr/html/glossa.html... done.
Converting www.elea.gr/html/contact.html... done.
Converting www.elea.gr/html/english/1982.html... done.
Converting www.elea.gr/html/gov.html... done.
Converting www.elea.gr/html/chmbers-list.html... done.
Converting www.elea.gr/html/politikoi.html... done.
Converting www.elea.gr/html/mesitika.html... done.
