--04:14:28--  http://www.kablo.sk:80/
           => `www.kablo.sk/index.html'
Connecting to www.kablo.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]

    0K -> ....

04:14:30 (5.77 KB/s) - `www.kablo.sk/index.html' saved [4800]

Loading robots.txt; please ignore errors.
--04:14:30--  http://www.kablo.sk:80/no-robots.txt
           => `www.kablo.sk/no-robots.txt'
Connecting to www.kablo.sk:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
04:14:30 ERROR 404: Object Not Found.

--04:14:30--  http://www.kablo.sk:80/wfd2.jpg
           => `www.kablo.sk/wfd2.jpg'
Connecting to www.kablo.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 19,715 [image/jpeg]

    0K -> .......... .........                                   [100%]

04:14:34 (7.18 KB/s) - `www.kablo.sk/wfd2.jpg' saved [19715/19715]

Converting www.kablo.sk/index.html... done.

FINISHED --04:14:34--
Downloaded: 24,515 bytes in 2 files
Converting www.kablo.sk/index.html... done.
