--10:38:43--  http://www.cardcentrum.sk:80/
           => `www.cardcentrum.sk/index.html'
Connecting to www.cardcentrum.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]

    0K -> ...

10:38:46 (4.34 KB/s) - `www.cardcentrum.sk/index.html' saved [3934]

Converting www.cardcentrum.sk/index.html... done.

FINISHED --10:38:46--
Downloaded: 3,934 bytes in 1 files
Converting www.cardcentrum.sk/index.html... done.
