--02:30:41--  http://www.micronet.gr:80/
           => `www.micronet.gr/index.html'
Connecting to www.micronet.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 26 [text/html]

    0K ->                                                        [100%]

02:30:41 (25.39 KB/s) - `www.micronet.gr/index.html' saved [26/26]

Converting www.micronet.gr/index.html... done.

FINISHED --02:30:41--
Downloaded: 26 bytes in 1 files
