



	
	<HTML><HEAD><TITLE>At-Auction Seller - Information</TITLE></HEAD><BODY BGCOLOR="white" TEXT="black" LINK="blue" ALINK="blue" VLINK="blue">
 



	<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH=600><TR><TD ALIGN=center>	<A HREF="http://www.At-Auction.com/index.cfm"><img src="http://www.At-Auction.com/images/navbarHome.gif" BORDER=0 ALT="Home"></A><A HREF="http://www.At-Auction.com/program/search.cfm"><img src="http://www.At-Auction.com/images/navbarSearch.gif" BORDER=0 ALT="Search"></A><A HREF="https://www.At-Auction.com/program/user.cfm"><img src="http://www.At-Auction.com/images/navbarRegister.gif" BORDER=0 ALT="Register"></A>	<A HREF="http://www.At-Auction.com/seller/helpSeller.cfm"><img src="http://www.At-Auction.com/images/navbarSellers.gif" BORDER=0 ALT="Sellers"></A><A HREF="http://www.At-Auction.com/program/list.cfm"><img src="http://www.At-Auction.com/images/navbarAllLots.gif" BORDER=0 ALT="List All Lots"></A><A HREF="http://www.At-Auction.com/program/editUser.cfm?bidStatus=1"><img src="http://www.At-Auction.com/images/navbarBidStatus.gif" BORDER=0 ALT="Bid Status"></A><A HREF="http://www.At-Auction.com/program/help.cfm"><img src="http://www.At-Auction.com/images/navbarHelp.gif" BORDER=0 ALT="Help"></A>
</TD></TR>	<TR><TD ALIGN=center BGCOLOR="white"><FONT SIZE=5 COLOR="navy" FACE="arial"><B>Seller - Information</B></FONT></TD></TR></TABLE><P>


<P>

<H2>Thanks for your interest in posting items on our site!</H2>

To get started, simply <A HREF="http://www.At-Auction.com/seller/createLot.cfm">create your auction lot</A>



<P>

<!--
This page generated by Emaze Auction version 2.1, 05/24/1999
copyright 1998-1999 by Emaze Software Corporation
http://www.emaze.com, sales@emaze.com
-->

 

<P>
</BODY>
</HTML>