--21:30:39--  http://kr.astalavista.box.sk:80/
           => `kr.astalavista.box.sk/index.html'
Connecting to kr.astalavista.box.sk:80... connected!
HTTP request sent, awaiting response... 302 Found
Location: http://kr.astalavista.box.sk/cgi-bin/robot [following]
--21:30:39--  http://kr.astalavista.box.sk:80/cgi-bin/robot
           => `kr.astalavista.box.sk/cgi-bin/robot'
Connecting to kr.astalavista.box.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]

    0K -> .......

21:30:41 (8.07 KB/s) - `kr.astalavista.box.sk/cgi-bin/robot' saved [7917]

Converting kr.astalavista.box.sk/cgi-bin/robot... done.

FINISHED --21:30:41--
Downloaded: 7,917 bytes in 1 files
Converting kr.astalavista.box.sk/cgi-bin/robot... done.
