<HTML><HEAD>
<!--begin title.tmpl-->
<TITLE>BroadcastAMERICA.com</TITLE>
<!--end title.tmpl-->

<link rel=stylesheet href="/home/master.css" type="text/css">

<script language="Javascript">
<!--
function fbwindow() {
	var feedback = window.open('http://www.broadcastamerica.com/feedback/index.html','feedback','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,width=360,height=360');
	feedback.focus();
}
//-->
</script>

<script language="Javascript" src="../home/js/launch.js"></script>

<script LANGUAGE="javascript">
<!--
this.name="home"
//-->
</script>

<META NAME="KEYWORDS" CONTENT="Music, Sports,Talk, Television,News,BroadcastAmerica.com,Live,Radio,Movies,Clubs,BroadcastSports.com,BroadcastTVNews.com/BroadcastTalk.com,BroadcastClubs.com">
<META NAME="DESCRIPTION" CONTENT="BroadcastAmerica.com: the worlds largest streaming media company with over 600 exclusive live radio stations and thousands of On Demand streams">
<META HTTP-EQUIV="Refresh" CONTENT="300; URL=http://music.broadcastamerica.com/">

</HEAD>
<BODY BACKGROUND="http://images.broadcastamerica.com/main/bg.gif" TEXT="#FFFFFF" BGCOLOR="#333333" LINK="#FFFFFF" VLINK="#FFFFFF" ALINK="#FFFF99" TOPMARGIN="5" LEFTMARGIN="5" MARGINWIDTH="5" MARGINHEIGHT="5">

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
<!--begin logo.phtml-->
	<TD ALIGN="Left" VALIGN="Top" WIDTH="255"><a href="../index.html"><IMG SRC="http://images.broadcastamerica.com/main/ba_logo.gif" WIDTH="255" HEIGHT="81" BORDER="0" ALT="BroadcastAmerica.com"></a></TD>

<!--end logo.phtml-->
<!--begin main_ad_top.phtml-->
<TD ALIGN="CENTER" VALIGN="MIDDLE"><A HREF="http://ad.doubleclick.net/jump/ba.dart/bannertop;sz=468x60;ord=18622381613?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/bannertop;sz=468x60;ord=18622381613?" border=0 height="60" width="468"></A></TD>

<!--end main_ad_top.phtml-->
</TR>

<TR>
	<TD COLSPAN="2" ALIGN="Left" VALIGN="Top">
<!--begin navbar.phtml-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_l.gif" WIDTH="13" HEIGHT="36"></TD>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_r.gif" WIDTH="13" HEIGHT="36"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Middle" WIDTH="739" HEIGHT="28">
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="220">
<FORM ACTION="http://search.broadcastamerica.com/results.phtml" METHOD="GET">
<TR><TD>
<font id="a12"><SELECT NAME="which">
<OPTION value=site>Search Channels</OPTION>
<OPTION value=web>Search Web</OPTION>
<OPTION value=music>Music</OPTION>
<OPTION value=sports>Sports</OPTION>
<OPTION value=clubs>Clubs</OPTION>
<OPTION value=talk>Talk</OPTION>
<OPTION value=tvnews>TV News</OPTION>
<OPTION value=movies>Movies</OPTION>
<OPTION value=urban>Urban</OPTION>
<OPTION value=bible>Christian</OPTION>
<OPTION value=comedy>Comedy</OPTION>
<OPTION value=wisdom>Wisdom</OPTION>
</SELECT></font>
</TD>
<TD><INPUT NAME="spec" TYPE=Text SIZE="8" MAXLENGTH="40"></TD><TD><INPUT NAME="FIND" TYPE=Submit VALUE="Find"></TD>
<TD ALIGN="Left" VALIGN="MIDDLE"><A HREF="http://www.goto.com/"><IMG SRC="http://images.broadcastamerica.com/main/goto_logo.gif" WIDTH="37" HEIGHT="23" BORDER="0"></A></TD></TR>
</FORM>
</TABLE>
</TD>

	<TD ALIGN="RIGHT" VALIGN="MIDDLE"><font id=a17><A HREF="../index.html">Home</A> | <A HREF="../mail/index.html">Free Voice/Fax/Email</A> | <A HREF="../news/index.html">World News</A> | <A HREF="../weather/scripts/index.html">Weather</A> | <A HREF="../customize/index.html">Customize</A> | <A HREF="index.html">Help</A></font></TD>
</TR>
</TABLE>

</TD>
</TR>
<TR>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="BOTTOM"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
</TR>
</TABLE>

<!--end navbar.phtml-->
	</TD>
</TR>
</TABLE>
<!--End Top Table	-->


<!--Begin Body Table	-->

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
<!--Begin LEFT TD-->
	<TD ALIGN="Left" VALIGN="Top">
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="116" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="600"></TD>

	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" HEIGHT="100%">

<!--begin leftnav_loc.tmpl-->

<!--end leftnav_loc.tmpl-->

<!--begin main_ad_1l.phtml-->
<center><A HREF="http://ad.doubleclick.net/jump/ba.dart/stream;sz=116x58;ord=2925551421941?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/stream;sz=116x58;ord=2925551421941?" border=0 height="58" width="116"></A></center><P>


<!--end main_ad_1l.phtml-->
	
<!--begin leftnav_main.phtml-->
<IMG SRC="http://images.broadcastamerica.com/main/t_streamchan.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12><a HREF="http://music.broadcastamerica.com/">Music Radio</a><BR>
<a HREF="http://sports.broadcastamerica.com/">Sports Radio</a><BR>
<a HREF="http://talk.broadcastamerica.com/">Talk Radio</a><BR>
<a HREF="http://tvnews.broadcastamerica.com/">Local TV News</a><BR>
<a HREF="http://weather.broadcastamerica.com/">Weather</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://bible.broadcastamerica.com/">Christian Radio</a><BR>
<a HREF="http://urban.broadcastamerica.com/">Urban Music Radio</a><BR>
<a HREF="http://latino.broadcastamerica.com/">Latin Radio</a><BR>
<a HREF="http://www.broadcasteurope.com/">European Radio</a><BR>
<a HREF="http://movies.broadcastamerica.com/">Movies and More</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://comedy.broadcastamerica.com/">Comedy</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://clubs.broadcastamerica.com/">Club Music</a><BR>
<a HREF="http://kids.broadcastamerica.com/">Kid's Radio</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://inspiration.broadcastamerica.com/">Wisdom</a><BR></font><P>

<A HREF="http://ad.doubleclick.net/jump/ba.dart/siaudio;sz=116x58;ord=2119518271648?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/siaudio;sz=116x58;ord=2119518271648?" border=0 height="58" width="116"></A>

<IMG SRC="http://images.broadcastamerica.com/main/t_shopping.gif" WIDTH="116" HEIGHT="28" vspace="3"><BR>
<a href="http://service.bfast.com/bfast/click?bfmid=2181&sourceid=35523158&categoryid=rn_bestsellers"><font id=a46>Barnes & Noble</font></a><br>
<a href="http://service.bfast.com/bfast/click?bfmid=22282494&siteid=35522081&bfpage=homepage"><font id=a46>Gifts.com</font></a><br>
<a href="http://service.bfast.com/bfast/click?bfmid=70780&sourceid=35521430&categoryid=banners"><font id=a46>proflowers.com</font></a><br>
<font id=a12>
<a HREF="../channels/onlinepsychic/index.html">Psychic Readings</a><BR>
<a HREF="../channels/connection/index.html">Personals</a></font><P>

<IMG SRC="http://images.broadcastamerica.com/main/t_thecompany.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12>
<a HREF="../company/factsheet.phtml">Fact Sheet</a><BR>
<a HREF="../company/about.phtml">About Us</a><BR>
<a HREF="../company/chanover.phtml">Channel Overview</a><BR>
<a HREF="../company/bios.phtml">Officer Bios</a><BR>
<a HREF="../company/investor.phtml">Investor Info</a><BR>
<a HREF="../advertising/index.html">Advertising</a><BR>
<a HREF="../company/contact.phtml">Contact Info</a><BR>
<a HREF="../company/press.phtml">Press Releases</a><BR>
<a HREF="../company/inthenews.phtml">In the News</a><BR>
<a HREF="../jobs/index.html">Jobs @</a></font><P>

<IMG SRC="http://images.broadcastamerica.com/main/t_helpfaq.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12><a HREF="index.html">Help</a><BR>
<a HREF="index.phtml#rm">Real Media</a><BR>
<a HREF="index.phtml#wm">Windows Media</a><BR>
<a HREF="index.phtml#qf">Quick Fixes</a><BR>
<a HREF="station_finder.phtml">Station Finder</a><BR>
<A HREF="javascript:fbwindow()">Feedback</a><BR>
<a HREF="index.phtml#form">Write to us</a></font><P>

<CENTER><a HREF="http://www.real.com/products/player/downloadrealplayer.html?wp=dl0899&src=hp_butn" TARGET="_blank"><img SRC="http://images.broadcastamerica.com/main/freerealplayer7.gif" WIDTH="88" HEIGHT="32" VSPACE="5" BORDER="0"></a><BR>

<A HREF="http://www.microsoft.com/windows/mediaplayer/en/download/default.asp"><IMG SRC="http://images.broadcastamerica.com/main/wmedia.gif" WIDTH="89" HEIGHT="32" BORDER="0" vspace="5"></A></CENTER>

<!--end leftnav_main.phtml-->
</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Middle"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>

<TR>
	<TD COLSPAN="3">
<!--begin main_ad_2l.phtml-->
<CENTER><a href="http://www.promoclick.com"><IMG SRC="http://images.broadcastamerica.com/ads/proclk_100x70.gif" WIDTH="100" HEIGHT="70" border="0" alt="ad banner" VSPACE="5"></A></CENTER>
<!--end main_ad_2l.phtml-->
	</TD>
</TR>
</TABLE>	

</TD>
<!--End LEFT TD-->

<!--Begin CENTER AREA TD-->
	<TD ALIGN="CENTER" VALIGN="Top">
<TABLE WIDTH="484px" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="12" HEIGHT="5"></TD>

</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="12" HEIGHT="5"></TD>
	<TD ALIGN="Left" VALIGN="Top"><IMG SRC="http://images.broadcastamerica.com/main/t_help.gif" WIDTH="243" HEIGHT="53" BORDER="0"></TD>
	<TD ALIGN="Left" VALIGN="Top"><IMG SRC="http://images.broadcastamerica.com/main/rt_sub_spacer.gif" WIDTH="229" HEIGHT="60"></TD>
</TR>
</TABLE>	

<table WIDTH="460px" BORDER="0" CELLSPACING="0" CELLPADDING="5px">
<TR>
        <TD ALIGN="RIGHT" VALIGN="Top" COLSPAN="3" background="http://images.broadcastamerica.com/main/list_top.gif"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></TD>
</TR>

<TR>
<TD ALIGN="RIGHT" bgcolor="#000000" colspan="3"><font id=a19b><IMG SRC="http://images.broadcastamerica.com/help/help_title.gif"></font></TD>
</TR>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td><TD ALIGN="center" bgcolor="003366"><font id=a17><a href="#rm">Real Media</a> | <a href="#wm">Windows Media</a> | <a href="#qf">Quick Fixes</a> | <a href="#form">Write to us</a> | <a href="station_finder.phtml">Station Finder</a></font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<TR>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<TD ALIGN="left"><font id=a17>BroadcastAmerica.com </font><font id=a13>is dedicated to providing you with the best possible experience every time you visit our Web site.  That's why we've assembled all the finest resources to answer your questions.  However, if you need additional information, feel free to use the <a href="#form">Help Request Form</a> at the bottom of this page.<br>
&nbsp;</font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td><td bgcolor="#003366" ALIGN="left"><a name="rm">
<font id=a19b>Real Media</font><br></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td>
<IMG SRC="http://images.broadcastamerica.com/help/real_help.gif" ALT="" WIDTH="72" HEIGHT="63" BORDER="0" ALIGN="right">
<font id=a17>RealPlayer 7 Basic: </font><font id=a13>(Windows or Macintosh)<br>
<a href="http://service.real.com/help/faq/rp7/rpb7inst.html#reqs">System Requirements</a><br>
<a href="http://www.real.com/player/index.html">Download</a><br>
<a href="http://www.real.com/player/index.html">Download Instructions</a><br>
<a href="http://service.real.com/help/faq/rp7/rpb7faq.html">FAQs</a></font><br>
<p><font id=a13>1. <a href="#rp1">I have RealPlayer version 5.0, but I cannot receive your content.</a><br>
2. <a href="#rp2">Why do I get a scripting error whenever I try to access a station on your site?</a><br>
3. <a href="#rp3">I have updated my browser and now my RealPlayer 7 will not work.</a><br>
4. <a href="#rp4">I already have RealPlayer 7 and the latest version of my web browser installed, but when I click on the "Listen" button to play a station, the player window is blank, or just says "Stopped" and will not connect to the station.</a><br>
5. <a href="#rp5">Why am I receiving the error message "Requested file not found. The link you followed may be outdated or inaccurate."?</a><br>&nbsp;</font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td bgcolor="#003366" ALIGN="left"><a name="wm">
<font id=a19b>Windows Media</font><br></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td><td>
<IMG SRC="http://images.broadcastamerica.com/help/wm_help.gif" ALT="" WIDTH="72" HEIGHT="63" BORDER="0" ALIGN="right">
<font id=a17>Windows Media Player: </font><font id=a13>(Windows {Macintosh: beta only})<br>
<a href="http://www.microsoft.com/windows/mediaplayer/en/download/sysreq.asp">System Requirements</a><br>
<a href=" http://www.microsoft.com/windows/windowsmedia/en/Download/default.asp">Download</a><br>
<a href="http://www.microsoft.com/windows/mediaplayer/en/support/InstallSupport.asp">Download Instructions</a><br>
<a href="http://www.microsoft.com/windows98/support/faq/SUPFAQMPlayer.asp">FAQs</a><br>&nbsp;</font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td bgcolor="#003366" ALIGN="left"><a name="qf">
<font id=a19b>RealPlayer Quick Fixes</font><br></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td ALIGN="left">
<a name="rp1"><font id=a17>Q1. I have RealPlayer version 5.0, but I cannot receive your content.</font><br>
<font id=a13 >A. You need to upgrade to RealPlayer 7 Basic, which is available as a free download from <a href="http://www.real.com/player">www.real.com/player</a>.  Just click on the link "RealPlayer 7 Basic is our free player."  For assistance in downloading and installing RealPlayer 7 on your computer, <a href="http://service.real.com/help/faq/rp7/rpb7faq.html">click here.</a></font>
<p><a name="rp2"><font id=a17>Q2. Why do I get a scripting error whenever I try to access a station on your site?</font><br>
<font id=a13 >A. You may be using an outdated version of your browser that does not support JavaScript.  The Internet is constantly evolving, and BroadcastAmerica.com takes advantage of today's newest technology. We recommend that PC users download the newest version of Internet Explorer, which is available as a free download from <a href="http://www.microsoft.com/windows/ie/">www.microsoft.com/windows/ie</a>.  Macintosh users should download the newest version of Netscape Communicator from <a href="http://www.netscape.com/download/">www.netscape.com/download</a>.</font>
<p><a name="rp3"><font id=a17>Q3. I have updated my browser and now my RealPlayer 7 will not work.</font><br>
<font id=a13 >A. It is a good idea to always download the newest browser. After you update your browser you must reinstall your RealPlayer 7 software. <a href="http://www.netscape.com/download/">Click here for download and installation instructions.</a></font> 
<p><a name="rp4"><font id=a17>Q4. I already have RealPlayer 7 and the latest version of my web browser installed, but when I click on the "Listen" button to play a station, the player window is blank, or just says "Stopped" and will not connect to the station.</font><br>
<font id=a13 >A. If you begin experiencing strange behavior with RealPlayer, we recommend re-installing it.  If you still have the file  you downloaded from Real's web site, simply double-click on that to begin the re-installation process.  If you cannot find this file, then you must download it again from <a href="http://www.real.com/player">www.real.com/player</a>.  Just click on the link "RealPlayer 7 Basic is our free player".  After re-installing RealPlayer, you should be able to access any of our streams immediately.</font>
<p><a name="rp5"><font id=a17>Q5. Why am I receiving the error message "Requested file not found. The link you followed may be outdated or inaccurate."?</font><br>
<font id=a13 >A. The station or program you are attempting to access may be experiencing technical difficulties.  If you receive this error, please alert our technical staff at <a href="mailto:tekhelp@broadcastamerica.com">tekhelp@BroadcastAmerica.com</a>.<br>
&nbsp;</font>
<p><a name="rp5"><font id=a17>Q6. I'm a Network Administrator and want configure my systems to allow our employees to listen to your site. What do I do"?</font><br>
<font id=a13 >A. Follow this link <a href="http://service.real.com/firewall/proxycfg.html">here</a>. You should be able to find all of the information you need.</font></TD>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</TR>

<form name="help" action="/home/scripts/help.cgi" method="post">
<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td valign="top" bgcolor="#003366" ALIGN="left"><font id="a19b">
<a name="form">Help Request Form:</font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td align="left" bgcolor="#000000"><font id="a13">
Email Address:*</font><br>
<font id="a21">
<input type="text"  name="email" size="40" maxlength="100"></font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td align="left" bgcolor="#000000" ALIGN="left"><font id="a13">Operating System:*</font><BR><font id="a22">
<select name="os" SIZE="1">
<option selected> Select One
<option> Windows 95
<option> Windows 98
<option> Windows NT
<option> Windows 2000
<option> Mac OS 9.0+
<option> Mac OS 8.0+
<option> Mac OS 7.6+
<option> Unix
<option> Linux
<option> Not sure
</select>
</font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td align="left" bgcolor="#000000" ALIGN="left"><font id="a13">Browser:*</font><BR><font id="a22">
<select name="browser" SIZE="1">
<option selected> Select One
<option> IE 5+
<option> IE 4+
<option> IE 3+
<option> Netscape 4.5+
<option> Netscape 4+
<option> Netscape 3+
<option> Other
</select>
</font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td align="left" bgcolor="#000000"><font id="a13">Player Version:*</font><BR><font id="a22">
<select name="player" SIZE="1">
<option selected> Select One
<option> RealPlayer 8
<option> RealPlayer 7
<option> RealPlayer G2
<option> RealPlayer 5
<option> Windows Media 7
<option> Windows Media 6
<option> Not Sure
</select>
</font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td align="left" bgcolor="#000000"><font id="a13">Connection Speed:*</font><BR><font id="a22">
<select name="connection" SIZE="1">
<option selected> Select One
<option> LAN
<option> Cable Modem
<option> ISDN/DSL
<option> 56k
<option> 33.6k
<option> 28.8k
<option> 14.4k
</select>
</font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td align="left" bgcolor="#000000"><font id="a13">Service Provider:*</font><BR><font id="a22">
<select name="provider" SIZE="1">
<option selected> Select One
<option> AOL
<option> Local ISP
<option> Network
<option> WebTV
<option> Free ISP
</select>
</font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td align="left" bgcolor="#000000"><font id="a13">
Regarding which station or program?*</font><br>
<font id="a21">
<input type="text" name="station" size="40"></font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td align="left" bgcolor="#000000" ALIGN="left"><font id="a13">
Questions or Comments:*</font><br>
<font id=a21>
<TEXTAREA  name="problem" rows="8" cols="40" wrap="hard"></TEXTAREA></font>
<br>&nbsp;<br></td><td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
<td align="center" bgcolor="#000000"><input type="Submit" value="Send Help Request Form">&nbsp;&nbsp;&nbsp;<!--<input type="RESET" value="Reset Application" id=RESET1 name=RESET1>--></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>
<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td><td align="left" bgcolor="#000000" ALIGN="left"><font id="a12">* These items are required.</font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="5"></td>
</tr>
</form>

<tr>
	<td ALIGN="Left" VALIGN="Top" COLSPAN="3" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
</tr>

<TR>
        <TD ALIGN="RIGHT" VALIGN="Top" COLSPAN="3" background="http://images.broadcastamerica.com/main/list_bot.gif"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></TD>
</TR>
</TABLE>
	


<!--END genre_list.tmpl-->
	</TD>
<!--END CENTER TD-->


<!--Begin RIGHT TD-->
	<TD ALIGN="Left" VALIGN="Top" WIDTH="140">
<!--Begin Right Nav Table BLACK-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="116" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%" HEIGHT="100%">

<!--begin main_ad_1r.phtml-->
<CENTER><A
HREF="http://ad.doubleclick.net/jump/ba.dart/msponsor;sz=88x31;ord=920995660127?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/msponsor;sz=88x31;ord=920995660127?" border=0 height="31" width="88"></A></CENTER><p>
<!--end main_ad_1r.phtml-->

<!--begin event.tmpl-->
<IMG SRC="http://images.broadcastamerica.com/main/t_events.gif" WIDTH="116" HEIGHT="28"><BR>
<IMG SRC="http://images.broadcastamerica.com/station_logos/music/superV_special.gif" WIDTH="116" HEIGHT="94"><BR>

<font id=a17>SUPER V</font><BR>
<font id=a16>Interactive Music TV<BR>
An EXCLUSIVE collaboration of Superadio and BroadcastAmerica<BR>
Coming soon!</font><P>

<font id=a17>Open House Party</font><BR>
<font id=a16>Live Broadcast<BR>
Saturdays<BR>
7pm est - Midnight</font><P>

<!--end event.tmpl-->

<!--begin new.tmpl-->
<IMG SRC="http://images.broadcastamerica.com/main/t_new.gif" WIDTH="116" HEIGHT="28" BORDER="0">

<font id=a31><BR>Clubs</font><BR>
<A HREF="http://Clubs.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Paul%20Oakenfold/bio?call=pauloak_bc"><font id=a17> Paul Oakenfold<BR>
</font></A><font id=a13>(World's #1 DJ)</font><P>

<font id=a31>Music</font><BR>
<A HREF="http://Music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/KRBI/bio?call=krbi_fm_bm"><font id=a17>KRBI</font></A><font id=a13> - 105.5 FM<BR>
Contemporary<BR>
St. Peter, MN</font><P>

<font id=a31>Sports</font><BR>
<A HREF="http://Sports.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WTAZ/bio?call=wtaz_am_bs"><font id=a17>WTAZ</font></A><font id=a13> - 1350 AM<BR>
Sports Talk/News<BR>
Peoria, IL</font><P>

<font id=a31>Talk</font><BR>
<A HREF="http://Talk.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WCGR/bio?call=wcgr_am_bt"><font id=a17>WCGR</font></A><font id=a13> - 1550 AM<BR>
News/Talk<BR>
Canandaigua, NY</font><P>

<font id=a31>TV News</font><BR>
<A HREF="http://Tvnews.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/KXD/bio?call=kkxd_tv"><font id=a17>KKXD</font></A><font id=a13> - CBS 13<BR>
Fairbanks, AK</font><P>





<!--end new.tmpl-->

</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
</TABLE>
<!--End Right Nav Table BLACK-->	

<!--BEGIN SPACER-->
<IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10">
<!--END SPACER-->

<!--begin main_ad_2r.phtml-->
<CENTER></CENTER>
<!--end main_ad_2r.phtml-->

<!--END RIGHT TD-->	
	
	
	</TD>
</TR>
</TABLE>	
	
<!--End Body Table	-->

<!--Begin Bottom Table	-->

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

<TR>
	<TD COLSPAN="2" ALIGN="Left" VALIGN="Top">
<!--begin navbar.phtml bottom-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_l.gif" WIDTH="13" HEIGHT="36"></TD>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_r.gif" WIDTH="13" HEIGHT="36"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Middle" WIDTH="739" HEIGHT="28">
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="220">
<FORM ACTION="http://search.broadcastamerica.com/results.phtml" METHOD="GET">
<TR><TD>
<font id="a12"><SELECT NAME="which">
<OPTION value=site>Search Channels</OPTION>
<OPTION value=web>Search Web</OPTION>
<OPTION value=music>Music</OPTION>
<OPTION value=sports>Sports</OPTION>
<OPTION value=clubs>Clubs</OPTION>
<OPTION value=talk>Talk</OPTION>
<OPTION value=tvnews>TV News</OPTION>
<OPTION value=movies>Movies</OPTION>
<OPTION value=urban>Urban</OPTION>
<OPTION value=bible>Christian</OPTION>
<OPTION value=comedy>Comedy</OPTION>
<OPTION value=wisdom>Wisdom</OPTION>
</SELECT></font>
</TD>
<TD><INPUT NAME="spec" TYPE=Text SIZE="8" MAXLENGTH="40"></TD><TD><INPUT NAME="FIND" TYPE=Submit VALUE="Find"></TD>
<TD ALIGN="Left" VALIGN="MIDDLE"><A HREF="http://www.goto.com/"><IMG SRC="http://images.broadcastamerica.com/main/goto_logo.gif" WIDTH="37" HEIGHT="23" BORDER="0"></A></TD></TR>
</FORM>
</TABLE>
</TD>

	<TD ALIGN="RIGHT" VALIGN="MIDDLE"><font id=a17><A HREF="../index.html">Home</A> | <A HREF="../mail/index.html">Free Voice/Fax/Email</A> | <A HREF="../news/index.html">World News</A> | <A HREF="../weather/scripts/index.html">Weather</A> | <A HREF="../customize/index.html">Customize</A> | <A HREF="index.html">Help</A></font></TD>
</TR>
</TABLE>

</TD>
</TR>
<TR>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="BOTTOM"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
</TR>
</TABLE>

<!--end navbar.phtml bottom-->
	</TD>
</TR>

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

<!--begin copyright.tmpl-->
<TR>
<TD COLSPAN="2" ALIGN="CENTER"><font id=a12>© Copyright 2000, BroadcastAmerica.com All rights reserved.<BR>
digiQue © Copyright 1999, BroadcastAmerica.com.</font></TD></TR>

<!--end copyright.tmpl-->

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

</TABLE>

<!--begin loc.phtml-->
<div ID="currentloc" STYLE="position:absolute; text-align:right; left:332; top:123; width:430; height:20; z-index:3; font-family:arial,helvetica; color:#FFFFFF; font-size:12px; clip:rect(0,430,16,0);">
<I><a href="../index.html">Home</a></I></div>

<!--end loc.phtml-->


</BODY>
</HTML>
