<HTML><HEAD>
<!--begin title.tmpl-->
<TITLE>BroadcastAMERICA.com</TITLE>
<!--end title.tmpl-->

<link rel=stylesheet href="/home/master.css" type="text/css">

<script language="Javascript">
<!--
function fbwindow() {
	var feedback = window.open('http://www.broadcastamerica.com/feedback/index.html','feedback','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,width=360,height=360');
	feedback.focus();
}
//-->
</script>

<script language="Javascript" src="../home/js/launch.js"></script>

<script LANGUAGE="javascript">
<!--
this.name="home"
//-->
</script>

<META NAME="KEYWORDS" CONTENT="Music, Sports,Talk, Television,News,BroadcastAmerica.com,Live,Radio,Movies,Clubs,BroadcastSports.com,BroadcastTVNews.com/BroadcastTalk.com,BroadcastClubs.com">
<META NAME="DESCRIPTION" CONTENT="BroadcastAmerica.com: the worlds largest streaming media company with over 600 exclusive live radio stations and thousands of On Demand streams">
<META HTTP-EQUIV="Refresh" CONTENT="300; URL=http://music.broadcastamerica.com/">

</HEAD>
<BODY BACKGROUND="http://images.broadcastamerica.com/main/bg.gif" TEXT="#FFFFFF" BGCOLOR="#333333" LINK="#FFFFFF" VLINK="#FFFFFF" ALINK="#FFFF99" TOPMARGIN="5" LEFTMARGIN="5" MARGINWIDTH="5" MARGINHEIGHT="5">

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
<!--begin logo.phtml-->
	<TD ALIGN="Left" VALIGN="Top" WIDTH="255"><a href="../index.html"><IMG SRC="http://images.broadcastamerica.com/main/ba_logo.gif" WIDTH="255" HEIGHT="81" BORDER="0" ALT="BroadcastAmerica.com"></a></TD>

<!--end logo.phtml-->
<!--begin main_ad_top.phtml-->
<TD ALIGN="CENTER" VALIGN="MIDDLE"><A HREF="http://ad.doubleclick.net/jump/ba.dart/bannertop;sz=468x60;ord=7633394128643?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/bannertop;sz=468x60;ord=7633394128643?" border=0 height="60" width="468"></A></TD>

<!--end main_ad_top.phtml-->
</TR>

<TR>
	<TD COLSPAN="2" ALIGN="Left" VALIGN="Top">
<!--begin navbar.phtml-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_l.gif" WIDTH="13" HEIGHT="36"></TD>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_r.gif" WIDTH="13" HEIGHT="36"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Middle" WIDTH="739" HEIGHT="28">
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="220">
<FORM ACTION="http://search.broadcastamerica.com/results.phtml" METHOD="GET">
<TR><TD>
<font id="a12"><SELECT NAME="which">
<OPTION value=site>Search Channels</OPTION>
<OPTION value=web>Search Web</OPTION>
<OPTION value=music>Music</OPTION>
<OPTION value=sports>Sports</OPTION>
<OPTION value=clubs>Clubs</OPTION>
<OPTION value=talk>Talk</OPTION>
<OPTION value=tvnews>TV News</OPTION>
<OPTION value=movies>Movies</OPTION>
<OPTION value=urban>Urban</OPTION>
<OPTION value=bible>Christian</OPTION>
<OPTION value=comedy>Comedy</OPTION>
<OPTION value=wisdom>Wisdom</OPTION>
</SELECT></font>
</TD>
<TD><INPUT NAME="spec" TYPE=Text SIZE="8" MAXLENGTH="40"></TD><TD><INPUT NAME="FIND" TYPE=Submit VALUE="Find"></TD>
<TD ALIGN="Left" VALIGN="MIDDLE"><A HREF="http://www.goto.com/"><IMG SRC="http://images.broadcastamerica.com/main/goto_logo.gif" WIDTH="37" HEIGHT="23" BORDER="0"></A></TD></TR>
</FORM>
</TABLE>
</TD>

	<TD ALIGN="RIGHT" VALIGN="MIDDLE"><font id=a17><A HREF="../index.html">Home</A> | <A HREF="../mail/index.html">Free Voice/Fax/Email</A> | <A HREF="../news/index.html">World News</A> | <A HREF="../weather/scripts/index.html">Weather</A> | <A HREF="../customize/index.html">Customize</A> | <A HREF="index.html">Help</A></font></TD>
</TR>
</TABLE>

</TD>
</TR>
<TR>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="BOTTOM"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
</TR>
</TABLE>

<!--end navbar.phtml-->
	</TD>
</TR>
</TABLE>
<!--End Top Table	-->


<!--Begin Body Table	-->

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
<!--Begin LEFT TD-->
	<TD ALIGN="Left" VALIGN="Top">
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="116" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="600"></TD>

	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" HEIGHT="100%">

<!--begin leftnav_loc.tmpl-->

<!--end leftnav_loc.tmpl-->

<!--begin main_ad_1l.phtml-->
<center><A HREF="http://ad.doubleclick.net/jump/ba.dart/stream;sz=116x58;ord=2149944314734?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/stream;sz=116x58;ord=2149944314734?" border=0 height="58" width="116"></A></center><P>


<!--end main_ad_1l.phtml-->
	
<!--begin leftnav_main.phtml-->
<IMG SRC="http://images.broadcastamerica.com/main/t_streamchan.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12><a HREF="http://music.broadcastamerica.com/">Music Radio</a><BR>
<a HREF="http://sports.broadcastamerica.com/">Sports Radio</a><BR>
<a HREF="http://talk.broadcastamerica.com/">Talk Radio</a><BR>
<a HREF="http://tvnews.broadcastamerica.com/">Local TV News</a><BR>
<a HREF="http://weather.broadcastamerica.com/">Weather</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://bible.broadcastamerica.com/">Christian Radio</a><BR>
<a HREF="http://urban.broadcastamerica.com/">Urban Music Radio</a><BR>
<a HREF="http://latino.broadcastamerica.com/">Latin Radio</a><BR>
<a HREF="http://www.broadcasteurope.com/">European Radio</a><BR>
<a HREF="http://movies.broadcastamerica.com/">Movies and More</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://comedy.broadcastamerica.com/">Comedy</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://clubs.broadcastamerica.com/">Club Music</a><BR>
<a HREF="http://kids.broadcastamerica.com/">Kid's Radio</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://inspiration.broadcastamerica.com/">Wisdom</a><BR></font><P>

<A HREF="http://ad.doubleclick.net/jump/ba.dart/siaudio;sz=116x58;ord=3229095819407?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/siaudio;sz=116x58;ord=3229095819407?" border=0 height="58" width="116"></A>

<IMG SRC="http://images.broadcastamerica.com/main/t_shopping.gif" WIDTH="116" HEIGHT="28" vspace="3"><BR>
<a href="http://service.bfast.com/bfast/click?bfmid=2181&sourceid=35523158&categoryid=rn_bestsellers"><font id=a46>Barnes & Noble</font></a><br>
<a href="http://service.bfast.com/bfast/click?bfmid=22282494&siteid=35522081&bfpage=homepage"><font id=a46>Gifts.com</font></a><br>
<a href="http://service.bfast.com/bfast/click?bfmid=70780&sourceid=35521430&categoryid=banners"><font id=a46>proflowers.com</font></a><br>
<font id=a12>
<a HREF="../channels/onlinepsychic/index.html">Psychic Readings</a><BR>
<a HREF="../channels/connection/index.html">Personals</a></font><P>

<IMG SRC="http://images.broadcastamerica.com/main/t_thecompany.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12>
<a HREF="../company/factsheet.phtml">Fact Sheet</a><BR>
<a HREF="../company/about.phtml">About Us</a><BR>
<a HREF="../company/chanover.phtml">Channel Overview</a><BR>
<a HREF="../company/bios.phtml">Officer Bios</a><BR>
<a HREF="../company/investor.phtml">Investor Info</a><BR>
<a HREF="../advertising/index.html">Advertising</a><BR>
<a HREF="../company/contact.phtml">Contact Info</a><BR>
<a HREF="../company/press.phtml">Press Releases</a><BR>
<a HREF="../company/inthenews.phtml">In the News</a><BR>
<a HREF="../jobs/index.html">Jobs @</a></font><P>

<IMG SRC="http://images.broadcastamerica.com/main/t_helpfaq.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12><a HREF="index.html">Help</a><BR>
<a HREF="index.phtml#rm">Real Media</a><BR>
<a HREF="index.phtml#wm">Windows Media</a><BR>
<a HREF="index.phtml#qf">Quick Fixes</a><BR>
<a HREF="station_finder.phtml">Station Finder</a><BR>
<A HREF="javascript:fbwindow()">Feedback</a><BR>
<a HREF="index.phtml#form">Write to us</a></font><P>

<CENTER><a HREF="http://www.real.com/products/player/downloadrealplayer.html?wp=dl0899&src=hp_butn" TARGET="_blank"><img SRC="http://images.broadcastamerica.com/main/freerealplayer7.gif" WIDTH="88" HEIGHT="32" VSPACE="5" BORDER="0"></a><BR>

<A HREF="http://www.microsoft.com/windows/mediaplayer/en/download/default.asp"><IMG SRC="http://images.broadcastamerica.com/main/wmedia.gif" WIDTH="89" HEIGHT="32" BORDER="0" vspace="5"></A></CENTER>

<!--end leftnav_main.phtml-->
</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Middle"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>

<TR>
	<TD COLSPAN="3">
<!--begin main_ad_2l.phtml-->
<CENTER><a href="http://www.promoclick.com"><IMG SRC="http://images.broadcastamerica.com/ads/proclk_100x70.gif" WIDTH="100" HEIGHT="70" border="0" alt="ad banner" VSPACE="5"></A></CENTER>
<!--end main_ad_2l.phtml-->
	</TD>
</TR>
</TABLE>	

</TD>
<!--End LEFT TD-->

<!--Begin CENTER AREA TD-->
	<TD ALIGN="CENTER" VALIGN="Top">
<TABLE WIDTH="484px" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="12" HEIGHT="5"></TD>

</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="12" HEIGHT="5"></TD>
	<TD ALIGN="Left" VALIGN="Top"><IMG SRC="http://images.broadcastamerica.com/main/t_help.gif" WIDTH="243" HEIGHT="53" BORDER="0"></TD>
	<TD ALIGN="Left" VALIGN="Top"><IMG SRC="http://images.broadcastamerica.com/main/rt_sub_spacer.gif" WIDTH="229" HEIGHT="60"></TD>
</TR>
</TABLE>	

<table WIDTH="460px" BORDER="0" CELLSPACING="0" CELLPADDING="5px">
<TR>
        <TD ALIGN="RIGHT" VALIGN="Top" COLSPAN="3" background="http://images.broadcastamerica.com/main/list_top.gif"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></TD>
</TR>

<TR>
<TD ALIGN="RIGHT" bgcolor="#000000" colspan="3"><font id=a19b><IMG SRC="http://images.broadcastamerica.com/help/sf_title_1.gif"></font></TD>
</TR>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
<TD ALIGN="center" bgcolor="003366"><font id=a17><a href="index.phtml#rm">Real Media</a> | <a href="index.phtml#wm">Windows Media</a> | <a href="index.phtml#qf">Quick Fixes</a> | <a href="index.phtml#form">Write to us</a> | <a href="station_finder.phtml">Station Finder</a></font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
</tr>

<TR>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
<TD ALIGN="left"><font id=a17>BroadcastAmerica.com </font><font id=a13>is dedicated to providing you with the best possible experience every time you visit our Web site.  That's why we've assembled all the finest resources to answer your questions.  However, if you need additional information, feel free to use the <a href="index.phtml#form">Help Request Form</a>.<br>
&nbsp;</font></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
<td bgcolor="#003366" ALIGN="left">
<p><font id=a19b>1: Search Field</font><br></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
<td>
<font id=a13>On BroadcastAmerica.com's home page you will find a "Pull Down" menu in the upper left-hand corner.  There are two selections that you can make to narrow your search.  The "Search Site" pull down lets you choose your desired venue (e.g. Music, Sports, and Talk).  Once you choose your content you can enter the call letters of the radio station (e.g. WABC) in the "Find" field and hit "Find" to search for the site.  If you don't know if it's Talk or Music radio, leave the "Search Site" field blank and put the call letters in the "Find" area.  The search will go through the complete listing of all stations currently available at BroadcastAmerica.com and give you a list of all the stations containing these call letters.  If a "Sorry, No Match" appears, the station hasn't yet joined the BroadcastAmerica.com family.</font><BR><CENTER><IMG SRC="http://images.broadcastamerica.com/help/search_bar.gif" ALT="" WIDTH="285" HEIGHT="200" BORDER="0" ALIGN="bottom"></CENTER></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
<td bgcolor="#003366" ALIGN="left">
<p><font id=a19b>2: "Left Side" Navigation Links</font><br></td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top"  bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
<td>
<font id=a13>On the left and right side of BroadcastAmerica.com's home page you will find a group of links designed to help you navigate the site.  These links separate the Music radio, Talk radio, etc., as well as allow you to choose different options pertaining to your specific lifestyle including news, shopping, and horoscopes, etc.
<P>When you choose one of the links in the "Streaming Channels" section, you are sent to a more specific page relating to your initial selection.  From here, you can use the "Left Side" links to choose from a variety of stations that will give you additional content for your chosen topic.
<P>When you select from the "Special Interest Audio" area, you are sent to a page that allows you to pick from a variety of audio clips, which pertain to your initial selection.
<P>The links in the "Shopping" section send you to a variety of shopping sites that will help you purchase that special something you have been looking for.</font><br>
&nbsp;</td>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top"  bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
<td bgcolor="#003366" ALIGN="left">
<p><font id=a19b>3: BroadcastAmerica.com "Home Page"</font><br></td>
<td ALIGN="Left" VALIGN="Top"  bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
</tr>

<tr>
<td ALIGN="Left" VALIGN="Top"  bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td><td ALIGN="left">
<font id=a13>BroadcastAmerica.com's home page provides an excellent vehicle for discovering new streaming media.  Here is where you can find new stations that have joined the streaming media era.  The links at the top of the page will bring you world news, weather, FREE voice and email.  A list of new stations in the lower right corner will let you listen to stations in different areas. <p>
 The "My Info Center" in the upper right hand corner can be customized to fit your listening interests, provide your area's weather, your horoscope and a report on world news.</font><br>
&nbsp;</font></TD>
<td ALIGN="Left" VALIGN="Top" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
</TR>

<tr>
	<td ALIGN="Left" VALIGN="Top" COLSPAN="3" bgcolor="#000000"><img SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></td>
</tr>
<TR>
        <TD ALIGN="RIGHT" VALIGN="Top" COLSPAN="3" background="http://images.broadcastamerica.com/main/list_bot.gif"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5px" HEIGHT="2px"></TD>
</TR>
</TABLE>
	


<!--END genre_list.tmpl-->
	</TD>
<!--END CENTER TD-->


<!--Begin RIGHT TD-->
	<TD ALIGN="Left" VALIGN="Top" WIDTH="140">
<!--Begin Right Nav Table BLACK-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="116" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%" HEIGHT="100%">

<!--begin main_ad_1r.phtml-->
<CENTER><A
HREF="http://ad.doubleclick.net/jump/ba.dart/msponsor;sz=88x31;ord=6274776533247?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/msponsor;sz=88x31;ord=6274776533247?" border=0 height="31" width="88"></A></CENTER><p>
<!--end main_ad_1r.phtml-->

<!--begin event.tmpl-->
<IMG SRC="http://images.broadcastamerica.com/main/t_events.gif" WIDTH="116" HEIGHT="28"><BR>
<IMG SRC="http://images.broadcastamerica.com/station_logos/music/superV_special.gif" WIDTH="116" HEIGHT="94"><BR>

<font id=a17>SUPER V</font><BR>
<font id=a16>Interactive Music TV<BR>
An EXCLUSIVE collaboration of Superadio and BroadcastAmerica<BR>
Coming soon!</font><P>

<font id=a17>Open House Party</font><BR>
<font id=a16>Live Broadcast<BR>
Saturdays<BR>
7pm est - Midnight</font><P>

<!--end event.tmpl-->

<!--begin new.tmpl-->
<IMG SRC="http://images.broadcastamerica.com/main/t_new.gif" WIDTH="116" HEIGHT="28" BORDER="0">

<font id=a31><BR>Clubs</font><BR>
<A HREF="http://Clubs.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Paul%20Oakenfold/bio?call=pauloak_bc"><font id=a17> Paul Oakenfold<BR>
</font></A><font id=a13>(World's #1 DJ)</font><P>

<font id=a31>Music</font><BR>
<A HREF="http://Music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/KRBI/bio?call=krbi_fm_bm"><font id=a17>KRBI</font></A><font id=a13> - 105.5 FM<BR>
Contemporary<BR>
St. Peter, MN</font><P>

<font id=a31>Sports</font><BR>
<A HREF="http://Sports.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WTAZ/bio?call=wtaz_am_bs"><font id=a17>WTAZ</font></A><font id=a13> - 1350 AM<BR>
Sports Talk/News<BR>
Peoria, IL</font><P>

<font id=a31>Talk</font><BR>
<A HREF="http://Talk.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WCGR/bio?call=wcgr_am_bt"><font id=a17>WCGR</font></A><font id=a13> - 1550 AM<BR>
News/Talk<BR>
Canandaigua, NY</font><P>

<font id=a31>TV News</font><BR>
<A HREF="http://Tvnews.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/KXD/bio?call=kkxd_tv"><font id=a17>KKXD</font></A><font id=a13> - CBS 13<BR>
Fairbanks, AK</font><P>





<!--end new.tmpl-->

</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
</TABLE>
<!--End Right Nav Table BLACK-->	

<!--BEGIN SPACER-->
<IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10">
<!--END SPACER-->

<!--begin main_ad_2r.phtml-->
<CENTER></CENTER>
<!--end main_ad_2r.phtml-->

<!--END RIGHT TD-->	
	
	
	</TD>
</TR>
</TABLE>	
	
<!--End Body Table	-->

<!--Begin Bottom Table	-->

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

<TR>
	<TD COLSPAN="2" ALIGN="Left" VALIGN="Top">
<!--begin navbar.phtml bottom-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_l.gif" WIDTH="13" HEIGHT="36"></TD>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_r.gif" WIDTH="13" HEIGHT="36"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Middle" WIDTH="739" HEIGHT="28">
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="220">
<FORM ACTION="http://search.broadcastamerica.com/results.phtml" METHOD="GET">
<TR><TD>
<font id="a12"><SELECT NAME="which">
<OPTION value=site>Search Channels</OPTION>
<OPTION value=web>Search Web</OPTION>
<OPTION value=music>Music</OPTION>
<OPTION value=sports>Sports</OPTION>
<OPTION value=clubs>Clubs</OPTION>
<OPTION value=talk>Talk</OPTION>
<OPTION value=tvnews>TV News</OPTION>
<OPTION value=movies>Movies</OPTION>
<OPTION value=urban>Urban</OPTION>
<OPTION value=bible>Christian</OPTION>
<OPTION value=comedy>Comedy</OPTION>
<OPTION value=wisdom>Wisdom</OPTION>
</SELECT></font>
</TD>
<TD><INPUT NAME="spec" TYPE=Text SIZE="8" MAXLENGTH="40"></TD><TD><INPUT NAME="FIND" TYPE=Submit VALUE="Find"></TD>
<TD ALIGN="Left" VALIGN="MIDDLE"><A HREF="http://www.goto.com/"><IMG SRC="http://images.broadcastamerica.com/main/goto_logo.gif" WIDTH="37" HEIGHT="23" BORDER="0"></A></TD></TR>
</FORM>
</TABLE>
</TD>

	<TD ALIGN="RIGHT" VALIGN="MIDDLE"><font id=a17><A HREF="../index.html">Home</A> | <A HREF="../mail/index.html">Free Voice/Fax/Email</A> | <A HREF="../news/index.html">World News</A> | <A HREF="../weather/scripts/index.html">Weather</A> | <A HREF="../customize/index.html">Customize</A> | <A HREF="index.html">Help</A></font></TD>
</TR>
</TABLE>

</TD>
</TR>
<TR>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="BOTTOM"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
</TR>
</TABLE>

<!--end navbar.phtml bottom-->
	</TD>
</TR>

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

<!--begin copyright.tmpl-->
<TR>
<TD COLSPAN="2" ALIGN="CENTER"><font id=a12>© Copyright 2000, BroadcastAmerica.com All rights reserved.<BR>
digiQue © Copyright 1999, BroadcastAmerica.com.</font></TD></TR>

<!--end copyright.tmpl-->

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

</TABLE>

<!--begin loc.phtml-->
<div ID="currentloc" STYLE="position:absolute; text-align:right; left:332; top:123; width:430; height:20; z-index:3; font-family:arial,helvetica; color:#FFFFFF; font-size:12px; clip:rect(0,430,16,0);">
<I><a href="../index.html">Home</a></I></div>

<!--end loc.phtml-->


</BODY>
</HTML>
