<CENTER><HTML><HEAD><TITLE>FloridaJobs.Com</TITLE></HEAD><BODY BGCOLOR="ffffff" Background="images/backgd3.gif" link=#e47833 vlink=#009999 alink=#ffffff><CENTER><IMG SRC="images/header.gif" alt="FloridaJobs.Com"></center><CENTER><IMG SRC="images/animation.gif" alt="FloridaJobs.Com"></center>

<IMG SRC="images/sub_search_jobs.gif" alt="Search Jobs"><BR>

<BLOCKQUOTE>



<CENTER><B><FONT FACE="helvetica, arial" SIZE="6">Keyword Search</FONT>



</B></CENTER>

</blockquote>
<CENTER><IMG SRC="images/hline.gif" alt="Horizontal Line"></center><BR>


<FONT FACE="helvetica, arial">


<FORM METHOD="POST" ACTION="/jobs-bin/AT-wwbellsearch.cgi">

<INPUT TYPE="hidden" NAME="sp" VALUE="sp">
<INPUT TYPE="hidden" NAME="source" VALUE="local">
<INPUT TYPE="hidden" NAME="mode" VALUE="concept">

<CENTER>

<TABLE CELLPADDING=5 CELLSPACING=5 BORDER=0 width="400">

  <TR>

    <TD WIDTH=400 ALIGN="center" VALIGN="TOP">

<TABLE>

	<TR>

		<TD colspan="2">

		<CENTER><FONT FACE="helvetica, arial" SIZE=3><B><U>Region</U></b><br><br>



<FONT SIZE="-1"><B>View the color coded map and select a <br>

specific region on the left to be searched. </B></FONT></font></center>



		</TD>

	</TR>

	<TR>

		<TD>

		<FONT FACE="helvetica, arial" SIZE=2>









<select name="region">

<option VALUE="">All of Florida, or

<option VALUE="1">1 - North West

<option VALUE="2">2 - North East

<option VALUE="3">3 - Central East

<option VALUE="4">4 - Central

<option VALUE="5">5 - Central West

<option VALUE="6">6 - South West

<option VALUE="7">7 - South East

</select>

</FONT>

		</TD>

		<TD>

		<CENTER><IMG SRC="images/florida_map.gif" width="235" height="177"></center>

		</TD>

	</TR>

</TABLE>



</center>

    </td>


  	<TR><TD VALIGN="TOP">



<CENTER><FONT FACE="helvetica, arial" SIZE=3><B><U>Job Age</U></b></font></center>



<BR>



<FONT FACE="helvetica, arial" SIZE=2>

<div align="center">

<B>Search for job postings that are no older than:</B>

</div><br>





<BLOCKQUOTE><BLOCKQUOTE><BLOCKQUOTE><BLOCKQUOTE>

<b><INPUT TYPE="radio" NAME="age" VALUE=5184000 CHECKED>60 Days

<br><INPUT TYPE="radio" NAME="age" VALUE=2592000 >30 Days

<br><INPUT TYPE="radio" NAME="age" VALUE=1209600 >14 Days

<br><INPUT TYPE="radio" NAME="age" VALUE=604800 > 7 Days</b>

</BLOCKQUOTE></BLOCKQUOTE></BLOCKQUOTE></BLOCKQUOTE>





</font>



    </td>



	</TR>
  </tr>

  <TR>

    <TD VALIGN="TOP">

<CENTER><FONT FACE="helvetica, arial" SIZE=3><B><U>Search By Keyword(s)</U></b></font></center>

<BR>



<FONT FACE="helvetica, arial" SIZE=2><B>Type in a keyword that you want an "Exact" match for. You can insert "Boolean" operators (AND, OR) to specify additional search information.<BR><U>Example:</U> accountant AND bank - rpg OR as400
</font>


<BR><FONT FACE="helvetica, arial" SIZE=2 color=#FF0000>
<B>Note: Do not use any symbols, ie: " " , ( ) in Keyword field.</B></b></font>



<BR>

<BR>

<CENTER>

<FONT FACE="helvetica, arial" SIZE=2><B>Keywords</B></font>

<BR>

<INPUT TYPE="TEXT" NAME="search" SIZE=50>


<TABLE BORDER=0>

<TR> <TD>





</font>
</TD> </TR>
</TABLE>
</center>

    </td>

  </tr>
</table>	<CENTER><BR>



<INPUT TYPE="SUBMIT" NAME=" " VALUE="Submit Search"><INPUT TYPE="RESET" NAME=" " VALUE="Clear"><BR>



<A HREF="http://www.excite.com/" TARGET="_top"><IMG SRC="http://www.floridajobs.com/Architext/pictures/AT-results_label.gif" BORDER=0></A>

</center>







</form>







</FONT><BR>

<CENTER><IMG SRC="images/hline.gif" alt="Horizontal Line"><BR>


<FONT FACE="helvetica, arial">

<CENTER>

<IMG SRC="images/footer.gif">

<BR>



<FONT SIZE=2>



<B><A HREF="mailto:admin@floridajobs.com">admin@floridajobs.com</a></B>
<BR>
<A HREF="../legal.html"><FONT SIZE="2">Terms and Conditions for this Web site</FONT></A><BR></center>

<BR>


</center>

</FONT>

</body>

</html>

















