--12:18:52--  http://www.chem.uoa.gr:80/
           => `www.chem.uoa.gr/index.html'
Connecting to www.chem.uoa.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 291 [text/html]

    0K ->                                                        [100%]

12:18:54 (284.18 KB/s) - `www.chem.uoa.gr/index.html' saved [291/291]

Converting www.chem.uoa.gr/index.html... done.

FINISHED --12:18:54--
Downloaded: 291 bytes in 1 files
