--14:18:41--  http://www.microsoft.com.gr:80/
           => `www.microsoft.com.gr/index.html'
Connecting to www.microsoft.com.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 419 [text/html]

    0K ->                                                        [100%]

14:18:42 (409.18 KB/s) - `www.microsoft.com.gr/index.html' saved [419/419]

Converting www.microsoft.com.gr/index.html... done.

FINISHED --14:18:42--
Downloaded: 419 bytes in 1 files
