<html>
<head>
<title>Briefme: Briefme Editors</title>
</head>
<body bgColor="#FFFFFF" text="#000000" link="#111111" vlink="#111111">
<table width="600" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td width="37" height="37" bgcolor="#ccff9a">&#160;&#160;</td>
	<td width="64" height="37" bgcolor="#006464">&#160;</td>
	<td width="50" height="37"><img src="../subimages/topcircle.jpg" width="50" height="37"></td>
	<td width="356" height="37" bgcolor="#006464">&#160;&#160;</td>
	<td width="93" height="37"><img src="../subimages/ladylean.jpg" width="93" height="37"></td>
</tr>
</table>
<table width="600" border="0" cellpadding="0" cellspacing="0">
<tr>
	<td width="37" height="29" bgcolor="#ccff9a">&#160;</td>
	<td width="125" height="29" bgcolor="#000000"><img src="../subimages/0.gif" width="127" height="29"></td>
	<td width="82" height="29" bgcolor="#000000"><a href="../subscribe/sub.cgi"><img src="../subimages/1.gif" border="0" width="82" height="29" name="subscribe"></a></td>
	<td width="94" height="29" bgcolor="#000000"><a href="../advertise/"><img src="../subimages/2.gif" border="0" width="94" height="29" name="advertise"></a></td>
	<td width="106" height="29" bgcolor="#000000"><a href="../editor/"><img src="../subimages/3.gif" border="0" width="112" height="29" name="editor"></a></td>
	<td width="90" height="29" bgcolor="#000000"><a href="../archive/"><img src="../subimages/4.gif" border="0" width="90" height="29" name="archives"></a></td>
	<td width="60" height="29" bgcolor="#000000"><a href="../"><img src="../subimages/5.gif" border="0" width="60" height="29" name="home"></a></td>
	</tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="600">
<tr>
	<td width="37" height="56" bgcolor="#ccff9a">&#160;</td>
	<td valign="top" width="117" height="56" bgcolor="#ccff9a"><img src="../subimages/buttomcircle.jpg" align="top" width="117" height="19"></td>
	<td width="446" height="56" bgcolor="#ccff9a"><img src="../editor/images/e_title.jpg" width="446" height="56"></td>
</tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="600">
<tr>
	<td valign="top" width="12" bgcolor="#ccff9a">&nbsp;</td>
	<td valign="top" width="150" bgcolor="#ccff9a" nowrap>&nbsp;</td>
	<td valign="top" width="438" bgcolor="#ccff9a">
	<table width="430" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td><font size="-1" face="arial, helvetica">
	<br>
	Click on the <b>e-zine topic</b> to view the list of editors.<p>
	<a href="./"><b>You can also be a BRIEFME editor!</b></a><p>
	<table cellspacing=1 cellpadding=1 border=0 width="100%">
	<tr bgColor="#000000">
		<td><font size=2 color="#FFFFFF"><b>Magazine Category</td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=001">Advertising & Marketing, Traditional</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=002">Advertising & Marketing, Web</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=003">Antiques & Collectibles</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=004">Art & Architecture</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=005">Arts & Crafts</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=006">Astrology, Psychic & Paranormal</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=007">Automotive</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=088">Beauty & Glamour</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=009">Boating & Sailing</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=010">Books & Literature</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=011">Bridal</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=013">Business News</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=084">Business: E-Commerce</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=012">Business: Small Business & Entrepreneurship</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=083">Computer Security & Privacy</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=016">Computer: Games</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=023">Computer: Mac</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=017">Computer: PC</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=015">Computer: Programming</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=021">Computer: Web & Internet</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=022">Computer: Webmaster</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=025">Consumer Electronics, Audio, Video</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=026">Contests & Sweepstakes</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=027">Education: College Life & Higher Ed</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=097">Education: Reference & Learning</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=029">Entertainment: Celebrity Scene</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=028">Entertainment: Movies</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=030">Entertainment: TV</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=031">Environment, Nature & Wildlife</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=032">Fashion & Style</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=096">Fishing & Hunting</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=070">Fitness & Nutrition</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=034">Food & Drink: Beer & Cocktails</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=033">Food & Drink: Cooking</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=099">Food & Drink: Wine</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=081">Free Stuff</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=085">Gambling & Casinos</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=035">Games, Toys & Hobbies</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=036">Gay & Lesbian</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=038">Home Improvement & Repair</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=039">Home, Garden & Decorating</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=040">Jokes & Humor</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=093">Kid Stuff</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=041">Law & Legal Issues</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=043">Medicine & Health</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=045">Money: Finance & Taxes</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=046">Money: Investing</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=048">Music: Classical & Opera</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=049">Music: Country & Folk</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=050">Music: Gospel & Christian</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=053">Music: Hip-Hop</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=051">Music: Jazz</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=087">Music: MP3 & Digital Music</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=052">Music: Rock & Pop</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=090">Music: Soul, Blues & R&B</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=056">Parenting & Family Life</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=092">Pets & Domestic Animals</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=094">Photography</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=057">Politics & Government</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=086">Relationships & Romance</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=061">Science & Technology</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=062">Science Fiction & Fantasy</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=063">Self-Help & Psychology</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=060">Senior Living</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=037">Shopping</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=091">Spirituality & Religion</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=095">Spirituality: New Age & Alternative</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=071">Sports, Extreme & Outdoor</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=100">Sports: Baseball</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=101">Sports: Basketball</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=102">Sports: Football</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=068">Sports: Golf</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=008">Sports: Motor Sports</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=077">Teen Scene</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=078">Telecommunications</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=080">Travel & Tourism</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=076">Women's Health</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=014">Workplace & Career</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=103">Wrestling, Boxing & Martial Arts</a></td>
	</tr>
	<tr bgColor="#EEEEEE">
		<td><font size=2><a href="masthead.phtml?id=098">Writing & Publishing</a></td>
	</tr>
	</table>
	<br>
		</td>
	</tr></table>
	</td>
</tr>
<tr>
	<td height="10" bgcolor="#000000">&#160;</td>
	<td height="10" bgcolor="#000000">&#160;</td>
	<td height="10" bgcolor="#000000">&#160;</td>
	<td height="10" bgcolor="#000000">&#160;</td>
</tr>
</table>
</body>
</html>

