<!-- WARNING!  DO NOT EDIT THIS FILE BY HAND OR USING AN HTML EDITOR! -->
<HTML>
<HEAD>
<TITLE>New Messages</TITLE>
<SCRIPT LANGUAGE="JavaScript">
<!-- ;
function setStatus(msg) {
  window.status = msg;
  return true;
}
function initpage () {
  window.defaultStatus = "New Messages"
  if (document.userpass) {
    if (document.userpass.username) {
      document.userpass.username.value = readcookie("user")
    }
    if (document.userpass.passwd) {
      document.userpass.passwd.value = readcookie("rpwd")
    }
  }
}
function readcookie(name) {
  var i = 0; var lookfor = name + "="
  while (i < document.cookie.length) {
    var j = i + lookfor.length
    if (document.cookie.substring(i,j) == lookfor) {
      var endstr = document.cookie.indexOf(";", j)
      if (endstr == -1) {
        endstr = document.cookie.length
      }
      return unescape(document.cookie.substring(j, endstr))
    }
    i = document.cookie.indexOf(" ", i) + 1
    if (i == 0) {
      break
    }
  }
  return ""
}
// end hide -->
</SCRIPT>
</HEAD>
<BODY BGCOLOR="#000033" TEXT="#ffffff" LINK="#99ffff" VLINK="#ff99ff" ALINK="#ff0000" BACKGROUND="" onLoad="initpage()">
<BASEFONT SIZE="2"><FONT FACE="Arial,Helvetica">
<A NAME="">
<a name=MT>

<CENTER><FONT SIZE=+1><B>New Messages</B></FONT></CENTER>
<HR>
<FORM ACTION="http://www.clanuk.org/cgi-bin/forum/board-newmessages.pl" METHOD=POST>
Search in&nbsp;<SELECT NAME="where" >
<OPTION VALUE="all">(All Topics)
<OPTION VALUE="11">About this service
<OPTION VALUE="1">Clan Chat
<OPTION VALUE="6">Action Chat
<OPTION VALUE="3">MMG Chat
<OPTION VALUE="4">RPG Chat
<OPTION VALUE="5">Strat Chat
<OPTION VALUE="5688">Reviews
<OPTION VALUE="5428">Online Security Issues
<OPTION VALUE="7">Help Desk

</SELECT> &nbsp;<INPUT TYPE=SUBMIT VALUE="Search">
<HR>
<BR>
<INPUT NAME="method" TYPE=radio VALUE="last" CHECKED>
Messages posted within the last&nbsp;
<INPUT NAME="number" VALUE="1" SIZE=3 onChange="document.forms[0].method[0].checked = true">
<SELECT NAME="units" onChange="document.forms[0].method[0].checked = true">
<OPTION VALUE="1">Minute(s)
<OPTION VALUE="60">Hour(s)
<OPTION VALUE="1440" SELECTED>Day(s)
</SELECT>
<P>
<INPUT NAME="method" TYPE=radio VALUE="check" onClick="document.forms[0].username.focus()" >
Messages since I last checked for new messages:<BR>
<UL><TABLE><TR><TD><FONT FACE="Arial,Helvetica" SIZE="2">Username:</FONT></TD><TD><INPUT TYPE=TEXT NAME=username  VALUE="" SIZE=9 onChange="document.forms[0].method[1].checked = true"></TD><TD><FONT FACE="Arial,Helvetica" SIZE="2">&nbsp;&nbsp;</FONT></TD></TR>
<TR><TD><FONT FACE="Arial,Helvetica" SIZE="2">Password:</FONT></TD><TD><INPUT TYPE=PASSWORD NAME=password SIZE=9 VALUE=""></TD><TD><FONT FACE="Arial,Helvetica" SIZE="2">&nbsp;&nbsp;<INPUT TYPE=CHECKBOX NAME=silent VALUE=on onClick="document.forms[0].method[1].checked = true">Don't remember this check</FONT></TD></TR></TABLE>
</UL>
<P>
<INPUT NAME="method" TYPE=radio VALUE="since" >
Messages posted after&nbsp;
<INPUT NAME="time" TYPE=text VALUE="12:01" SIZE=5 onChange="document.forms[0].method[2].checked = true">
<SELECT NAME="ampm" onChange="document.forms[0].method[2].checked = true"><OPTION VALUE="am" SELECTED>am<OPTION VALUE="pm">pm</SELECT>
<SELECT NAME="day" onChange="document.forms[0].method[2].checked = true">
<OPTION VALUE="-2">Today
<OPTION VALUE="-1">Yesterday
<OPTION VALUE="0">Thursday<OPTION VALUE="1">Wednesday<OPTION VALUE="2">Tuesday<OPTION VALUE="3">Monday<OPTION VALUE="4">Sunday<OPTION VALUE="5">Last Saturday
</SELECT>
<P>
<INPUT TYPE=CHECKBOX NAME=tree VALUE=1 CHECKED>
Display results in a message tree view
<BR>
<HR>
Most recent post: <B>Saturday, December 25, 1999 - 11:56 pm</B>
<!-- Discus 3.01.p1(NT)*PRO* %3253% !946166212!-->
</FORM>
</FONT>
<BR>
<BR>
</BODY>
</HTML>
