<!-- WARNING!  DO NOT EDIT THIS FILE BY HAND OR USING AN HTML EDITOR! -->
<HTML>
<HEAD>
<TITLE>Profile Editor</TITLE>
<SCRIPT LANGUAGE="JavaScript">
<!-- ;
function setStatus(msg) {
  window.status = msg;
  return true;
}
function initpage () {
  window.defaultStatus = ""
  if (document.userpass) {
    if (document.userpass.username) {
      document.userpass.username.value = readcookie("user")
    }
    if (document.userpass.passwd) {
      document.userpass.passwd.value = readcookie("rpwd")
    }
  }
}
function readcookie(name) {
  var i = 0; var lookfor = name + "="
  while (i < document.cookie.length) {
    var j = i + lookfor.length
    if (document.cookie.substring(i,j) == lookfor) {
      var endstr = document.cookie.indexOf(";", j)
      if (endstr == -1) {
        endstr = document.cookie.length
      }
      return unescape(document.cookie.substring(j, endstr))
    }
    i = document.cookie.indexOf(" ", i) + 1
    if (i == 0) {
      break
    }
  }
  return ""
}
// end hide -->
</SCRIPT>
</HEAD>
<BODY BGCOLOR="#000033" TEXT="#ffffff" LINK="#99ffff" VLINK="#ff99ff" ALINK="#ff0000" BACKGROUND="" onLoad="initpage()">
<BASEFONT SIZE="2"><FONT FACE="Arial,Helvetica">
<A NAME="">
<a name=MT>
<CENTER><FONT SIZE=+1><B>Profile Editor</B></FONT></CENTER><HR>
Enter your username and password below to edit your profile.<FORM ACTION="http://www.clanuk.org/cgi-bin/forum/board-profile.pl" METHOD=POST>
<TABLE><TR><TD><FONT FACE="Arial,Helvetica" SIZE=2><B>Username:</B></FONT></TD>
<TD><INPUT TYPE=TEXT NAME=username VALUE="" SIZE=15></TD></TR>
<TR><TD><FONT FACE="Arial,Helvetica" SIZE=2><B>Password:</B></FONT></TD>
<TD><INPUT TYPE=PASSWORD NAME=password VALUE="" SIZE=15></TD></TR>
</TABLE><P><INPUT TYPE=SUBMIT VALUE="Log In">
<INPUT TYPE=HIDDEN NAME=action VALUE=profile_editor_screen>
</FORM>
<FORM ACTION="http://www.clanuk.org/cgi-bin/forum/board-profile.pl" METHOD=POST>
<HR>If you do not currently have an account, but you wish to register for an account, you can do so by clicking the following button.<P>
<INPUT TYPE=SUBMIT VALUE="Instant Registration">
<INPUT TYPE=HIDDEN NAME=action VALUE=register>
</FORM>
</FONT>
<BR>
<BR>
</BODY>
</HTML>
