<!-- WARNING!  DO NOT EDIT THIS FILE BY HAND OR USING AN HTML EDITOR! -->
<HTML>
<HEAD>
<TITLE>Contact Moderators</TITLE>
<SCRIPT LANGUAGE="JavaScript">
<!-- ;
function setStatus(msg) {
  window.status = msg;
  return true;
}
function initpage () {
  window.defaultStatus = ""
  if (document.userpass) {
    if (document.userpass.username) {
      document.userpass.username.value = readcookie("user")
    }
    if (document.userpass.passwd) {
      document.userpass.passwd.value = readcookie("rpwd")
    }
  }
}
function readcookie(name) {
  var i = 0; var lookfor = name + "="
  while (i < document.cookie.length) {
    var j = i + lookfor.length
    if (document.cookie.substring(i,j) == lookfor) {
      var endstr = document.cookie.indexOf(";", j)
      if (endstr == -1) {
        endstr = document.cookie.length
      }
      return unescape(document.cookie.substring(j, endstr))
    }
    i = document.cookie.indexOf(" ", i) + 1
    if (i == 0) {
      break
    }
  }
  return ""
}
// end hide -->
</SCRIPT>
</HEAD>
<BODY BGCOLOR="#000033" TEXT="#ffffff" LINK="#99ffff" VLINK="#ff99ff" ALINK="#ff0000" BACKGROUND="" onLoad="initpage()">
<BASEFONT SIZE="2"><FONT FACE="Arial,Helvetica">
<A NAME="">
<a name=MT>
<CENTER><FONT SIZE=+1><B>Contact Moderators</B></FONT></CENTER>
<HR>
<P>Moderators:<P><UL>
<LI><A HREF="http://www.clanuk.org/cgi-bin/forum/board-profile.pl?action=display_profile&profile=admin-MODERATOR">Webmaster</A><LI><A HREF="http://www.clanuk.org/cgi-bin/forum/board-profile.pl?action=display_profile&profile=sheleph-MODERATOR">Sheleph</A><LI>Deputy Web Administrator</A></LI>
<LI><A HREF="http://www.clanuk.org/cgi-bin/forum/board-profile.pl?action=display_profile&profile=carnival-MODERATOR">Forum Administrator</A><LI><A HREF="http://www.clanuk.org/cgi-bin/forum/board-profile.pl?action=display_profile&profile=eod_god-MODERATOR">EOD God</A><LI><A HREF="http://www.clanuk.org/cgi-bin/forum/board-profile.pl?action=display_profile&profile=30ft_smurf-MODERATOR">+=30ft-Smurf=+</A><LI>Fumble</A></LI>
<LI><A HREF="http://www.clanuk.org/cgi-bin/forum/board-profile.pl?action=display_profile&profile=operator-MODERATOR">ClanUK operators</A></UL><P>
<P>Please address general questions and concerns to <A HREF="mailto:webmaster@clanuk.org">Webmaster</A>.<P>
<HR><CENTER><BR>
<A HREF="javascript:history.back()">Back to previous page</A>
</CENTER>
</FONT>
<BR>
<BR>
</BODY>
</HTML>
