--00:37:42--  http://www.canon.gr:80/
           => `www.canon.gr/index.html'
Connecting to www.canon.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 104 [text/html]

    0K ->                                                        [100%]

00:37:43 (101.56 KB/s) - `www.canon.gr/index.html' saved [104/104]

Converting www.canon.gr/index.html... done.

FINISHED --00:37:43--
Downloaded: 104 bytes in 1 files
