--15:56:56--  http://datacreta.datacreta.gr:80/
           => `datacreta.datacreta.gr/index.html'
Connecting to datacreta.datacreta.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 3,048 [text/html]

    0K -> ..                                                     [100%]

15:56:57 (10.30 KB/s) - `datacreta.datacreta.gr/index.html' saved [3048/3048]

Loading robots.txt; please ignore errors.
--15:56:57--  http://datacreta.datacreta.gr:80/no-robots.txt
           => `datacreta.datacreta.gr/no-robots.txt'
Connecting to datacreta.datacreta.gr:80... connected!
HTTP request sent, awaiting response... 404 Not Found
15:56:58 ERROR 404: Not Found.

--15:56:58--  http://datacreta.datacreta.gr:80/main.jpg
           => `datacreta.datacreta.gr/main.jpg'
Connecting to datacreta.datacreta.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 12,668 [image/jpeg]

    0K -> .......... ..                                          [100%]

15:56:59 (20.48 KB/s) - `datacreta.datacreta.gr/main.jpg' saved [12668/12668]

--15:56:59--  http://datacreta.datacreta.gr:80/U_index.html
           => `datacreta.datacreta.gr/U_index.html'
Connecting to datacreta.datacreta.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 2,576 [text/html]

    0K -> ..                                                     [100%]

15:56:59 (1.23 MB/s) - `datacreta.datacreta.gr/U_index.html' saved [2576/2576]

--15:56:59--  http://datacreta.datacreta.gr:80/pics/logo-DC.gif
           => `datacreta.datacreta.gr/pics/logo-DC.gif'
Connecting to datacreta.datacreta.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,627 [image/gif]

    0K -> ....                                                   [100%]

15:57:00 (17.12 KB/s) - `datacreta.datacreta.gr/pics/logo-DC.gif' saved [4627/4627]

--15:57:00--  http://datacreta.datacreta.gr:80/indexGR.html
           => `datacreta.datacreta.gr/indexGR.html'
Connecting to datacreta.datacreta.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 766 [text/html]

    0K ->                                                        [100%]

15:57:01 (748.05 KB/s) - `datacreta.datacreta.gr/indexGR.html' saved [766/766]

--15:57:01--  http://datacreta.datacreta.gr:80/pics/r-greek-sign.gif
           => `datacreta.datacreta.gr/pics/r-greek-sign.gif'
Connecting to datacreta.datacreta.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 979 [image/gif]

    0K ->                                                        [100%]

15:57:01 (956.05 KB/s) - `datacreta.datacreta.gr/pics/r-greek-sign.gif' saved [979/979]

--15:57:01--  http://datacreta.datacreta.gr:80/indexEN.html
           => `datacreta.datacreta.gr/indexEN.html'
Connecting to datacreta.datacreta.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 763 [text/html]

    0K ->                                                        [100%]

15:57:02 (745.12 KB/s) - `datacreta.datacreta.gr/indexEN.html' saved [763/763]

--15:57:02--  http://datacreta.datacreta.gr:80/pics/r-english-sign.gif
           => `datacreta.datacreta.gr/pics/r-english-sign.gif'
Connecting to datacreta.datacreta.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 226 [image/gif]

    0K ->                                                        [100%]

15:57:02 (220.70 KB/s) - `datacreta.datacreta.gr/pics/r-english-sign.gif' saved [226/226]

Converting datacreta.datacreta.gr/U_index.html... done.
Converting datacreta.datacreta.gr/index.html... done.

FINISHED --15:57:02--
Downloaded: 25,653 bytes in 8 files
Converting datacreta.datacreta.gr/index.html... done.
Converting datacreta.datacreta.gr/U_index.html... done.
Converting datacreta.datacreta.gr/indexGR.html... done.
Converting datacreta.datacreta.gr/indexEN.html... done.
