--13:28:22--  http://www.navy.gr:80/
           => `www.navy.gr/index.html'
Connecting to www.navy.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 5,297 [text/html]

    0K -> .....                                                  [100%]

13:28:24 (7.64 KB/s) - `www.navy.gr/index.html' saved [5297/5297]

Loading robots.txt; please ignore errors.
--13:28:24--  http://www.navy.gr:80/no-robots.txt
           => `www.navy.gr/no-robots.txt'
Connecting to www.navy.gr:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
13:28:25 ERROR 404: Object Not Found.

--13:28:25--  http://www.navy.gr:80/1.gif
           => `www.navy.gr/1.gif'
Connecting to www.navy.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 12,964 [image/gif]

    0K -> .......... ..                                          [100%]

13:28:28 (8.08 KB/s) - `www.navy.gr/1.gif' saved [12964/12964]

--13:28:32--  http://www.navy.gr:80/2.gif
           => `www.navy.gr/2.gif'
Connecting to www.navy.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 8,660 [image/gif]

    0K -> ........                                               [100%]

13:28:34 (6.08 KB/s) - `www.navy.gr/2.gif' saved [8660/8660]

Converting www.navy.gr/index.html... done.

FINISHED --13:28:39--
Downloaded: 26,921 bytes in 3 files
Converting www.navy.gr/index.html... done.
