--08:03:49--  http://www.amtel.sk:80/
           => `www.amtel.sk/index.html'
Connecting to www.amtel.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 3,934 [text/html]

    0K -> ...                                                    [100%]

08:03:49 (18.56 KB/s) - `www.amtel.sk/index.html' saved [3934/3934]

Converting www.amtel.sk/index.html... done.

FINISHED --08:03:49--
Downloaded: 3,934 bytes in 1 files
Converting www.amtel.sk/index.html... done.
