--02:31:32--  http://ww1.wavelord.gr:80/
           => `ww1.wavelord.gr/index.html'
Connecting to ww1.wavelord.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 514 [text/html]

    0K ->                                                        [100%]

02:31:34 (501.95 KB/s) - `ww1.wavelord.gr/index.html' saved [514/514]

Converting ww1.wavelord.gr/index.html... done.

FINISHED --02:31:34--
Downloaded: 514 bytes in 1 files
