--13:00:50--  http://www.trans.gr:80/
           => `www.trans.gr/index.html'
Connecting to www.trans.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 734 [text/html]

    0K ->                                                        [100%]

13:00:50 (716.80 KB/s) - `www.trans.gr/index.html' saved [734/734]

Loading robots.txt; please ignore errors.
--13:00:50--  http://www.trans.gr:80/no-robots.txt
           => `www.trans.gr/no-robots.txt'
Connecting to www.trans.gr:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
13:00:51 ERROR 404: Object Not Found.

--13:00:51--  http://www.trans.gr:80/fundzbr.jpg
           => `www.trans.gr/fundzbr.jpg'
Connecting to www.trans.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,077 [image/jpeg]

    0K -> ...                                                    [100%]

13:00:51 (34.03 KB/s) - `www.trans.gr/fundzbr.jpg' saved [4077/4077]

--13:00:51--  http://www.trans.gr:80/diabz_.gif
           => `www.trans.gr/diabz_.gif'
Connecting to www.trans.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 18,345 [image/gif]

    0K -> .......... .......                                     [100%]

13:00:51 (74.03 KB/s) - `www.trans.gr/diabz_.gif' saved [18345/18345]

--13:00:51--  http://www.trans.gr:80/riei.htm
           => `www.trans.gr/riei.htm'
Connecting to www.trans.gr:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
13:00:52 ERROR 404: Object Not Found.

Converting www.trans.gr/index.html... done.

FINISHED --13:00:52--
Downloaded: 23,156 bytes in 3 files
Converting www.trans.gr/index.html... done.
