--23:45:00--  http://www.suz.sk:80/
           => `www.suz.sk/index.html'
Connecting to www.suz.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 1,354 [text/html]

    0K -> .                                                      [100%]

23:45:01 (2.26 KB/s) - `www.suz.sk/index.html' saved [1354/1354]

Loading robots.txt; please ignore errors.
--23:45:01--  http://www.suz.sk:80/no-robots.txt
           => `www.suz.sk/no-robots.txt'
Connecting to www.suz.sk:80... connected!
HTTP request sent, awaiting response... 404 Not Found
23:45:02 ERROR 404: Not Found.

--23:45:02--  http://www.suz.sk:80/indexbak.htm
           => `www.suz.sk/indexbak.htm'
Connecting to www.suz.sk:80... connected!
HTTP request sent, awaiting response... 404 Not Found
23:45:02 ERROR 404: Not Found.

Converting www.suz.sk/index.html... done.

FINISHED --23:45:02--
Downloaded: 1,354 bytes in 1 files
Converting www.suz.sk/index.html... done.
