<HTML><HEAD>
<!--begin title.tmpl-->
<TITLE>BroadcastAMERICA.com</TITLE>
<!--end title.tmpl-->

<!--BROADCASTAMERICA.COM MAIN-->

<LINK rel=stylesheet href="master.css" type="text/css">

<SCRIPT language="Javascript">
<!--
function fbwindow() {
	var feedback = window.open('http://www.broadcastamerica.com/feedback/index.html','feedback','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,WIDTH=360,height=360');
	feedback.focus();
}
//-->
</SCRIPT>

<SCRIPT LANGUAGE="javascript">
        <!--
this.name="home"
        //-->
</SCRIPT>

<SCRIPT LANGUAGE="JavaScript">
<!-- Hide script from old browsers
var exp;
function reclama ()
{
	beenHere = getCookie('promopopup');

	if (beenHere != 1) 
	{
		exp = new Date(); 
		exp.setTime(exp.getTime() + (30*60*1000));
		document.cookie = "promopopup=1; domain=.broadcastamerica.com ; expires="+exp.toGMTString();
		var external=window.open('promo/promo.phtml',  'promo', 'width=250,height=250,left=225,top=100');
	}

}

function getCookie (name) {
	var arg = name + "=";
	var alen = arg.length;
	var clen = document.cookie.length;
	var i = 0;
	while (i < clen) {
		var j = i + alen;
		if (document.cookie.substring(i, j) == arg) {return getCookieVal (j);}
		i = document.cookie.indexOf(" ", i) + 1;
		if (i == 0) break; 
	}
	return null;
}

function getCookieVal (offset) {
	var endstr = document.cookie.indexOf (";", offset);
	if (endstr == -1) endstr = document.cookie.length;
	return unescape(document.cookie.substring(offset, endstr));
}
// End hiding script -->
</SCRIPT>


<SCRIPT language="Javascript">
<!--
var infocenter;
function infowindow() {
infocenter = window.open('f_infocenter.phtml','infocenter','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,WIDTH=140,height=400');
infocenter.focus();
}
//-->
</SCRIPT>
<STYLE>
<!--
#newstop { position:absolute; WIDTH:242px; height:29px; z-index:3; left:157; top:100; visibility: visible; }

#newsback { position:absolute; WIDTH:242px; height:280px; z-index:1; left:157; top:100; visibility: visible; background-color:#003366; layer-background-color:#003366;}

#newsbottom { position:absolute; WIDTH:242px; height:19px; z-index:3; left:157; top:385; visibility: visible; }

#title { font-family:arial,helvetica; color:#FFCC00; font-size:12pt; font-weight:bold;}

#text { font-family:arial,helvetica; color:#FFFFFF; font-size:10pt;}
//-->
</STYLE>

<SCRIPT language="VBScript" src="home/js/main.vbs"></SCRIPT>
<SCRIPT language="JavaScript" src="home/js/launchya.js"></SCRIPT>
<SCRIPT language="JavaScript" src="home/js/dynlayer.js"></SCRIPT>
<SCRIPT language="JavaScript" src="home/js/mouseevents.js"></SCRIPT>
<SCRIPT language="JavaScript" src="home/js/scroll2.js"></SCRIPT>
<SCRIPT language="JavaScript" src="home/js/resizefix.js"></SCRIPT>
<SCRIPT language="Javascript" src="home/js/launch.js"></SCRIPT>
<SCRIPT language="JavaScript" src="home/js/newsticker.js"></SCRIPT>

<SCRIPT language="JavaScript">

<!--
onload = init

function init() {

	myscroll.activate()
	initMouseEvents()
    ticker.activate();

}

var i0 = '<span class="tickerstyle"><A HREF="http://www.broadcastamerica.com/news/fullstory.cgi?page=ronsz&story=NEWS-ELECTION-LEADALL-DC" target=home>Gore Asks for Support in Contesting Florida Count</A></span>';
 var i1 = '<span class="tickerstyle"><A HREF="http://www.broadcastamerica.com/news/fullstory.cgi?page=ronsz&story=NEWS-ELECTION-NORTHWEST-DC" target=home>Washington State Starts Senate Recount</A></span>';
 var i2 = '<span class="tickerstyle"><A HREF="http://www.broadcastamerica.com/news/fullstory.cgi?page=ronsz&story=NEWS-COURT-MARIJUANA-DC" target=home>U.S. High Court to Decide Medical Marijuana Case</A></span>';
 var i3 = '<span class="tickerstyle"><A HREF="http://www.broadcastamerica.com/news/fullstory.cgi?page=ronsz&story=NEWS-ELECTION-COURT-DC" target=home>Democrats Mount Legal Challenge to Bush Victory</A></span>';
 var i4 = '<span class="tickerstyle"><A HREF="http://www.broadcastamerica.com/news/fullstory.cgi?page=ronsz&story=NEWS-COURT-EXECUTION-DC" target=home>Case of Texas Death-Row Inmate Goes to Supreme Court</A></span>';
 var i5 = '<span class="tickerstyle"><A HREF="http://www.broadcastamerica.com/news/fullstory.cgi?page=ronsz&story=NEWS-TELEVISION-COURT-DC" target=home>US High Court Won\'t Allow TV Cover of Election Case</A></span>';
 var i6 = '<span class="tickerstyle"><A HREF="news/fullstory.cgi?page=ronsz&story=NEWS-MICROSOFT-APPEAL-DC" target=home>Microsoft Tells Court It Acted Legally</A></span>';
 var i7 = '<span class="tickerstyle"><A HREF="news/fullstory.cgi?page=ronsz&story=NEWS-CANADA-ELECTION-DC" target=home>Canada\'s Liberals Head for Third Majority</A></span>';
 var i8 = '<span class="tickerstyle"><A HREF="news/fullstory.cgi?page=ronsz&story=NEWS-HAITI-ELECTION-DC" target=home>Haiti\'s Aristide Emerges After Likely Election Win</A></span>';
 var i9 = '<span class="tickerstyle"><A HREF="news/fullstory.cgi?page=ronsz&story=NEWS-CRIME-FUGITIVE-DC" target=home>Fugitive in 1983 Bank Robbery Case Surrenders</A></span>';

var i8 = '<span class="tickerstyle"><b><A HREF="http://www.broadcastamerica.com/company/press_090700.phtml">BroadcastAmerica Expands Content </A></b></Span>';

ticker = new NewsTicker(640,188,120,40);
ticker.addItem(i0);
ticker.addItem(i1);
ticker.addItem(i2);
ticker.addItem(i3);
ticker.addItem(i4);
ticker.addItem(i5);
ticker.addItem(i6);
ticker.addItem(i7);
ticker.addItem(i8);
ticker.build();



writeCSS(
ticker.css 
)

myscroll = new Scroll(157,180,230,205)
myscroll.useH = false
myscroll.imgSet('http://images.broadcastamerica.com/scrollbars/bamerica/',14,11,17,-1,2,-1,2,1,1)

myscroll.drawBorder = false
myscroll.build()
writeCSS ( myscroll.css )

//-->

</SCRIPT>

<STYLE type="text/css">

<!--
.tickerstyle {font-family:arial,helvetica; font-size:10px; color:#FFFFFF;}
//-->
</STYLE>

<META NAME="KEYWORDS" CONTENT="Music, Sports,Talk, Television,News,BroadcastAmerica.com,Live,Radio,Movies,Clubs,BroadcastMusic.com,BroadcastSports.com,BroadcastTVNews.com/BroadcastTalk.com,BroadcastClubs.com">
<META NAME="DESCRIPTION" CONTENT="BroadcastAmerica.com: the worlds largest streaming media company with over 500 exclusive live radio stations">
<META HTTP-EQUIV="Refresh" CONTENT="900; URL=index.html">
</HEAD>
<BODY BACKGROUND="http://images.broadcastamerica.com/main/bg.gif" TEXT="#FFFFFF" BGCOLOR="#333333" LINK="#FFFFFF" VLINK="#FFFFFF" ALINK="#FFFF99" TOPMARGIN="5px" LEFTMARGIN="5px" MARGINWIDTH="5px" MARGINHEIGHT="5px" onload="init();reclama();">

<SCRIPT language="JavaScript">
<!--
document.write(ticker.div);
//-->
</SCRIPT>

<!--BEGIN Top TABLE-->
<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
<!--begin logo.tmpl-->
	<TD ALIGN="Left" VALIGN="Top" WIDTH="255"><a href="index.html"><IMG SRC="http://images.broadcastamerica.com/main/ba_logo.gif" WIDTH="255" HEIGHT="81" BORDER="0" ALT="BroadcastAmerica.com"></a></TD>

<!--end logo.tmpl-->
<!--begin ad_top.phtml-->
<TD ALIGN="CENTER" VALIGN="MIDDLE"><A HREF="http://ad.doubleclick.net/jump/ba.dart/bannertop;sz=468x60;ord=2711454224773?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/bannertop;sz=468x60;ord=2711454224773?" border=0 height="60" width="468"></A></TD>

<!--end ad_top.phtml-->
</TR>

<TR>
	<TD COLSPAN="2" ALIGN="Left" VALIGN="Top">
<!--begin navbar.phtml-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_l.gif" WIDTH="13" HEIGHT="36"></TD>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_r.gif" WIDTH="13" HEIGHT="36"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Middle" WIDTH="739" HEIGHT="28">
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="220">
<FORM ACTION="http://search.broadcastamerica.com/results.phtml" METHOD="GET">
<TR><TD>
<font id="a12"><SELECT NAME="which">
<OPTION value=site>Search Channels</OPTION>
<OPTION value=web>Search Web</OPTION>
<OPTION value=music>Music</OPTION>
<OPTION value=sports>Sports</OPTION>
<OPTION value=clubs>Clubs</OPTION>
<OPTION value=talk>Talk</OPTION>
<OPTION value=tvnews>TV News</OPTION>
<OPTION value=movies>Movies</OPTION>
<OPTION value=urban>Urban</OPTION>
<OPTION value=bible>Christian</OPTION>
<OPTION value=comedy>Comedy</OPTION>
<OPTION value=wisdom>Wisdom</OPTION>
</SELECT></font>
</TD>
<TD><INPUT NAME="spec" TYPE=Text SIZE="8" MAXLENGTH="40"></TD><TD><INPUT NAME="FIND" TYPE=Submit VALUE="Find"></TD>
<TD ALIGN="Left" VALIGN="MIDDLE"><A HREF="http://www.goto.com/"><IMG SRC="http://images.broadcastamerica.com/main/goto_logo.gif" WIDTH="37" HEIGHT="23" BORDER="0"></A></TD></TR>
</FORM>
</TABLE>
</TD>

	<TD ALIGN="RIGHT" VALIGN="MIDDLE"><font id=a17><A HREF="index.html">Home</A> | <A HREF="mail/index.html">Free Voice/Fax/Email</A> | <A HREF="news/index.html">World News</A> | <A HREF="weather/scripts/index.html">Weather</A> | <A HREF="customize/index.html">Customize</A> | <A HREF="help/index.html">Help</A></font></TD>
</TR>
</TABLE>

</TD>
</TR>
<TR>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="BOTTOM"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
</TR>
</TABLE>

<!--end navbar.phtml-->
	</TD>
</TR>
</TABLE>
<!--End Top TABLE	-->

<!--Begin Body TABLE	-->
<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
<!--Begin LEFT TD-->
	<TD ALIGN="Left" VALIGN="Top">
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="116" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="600"></TD>

	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" HEIGHT="100%">

<!--begin leftnav_loc.tmpl-->

<!--end leftnav_loc.tmpl-->

<!--begin main_ad_1l.phtml-->
<center><A HREF="http://ad.doubleclick.net/jump/ba.dart/stream;sz=116x58;ord=9478540839628?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/stream;sz=116x58;ord=9478540839628?" border=0 height="58" width="116"></A></center><P>


<!--end main_ad_1l.phtml-->
	
<!--begin leftnav_main.phtml-->
<IMG SRC="http://images.broadcastamerica.com/main/t_streamchan.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12><a HREF="http://music.broadcastamerica.com/">Music Radio</a><BR>
<a HREF="http://sports.broadcastamerica.com/">Sports Radio</a><BR>
<a HREF="http://talk.broadcastamerica.com/">Talk Radio</a><BR>
<a HREF="http://tvnews.broadcastamerica.com/">Local TV News</a><BR>
<a HREF="http://weather.broadcastamerica.com/">Weather</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://bible.broadcastamerica.com/">Christian Radio</a><BR>
<a HREF="http://urban.broadcastamerica.com/">Urban Music Radio</a><BR>
<a HREF="http://latino.broadcastamerica.com/">Latin Radio</a><BR>
<a HREF="http://www.broadcasteurope.com/">European Radio</a><BR>
<a HREF="http://movies.broadcastamerica.com/">Movies and More</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://comedy.broadcastamerica.com/">Comedy</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://clubs.broadcastamerica.com/">Club Music</a><BR>
<a HREF="http://kids.broadcastamerica.com/">Kid's Radio</a><IMG SRC="http://images.broadcastamerica.com/main/s_new.gif" align="absmiddle"><BR>
<a HREF="http://inspiration.broadcastamerica.com/">Wisdom</a><BR></font><P>

<A HREF="http://ad.doubleclick.net/jump/ba.dart/siaudio;sz=116x58;ord=7560065849685?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/siaudio;sz=116x58;ord=7560065849685?" border=0 height="58" width="116"></A>

<IMG SRC="http://images.broadcastamerica.com/main/t_shopping.gif" WIDTH="116" HEIGHT="28" vspace="3"><BR>
<a href="http://service.bfast.com/bfast/click?bfmid=2181&sourceid=35523158&categoryid=rn_bestsellers"><font id=a46>Barnes & Noble</font></a><br>
<a href="http://service.bfast.com/bfast/click?bfmid=22282494&siteid=35522081&bfpage=homepage"><font id=a46>Gifts.com</font></a><br>
<a href="http://service.bfast.com/bfast/click?bfmid=70780&sourceid=35521430&categoryid=banners"><font id=a46>proflowers.com</font></a><br>
<font id=a12>
<a HREF="channels/onlinepsychic/index.html">Psychic Readings</a><BR>
<a HREF="channels/connection/index.html">Personals</a></font><P>

<IMG SRC="http://images.broadcastamerica.com/main/t_thecompany.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12>
<a HREF="company/factsheet.phtml">Fact Sheet</a><BR>
<a HREF="company/about.phtml">About Us</a><BR>
<a HREF="company/chanover.phtml">Channel Overview</a><BR>
<a HREF="company/bios.phtml">Officer Bios</a><BR>
<a HREF="company/investor.phtml">Investor Info</a><BR>
<a HREF="advertising/index.html">Advertising</a><BR>
<a HREF="company/contact.phtml">Contact Info</a><BR>
<a HREF="company/press.phtml">Press Releases</a><BR>
<a HREF="company/inthenews.phtml">In the News</a><BR>
<a HREF="jobs/index.html">Jobs @</a></font><P>

<IMG SRC="http://images.broadcastamerica.com/main/t_helpfaq.gif" WIDTH="116" HEIGHT="28"><BR>
<font id=a12><a HREF="help/index.html">Help</a><BR>
<a HREF="help/index.phtml#rm">Real Media</a><BR>
<a HREF="help/index.phtml#wm">Windows Media</a><BR>
<a HREF="help/index.phtml#qf">Quick Fixes</a><BR>
<a HREF="help/station_finder.phtml">Station Finder</a><BR>
<A HREF="javascript:fbwindow()">Feedback</a><BR>
<a HREF="help/index.phtml#form">Write to us</a></font><P>

<CENTER><a HREF="http://www.real.com/products/player/downloadrealplayer.html?wp=dl0899&src=hp_butn" TARGET="_blank"><img SRC="http://images.broadcastamerica.com/main/freerealplayer7.gif" WIDTH="88" HEIGHT="32" VSPACE="5" BORDER="0"></a><BR>

<A HREF="http://www.microsoft.com/windows/mediaplayer/en/download/default.asp"><IMG SRC="http://images.broadcastamerica.com/main/wmedia.gif" WIDTH="89" HEIGHT="32" BORDER="0" vspace="5"></A></CENTER>

<!--end leftnav_main.phtml-->
</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Middle"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>

<TR>
	<TD COLSPAN="3">
<!--begin main_ad_2l.phtml-->
<CENTER><a href="http://www.promoclick.com"><IMG SRC="http://images.broadcastamerica.com/ads/proclk_100x70.gif" WIDTH="100" HEIGHT="70" border="0" alt="ad banner" VSPACE="5"></A></CENTER>
 to be or not to be..&nbsp;
<p>-kryptek<!--end main_ad_2l.phtml-->
</p>
	</TD>
</TR>

</TABLE>	

</TD>
<!--END LEFT TD-->

<!--Begin CENTER AREA TD-->
	<TD ALIGN="Left" VALIGN="Top">
<!--Begin LIVE DISH AND LOOP TABLE-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ALIGN="Left" VALIGN="Top" Rowspan="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="12" HEIGHT="5"></TD>
	<TD ALIGN="Left" VALIGN="Top"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="5"></TD>
	<TD ALIGN="Left" VALIGN="Top" Rowspan="3">
<!--BEGIN TOP PICKS TABLE-->

<!--begin toppicks.tmpl-->
<TABLE Width="208" BORDER="0" CELLSPACING="0" CELLPADDING="2">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>

<TR>
	<TD ALIGN="Left" VALIGN="Top" ROWSPAN="11"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="2" HEIGHT="10"></TD>
	<TD><IMG SRC="http://images.broadcastamerica.com/main/t_toppics.gif" WIDTH="204" HEIGHT="23"></TD>
</TR>

<TR>
	<TD><IMG SRC="http://images.broadcastamerica.com/main/toppick_bullet.gif" WIDTH="12" HEIGHT="30" ALIGN="LEFT"><A HREF="http://music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WZUU/Bio?call=wzuu_fm_bm"><font id=a17>WZUU 92.3 FM</font></A><font id=a13></font><BR>
<font id=a13> Classic Rock</font></TD>
</TR>
<TR>
	<TD><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="202" HEIGHT="2"></TD>
</TR>

<TR>
	<TD><IMG SRC="http://images.broadcastamerica.com/main/toppick_bullet.gif" WIDTH="12" HEIGHT="30" ALIGN="LEFT"><A HREF="http://Sports.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Mad%20Dog%20Sports/bio?call=mdog_bs"><font id=a17>Mad Dog Sports</A></font><BR>
<font id=a13>
Sports Talk</font></TD>
</TR>
<TR>
	<TD><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="202" HEIGHT="2"></TD>
</TR>

<TR>
	<TD><IMG SRC="http://images.broadcastamerica.com/main/toppick_bullet.gif" WIDTH="12" HEIGHT="30" ALIGN="LEFT"><A HREF="http://Talk.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Erskine%20Overnight/bio?call=ts07010"><font id=a17> Erskine Overnight
</font><font id=a13></font></A><BR>
<font id=a13>Talk Radio</font></TD>
</TR>

<TR>
	<TD><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="202" HEIGHT="2"></TD>
</TR>

<TR>
	<TD><IMG SRC="http://images.broadcastamerica.com/main/toppick_bullet.gif" WIDTH="12" HEIGHT="30" ALIGN="LEFT"><A HREF="http://Tvnews.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/NASA%20TV/bio?call=nasa001"><font id=a17>NASA TV
</font><font id=a13></font></A><BR>
<font id=a13>24hr NASA News</font></TD>
</TR>

<TR>
	<TD><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="202" HEIGHT="2"></TD>
</TR>

<TR>
	<TD><IMG SRC="http://images.broadcastamerica.com/main/toppick_bullet.gif" WIDTH="12" HEIGHT="30" ALIGN="LEFT"><A HREF="http://music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Jazz%20Trax/Bio?call=spr023"><font id=a17>Jazz Trax </font><BR>
<font id=a13>Jazz Radio</A></font></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"><IMG SRC="http://images.broadcastamerica.com/main/t_toppics_bot.gif" WIDTH="204" HEIGHT="15"></TD>
</TR>

<!--BEGIN TEXT AD-->
<!--SM SHUT DOWN THIS TEXT AD - PLEASE SEE ME BEFORE TURNING BACK ON-->
<!--<TR>
	<TD ALIGN="Left" VALIGN="Top"><A HREF="http://ad.doubleclick.net/jump/ba.dart/text1;sz=204x42;ord=7093059793115?"><IMG SRC="http://ad.doubleclick.net/ad/ba.dart/text1;sz=204x42;ord=7093059793115?" WIDTH="204" HEIGHT="42" BORDER="0"></A></TD>
</TR>-->
<!--SM SHUT DOWN THIS TEXT AD - PLEASE SEE ME BEFORE TURNING BACK ON-->
<!--END TEXT AD-->

</TABLE Width="208">

<!--end toppicks.tmpl-->

<!--END TOP PICKS TABLE-->		
	</TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top">
<!--begin sub_title.tmpl-->
	<IMG SRC="http://images.broadcastamerica.com/main/t_main.gif" WIDTH="243" HEIGHT="53">
<!--end sub_title.tmpl-->	
	</TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="228"></TD>
</TR>

</TABLE>	
<!--End LIVE DISH AND LOOP TABLE-->


<!--Begin NEWS TABLE-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="468">
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%" HEIGHT="100%">

<!--BEGIN NEWS-->	
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="444">
<TR>
	<TD ALIGN="Left" VALIGN="Top" Colspan="2"><IMG SRC="http://images.broadcastamerica.com/main/t_topstories_news.gif" WIDTH="436" HEIGHT="23" BORDER="0"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" Colspan="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="436" HEIGHT="10" BORDER="0"></TD>
</TR>
<!--BEGIN Top Story-->	
<TR>
 	<TD ALIGN="Left" VALIGN="Top"><a href="home/news/fullstory.cgi?page=ronsz&amp;story=NEWS-ELECTION-LEADALL-DC"><img align="right" width="200" hspace="5" border="0" src="mdf134099.jpg" /></a></TD>
 	<TD ALIGN="Left" VALIGN="Top">
 <P>
 
 <font size="4" color="#00FFFF">George Bush arrested in Florida in drunken car
 chase!</font><P>
 
 <font id=a13>WASHINGTON (kryptek) - Casting himself as a defender of democracy and the Constitution,
 George W. Bush Was arrested today by the Miami police department for
 speeding.&nbsp; When pulled over, Bush was found drunk and was carrying a set
 of 9mm Glocks.<P>
 
 <A HREF="home/news/fullstory.cgi?page=ronsz&story=NEWS-ELECTION-LEADALL-DC">Full Story</A><BR>
 
 <A HREF="home/news/summaries.cgi?page=ronsz">In Other News...</A></font></TD>
 </TR>
<!--end Top Story-->

<!--spacer-->
<TR>
	<TD ALIGN="Left" VALIGN="Top" Colspan="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="5" HEIGHT="10"></TD>
</TR>
<!--end spacer-->
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="2">

<!--BEGIN NEWS SOUND BYTES TABLE-->

		
<!--BEGIN NEWS SOUND BYTES TABLE-->

	</TD>
</TR>
</TABLE>		
<!--END News-->	
	</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
</TABLE>

<!--End NEWS Area-->
<TABLE>
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="2">
<!--Begin QUAD TABLE Body Area-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="468">
<TR>
	<TD ALIGN="Left" VALIGN="Top" WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top">

<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="5">
<!--BEGIN ROW SPACER-->
<!--begin press_lead.tmpl-->
<TR>
<TD ALIGN="Left" VALIGN="Top"><IMG SRC="http://images.broadcastamerica.com/main/t_thebuzz.gif" WIDTH="162" HEIGHT="36"><P>
<font id=a19>BroadcastAmerica to Combine with SurferNETWORK.com</font><BR>
<font id=a17>New Company Will Bring Together World's Largest Online Broadcaster with Streaming / Ad Insertion Technology Leader to Provide Superior Online Listening and Targeted Multimedia Advertising<br></font><P>
<IMG SRC="http://images.broadcastamerica.com/pressreleases/p_110800_sm.gif" WIDTH="150" HEIGHT="90" HSPACE="5" ALIGN="Right" BORDER="0" ALT="">
<font id=a13>For more information about the BroadcastAmerica and SurferNETWORK combination, please email <a href="mailto:communications@broadcastamerica.com">communications@broadcastamerica.com</a>.<P></font></TR>
<tr><td><P><A HREF="company/press.phtml?108"><font id=a17>Full Story</font></A><P></td></tr><P><TR>
<TD ALIGN="Left" VALIGN="Top">
<font id=a19>BroadcastAmerica and Hockey Star Mark Messier Launch </font><BR>
<font id=a17>Online Charity Program to Auction off Extremely Rare Messier Memorabilia to Benefit Tomorrows Children's Fund<br></font><P>
<IMG SRC="http://images.broadcastamerica.com/pressreleases/p_092000_sm.jpg" WIDTH="150" HEIGHT="90" HSPACE="5" ALIGN="Right" BORDER="0" ALT="">
<font id=a13><p>NEW YORK (September 20, 2000)– BroadcastAmerica announced last night in a media conference at Madison Square Garden that it has launched a charitable program called Bids for Kids with future hockey Hall of Famer and New York Rangers Captain Mark Messier. Messier, who led the New York Rangers to a Stanley Cup in 1994 after a 54-year drought, recently returned to the Rangers after three years with the Vancouver Canucks.<P>
</font>
</TR>
<tr><td><A HREF="company/press.phtml?104"><font id=a17>Full Story</font></A><P></td></tr>
<!--end press_lead.tmpl-->

</TABLE>
	
	</TD>
</TR>
</TABLE>
<!--End QUAD TABLE Body Area-->
	</TD>
</TR>

</TABLE>	
	</TD>
<!--END CENTER AREA TD-->	

<!--Begin RIGHT TD-->
	<TD ALIGN="Left" VALIGN="Top" WIDTH="140">
<!--BEGIN INFOCENTER-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<!--BEGIN SPACER-->
<TR>
	<TD COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="12" HEIGHT="18"></TD>
</TR>
<!--END SPACER-->
<TR>
	<TD COLSPAN="3"><IMG SRC="http://images.broadcastamerica.com/infocenter/info_top.gif" WIDTH="140" HEIGHT="31"></TD>
</TR>
<TR>
	<TD ROWSPAN="10"><IMG SRC="http://images.broadcastamerica.com/infocenter/bg_l.gif" WIDTH="6" HEIGHT="297"></TD>
	<TD BGCOLOR="#000033" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/infocenter/t_wnews.gif" WIDTH="128" HEIGHT="13"></TD>
	<TD ROWSPAN="10"><IMG SRC="http://images.broadcastamerica.com/infocenter/bg_r.gif" WIDTH="6" HEIGHT="297"></TD>
</TR>

<!--BEGIN WORLD NEWS-->
<TR>
	<TD BGCOLOR="#000033">
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="3px" WIDTH="100%">
<TR>
<TD align=left valign=top bgcolor=#000033><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="40" HEIGHT="34"></TD>
</TR>
</TABLE>
	</TD>
</TR>
<!--END WORLD NEWS-->
<TR>
	<TD BGCOLOR="#330033" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/infocenter/t_weather.gif" WIDTH="128" HEIGHT="13"></TD>
</TR>

<!--BEGIN WEATHER-->
<TR>
	<TD BGCOLOR="#330033">

<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="3" WIDTH="100%">
<tr><td align=center valign=top bgcolor=#330033><p><font id=a12 color=white><a href=weather/scripts/index.html target=home>Your Local Weather</a></font></td></tr>
</TABLE>

	</TD>
</TR>
<!--END WEATHER-->
<TR>
	<TD BGCOLOR="#000033" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/infocenter/t_email.gif" WIDTH="128" HEIGHT="13"></TD>
</TR>

<!--BEGIN EMAIL-->
<TR>
	<TD BGCOLOR="#000033">

<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="3" WIDTH="100%">
<TR>
	<TD Align="Center" VALIGN="TOP"><FONT id=a12>Sign up for your free Email/Voicemail/Fax account Now!</FONT><BR>
<FONT id=a12><A HREF="mail/index.html">Click Here</A></FONT></TD>
</TR>
</TABLE>

	</TD>
</TR>
<!--END EMAIL-->
<TR>
	<TD BGCOLOR="#330033" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/infocenter/t_spec_int.gif" WIDTH="128" HEIGHT="13"></TD>
</TR>

<!--BEGIN SPECIAL INT-->
<TR>
	<TD BGCOLOR="#330033">
	
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="3" WIDTH="100%">
<TR>
	<TD Align="Center" VALIGN="TOP"><FONT id=a12>What's Your Future?</FONT><BR>
<FONT id=a12><A HREF="http://www.onlinepsychic.com/">Find Out Now.</A></FONT></TD>
</TR>
</TABLE>

	</TD>
</TR>
<!--END SPECIAL INT-->
<TR>
	<TD BGCOLOR="#000033" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/infocenter/t_fav_chan.gif" WIDTH="128" HEIGHT="13"></TD>
</TR>

<!--BEGIN FAV CHAN-->
<TR>
	<TD BGCOLOR="#000033" ALIGN="CENTER">

<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="3">
<TR>
	<TD Align="LEFT" VALIGN="TOP">
<FONT id=a12><A HREF="customize/index.html">Preset 1 - Not Set</A></FONT><BR>
<FONT id=a12><A HREF="customize/index.html">Preset 2 - Not Set</A></FONT><BR>
<FONT id=a12><A HREF="customize/index.html">Preset 3 - Not Set</A></FONT><BR></TD>
</TR>
</TABLE>

	</TD>
</TR>
<!--END FAV CHAN-->
<TR>
	<TD COLSPAN="3"><A HREF="javascript:infowindow()"><IMG SRC="http://images.broadcastamerica.com/infocenter/info_bottom.gif" WIDTH="140" HEIGHT="23" BORDER="0"></A></TD>
</TR>

</TABLE>
<!--END INFOCENTER-->

<!--Begin Right Nav TABLE BLACK-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="140">
<TR>
	<TD ALIGN="Left" VALIGN="Top" COLSPAN="3" WIDTH="140"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="18"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="116" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_top_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%" HEIGHT="100%">
<!--begin event.tmpl-->
<IMG SRC="http://images.broadcastamerica.com/main/t_events.gif" WIDTH="116" HEIGHT="28"><BR>
<IMG SRC="http://images.broadcastamerica.com/station_logos/music/superV_special.gif" WIDTH="116" HEIGHT="94"><BR>

<font id=a17>SUPER V</font><BR>
<font id=a16>Interactive Music TV<BR>
An EXCLUSIVE collaboration of Superadio and BroadcastAmerica<BR>
Coming soon!</font><P>

<font id=a17>Open House Party</font><BR>
<font id=a16>Live Broadcast<BR>
Saturdays<BR>
7pm est - Midnight</font><P>

<!--end event.tmpl-->

<!--begin new.tmpl-->
<IMG SRC="http://images.broadcastamerica.com/main/t_new.gif" WIDTH="116" HEIGHT="28" BORDER="0">

<font id=a31><BR>Clubs</font><BR>
<A HREF="http://Clubs.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Paul%20Oakenfold/bio?call=pauloak_bc"><font id=a17> Paul Oakenfold<BR>
</font></A><font id=a13>(World's #1 DJ)</font><P>

<font id=a31>Music</font><BR>
<A HREF="http://Music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/KRBI/bio?call=krbi_fm_bm"><font id=a17>KRBI</font></A><font id=a13> - 105.5 FM<BR>
Contemporary<BR>
St. Peter, MN</font><P>

<font id=a31>Sports</font><BR>
<A HREF="http://Sports.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WTAZ/bio?call=wtaz_am_bs"><font id=a17>WTAZ</font></A><font id=a13> - 1350 AM<BR>
Sports Talk/News<BR>
Peoria, IL</font><P>

<font id=a31>Talk</font><BR>
<A HREF="http://Talk.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WCGR/bio?call=wcgr_am_bt"><font id=a17>WCGR</font></A><font id=a13> - 1550 AM<BR>
News/Talk<BR>
Canandaigua, NY</font><P>

<font id=a31>TV News</font><BR>
<A HREF="http://Tvnews.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/KXD/bio?call=kkxd_tv"><font id=a17>KKXD</font></A><font id=a13> - CBS 13<BR>
Fairbanks, AK</font><P>





<!--end new.tmpl-->
</TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_l.gif" WIDTH="12" HEIGHT="12"></TD>
	<TD ALIGN="Left" VALIGN="Top" bgcolor="#000000" WIDTH="100%"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="1" HEIGHT="1"></TD>
	<TD ALIGN="Left" VALIGN="Top"  WIDTH="12"><IMG SRC="http://images.broadcastamerica.com/main/black_curve_bot_r.gif" WIDTH="12" HEIGHT="12"></TD>
</TR>
</TABLE>
<!--End Right Nav TABLE BLACK-->	

<!--BEGIN SPACER-->
<IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10">
<!--END SPACER-->

<!--begin main_ad_2r.phtml-->
<CENTER></CENTER>
<!--end main_ad_2r.phtml-->
	</TD>
<!--END RIGHT TD-->	
		
</TR>

</TABLE>	
	
<!--End Body TABLE	-->

<TABLE WIDTH="764" BORDER="0" CELLSPACING="0" CELLPADDING="0">

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

<TR>
	<TD COLSPAN="2" ALIGN="Left" VALIGN="Top">

<!--begin navbar.phtml bottom-->
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_l.gif" WIDTH="13" HEIGHT="36"></TD>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
	<TD ROWSPAN="3" WIDTH="13" VALIGN="TOP"><IMG SRC="http://images.broadcastamerica.com/main/nav_curve_r.gif" WIDTH="13" HEIGHT="36"></TD>
</TR>
<TR>
	<TD ALIGN="Left" VALIGN="Middle" WIDTH="739" HEIGHT="28">
<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="220">
<FORM ACTION="http://search.broadcastamerica.com/results.phtml" METHOD="GET">
<TR><TD>
<font id="a12"><SELECT NAME="which">
<OPTION value=site>Search Channels</OPTION>
<OPTION value=web>Search Web</OPTION>
<OPTION value=music>Music</OPTION>
<OPTION value=sports>Sports</OPTION>
<OPTION value=clubs>Clubs</OPTION>
<OPTION value=talk>Talk</OPTION>
<OPTION value=tvnews>TV News</OPTION>
<OPTION value=movies>Movies</OPTION>
<OPTION value=urban>Urban</OPTION>
<OPTION value=bible>Christian</OPTION>
<OPTION value=comedy>Comedy</OPTION>
<OPTION value=wisdom>Wisdom</OPTION>
</SELECT></font>
</TD>
<TD><INPUT NAME="spec" TYPE=Text SIZE="8" MAXLENGTH="40"></TD><TD><INPUT NAME="FIND" TYPE=Submit VALUE="Find"></TD>
<TD ALIGN="Left" VALIGN="MIDDLE"><A HREF="http://www.goto.com/"><IMG SRC="http://images.broadcastamerica.com/main/goto_logo.gif" WIDTH="37" HEIGHT="23" BORDER="0"></A></TD></TR>
</FORM>
</TABLE>
</TD>

	<TD ALIGN="RIGHT" VALIGN="MIDDLE"><font id=a17><A HREF="index.html">Home</A> | <A HREF="mail/index.html">Free Voice/Fax/Email</A> | <A HREF="news/index.html">World News</A> | <A HREF="weather/scripts/index.html">Weather</A> | <A HREF="customize/index.html">Customize</A> | <A HREF="help/index.html">Help</A></font></TD>
</TR>
</TABLE>

</TD>
</TR>
<TR>
	<TD WIDTH="200" HEIGHT="4" BGCOLOR="#000000" VALIGN="BOTTOM"><IMG SRC="http://images.broadcastamerica.com/main/black.gif" WIDTH="10" HEIGHT="3"></TD>
</TR>
</TABLE>

<!--end navbar.phtml bottom-->
	</TD>
</TR>

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

<!--begin copyright.tmpl-->
<TR>
<TD COLSPAN="2" ALIGN="CENTER"><font id=a12>© Copyright 2000, BroadcastAmerica.com All rights reserved.<BR>
digiQue © Copyright 1999, BroadcastAmerica.com.</font></TD></TR>

<!--end copyright.tmpl-->

<!--BEGIN SPACER-->
<TR><TD COLSPAN="2"><IMG SRC="http://images.broadcastamerica.com/main/trans.gif" WIDTH="10" HEIGHT="10"></TD></TR>
<!--END SPACER-->

</TABLE>

<SCRIPT language="JavaScript">
	document.writeln(myscroll.divStart)
</SCRIPT>

<TABLE WIDTH=230 border=0 CELLSPACING=0 CELLPADDING=5 bgcolor="#003366"><TR><TD>

<!--begin main_menu.tmpl-->
<!--------------------------------------------------------------------->
<!double breaks are necessary here as the P command does not work-->
<!--------------------------------------------------------------------->
<font id=a7>Film Trailers</font><BR>
<a href="http://movies.broadcastamerica.com/stations/moreinfo/bio.phtml?code=fs_vert"><img src="http://images.broadcastamerica.com/movies/vlimit_200x60.gif" border="0" vspace="3"></a><br>
<font id=a16>Some of Newest and Best Trailers on the Web! <a href="http://movies.broadcastamerica.com/stations/index.phtml?g=trfs">Check them out!</a></font><BR><BR>

<font id=a7>Music</font><BR>

<font id=a16>Over 400 Exclusive Live Stations! Plus:</font><BR><BR>

<font id=a16><A HREF="http://music.broadcastamerica.com">Open House Party</A>, 
<A HREF="http://music.broadcastamerica.com/stations/index.phtml/Dick%20Clark's%20United%20Stations%20Radio%20Network?l=syn&g=unis">Dick Clark's United Stations Radio Network</A>, 
<A HREF="http://music.broadcastamerica.com/stations/index.phtml/SuperRadio?l=syn&g=supr">Superadio</A>, 
<A HREF="http://music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/SuperJamz/Bio?call=spr006">SuperJAMZ</A>, 
<A HREF="http://music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Russ%20Parr%20Morning%20Show/Bio?call=spr044">Russ Parr</A>, 
<A HREF="http://music.broadcastamerica.com/stations/index.phtml/Star%20Interviews?l=star">Star Interviews</A>, 
<A HREF="http://music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Lost%20in%20the%2080's/Bio?call=spr040">Lost in the 80's</A>, 
<A HREF="http://music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Bowling%20Radio%20-%20Rock%20300/Bio?call=spr041">Bowling Radio - Rock 300</A>, 
<A HREF="http://music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Cable%20Radio%20Network%201/Bio?call=spr037">Cable Radio Network 1</A>, 
<A HREF="http://music.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Holy%20Hip%20Hop%20Radio/Bio?call=spr043">Holy Hip Hop Radio</A>, 
<A HREF="mail/index.html">Free Voice Mail Email and Fax</A></font><BR><BR>

<font id=a7>Sports</font><BR>

<A HREF="http://sports.broadcastamerica.com/"><font id=a17>The Virtual Player</font></a><BR>
<font id=a16>Welcome to a better way of analyzing</font><font id=a2> baseball statistics and games</font><font id=a16> on the Internet. You gotta see this stuff!</font><font id=a16><A HREF="http://sports.broadcastamerica.com/virtualplayer/"> Click Here</a> to Play!</font><br><br>
<font id=a16>Also...</font><BR>
<font id=a16><A HREF="http://sports.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/One-On-One%20Sports/bio?call=oneon1">One-On-One Sports</A>, 
<A HREF="http://sports.broadcastamerica.com/hoffer/hoffer1.phtml">Hoffer Report</A>, 
<A HREF="http://sports.broadcastamerica.com/index.phtml">Sports Trivia</A>, 
<A HREF="http://sports.broadcastamerica.com/stations/index.phtml/Stations/International?g=IN">International Sports</A>,<A HREF="http://sports.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Base%20Camp%20America/Bio?call=basecam">BaseCamp America</a></font><BR><BR>

<font id=a7>Talk</font><BR>

<font id=a16>Over 240 Exclusive Talk shows and 100's of Talk Radio Stations.</font><BR><BR>

<font id=a16><A HREF="http://talk.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/TRN1/Bio?call=trn1">Talk Radio Network</A>, 
<A HREF="http://talk.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Doug%20Stephan's%20Good%20Day%20USA/bio?call=ts06007">Doug Stephan, "Good Day USA"</A>, 
<A HREF="http://talk.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/Talk%20Radio%20Network/Bio?call=tan1">Talk America</A></font><BR><BR> 

<font id=a7>Local TV News</font><BR>

<font id=a16>Over 70 Live Local TV News Broadcasts from across the U.S.A.</font><BR><BR>

<font id=a16><A HREF="http://tvnews.broadcastamerica.com">Local Television News</A>, 
<A HREF="http://tvnews.broadcastamerica.com/stations/index.phtml/Technology%20Today?l=syn&g=techtoday">Technology Today</A>, 
<A HREF="http://tvnews.broadcastamerica.com/stations/moreinfo/bio.phtml/Stations/WJMK/Bio?code=wjmk_tv">American Review Series</A>, 
<A HREF="http://tvnews.broadcastamerica.com/stations/index.phtml/Stations/International?r=IN">International  News</A></font><BR><BR>

<!--------------------------------------------------------------------->
<!---------------The Last <BR> command must be included---------------->
<!--------------------------------------------------------------------->

<!--end main_menu.tmpl-->

</TD></Tr></TABLE>

<SCRIPT language="JavaScript">
	document.writeln(myscroll.divEnd)
</SCRIPT>

<DIV id="newsbottom"><IMG SRC="http://images.broadcastamerica.com/main/livedish_bot.gif" WIDTH="243" HEIGHT="18"></DIV>


<!--begin loc.tmpl-->
<div ID="currentloc" STYLE="position:absolute; text-align:right; left:332; top:123; width:430; height:20; z-index:3; font-family:arial,helvetica; color:#FFFFFF; font-size:12px; clip:rect(0,430,16,0);">
<I><a href="index.html">Home</a></I></div>

<!--end loc.tmpl-->


</BODY>
</HTML>
