

<DIV ID="TEXT" STYLE="Width:800;z-index:7;position:absolute;top:0;">    
<TABLE BORDER=0 CELLSPACING=1>
  <TD width=88 bgcolor="#e1f2e1">請選擇類別:</TD>    
  <TD width=65 bgcolor="#e1f2e1"><A HREF="2link.asp?Criteria=All" TARGET="_self">全部網站</A></TD>   
  <TD width=65 bgcolor="#e1f2e1"><A HREF="2link.asp?Criteria=Factory" TARGET="_self">製造工廠</A></TD>    
  <TD width=65 bgcolor="#e1f2e1"><A HREF="2link.asp?Criteria=Taiwan" TARGET="_self">台灣網站</A></TD>    
  <TD width=65 bgcolor="#e1f2e1"><A HREF="2link.asp?Criteria=Japan" TARGET="_self">日本網站</A></TD>    
  <TD width=65 bgcolor="#e1f2e1"><A HREF="2link.asp?Criteria=Europe" TARGET="_self">歐洲網站</A></TD>    
  <TD width=65 bgcolor="#e1f2e1"><A HREF="2link.asp?Criteria=American" TARGET="_self">美加網站</A></TD>    
  <TD width=65 bgcolor="#e1f2e1"><A HREF="2link.asp?Criteria=Other" TARGET="_self">其它網站</A></TD>    
  <TD width=65 bgcolor="#e1f2e1"></TD>
  <TD width=65 bgcolor="#e1f2e1"></TD>
  <TD width=65 bgcolor="#e1f2e1"></TD>
</TABLE>
</DIV><br> 



<HTML>
<HEAD><TITLE>分段瀏覽資料錄的技巧</TITLE></HEAD>

<style type="text/CSS"> 
A:hover { background-color:"#ffffdf";color:"#999933"; } 
body{background-color:#ffffff;}  
td{ font-family: 新細明體; color:#000000; } 
A{color:"black"; text-decoration:none;} 
</style>

<BODY bgcolor="#FFFFFF">

<DIV ALIGN=center>

<FORM Action=2link.asp Method=GET>

<font color=grand size=5><B></B></font><br>
<input TYPE="button" VALUE="我要提供新網站給車友" onClick="location='web_add.asp'">
<input TYPE="button" VALUE="回 首 頁" onClick="location='../contents1.asp'">

<CENTER><table border=0 width=100% cellspacing=1 bgcolor=#ffffff><TR BGCOLOR=#d8d8c5>
	<TD width="2%">No</TD>
	<TD width="8%">日期</TD>
	<td width="8%"><font size=3>類別</td>
	<td width="20%"><font size=3>站名及網址</td>
        <td width="57%"><font size=3>網站內容概述</td>
<!--        
        <td width="12%"><font size=3>提供者</td>
        -->
  </TR><TR  bgcolor=#edefd8>
      
    <TD NOWRAP align="center"><font size=2>1</TD>
	<TD NOWRAP><font size=2>2001/5/6</A></TD>
    <td><font size=2><a style="color:olive" target="_blank" href="http://台灣地區">台灣地區</a></td>
	<td><font size=2><a style="color:olive" target="_blank" href="http://http://home.kimo.com.tw/chang_hua1/tra.htm">台灣鐵路局彰化站</a></td>
    <td><font size=2><a style="color:olive" target="_blank" href="http://http://home.kimo.com.tw/chang_hua1/tra.htm">本站是官辦民營的鐵路時刻及其他彰化地區旅遊查詢!!歡迎來本站參觀!!</a></td>
        <!--
        <td><font size=2><a href="mailto:chang_hua1@kimo.com.tw">台灣鐵路局 彰化站</a></td>
        -->
</TR><TR  bgcolor=#edefd8>
      
    <TD NOWRAP align="center"><font size=2>2</TD>
	<TD NOWRAP><font size=2>2001/5/6</A></TD>
    <td><font size=2><a style="color:olive" target="_blank" href="http://台灣地區">台灣地區</a></td>
	<td><font size=2><a style="color:olive" target="_blank" href="http://http://chiayu.tacomall.com.tw/chia.html">佳鈺精品休閒購物網站</a></td>
    <td><font size=2><a style="color:olive" target="_blank" href="http://http://chiayu.tacomall.com.tw/chia.html">佳鈺精品是第一家專門賣鐵路相關小飾品!CK101鑰匙圈及CK124鑰匙圈...等!歡迎來本站參觀!!</a></td>
        <!--
        <td><font size=2><a href="mailto:ch5511@ms14.hinet.net">佳鈺精品</a></td>
        -->
</TR><TR  bgcolor=#edefd8>
      
    <TD NOWRAP align="center"><font size=2>3</TD>
	<TD NOWRAP><font size=2>2001/4/12</A></TD>
    <td><font size=2><a style="color:olive" target="_blank" href="http://其它地區">其它地區</a></td>
	<td><font size=2><a style="color:olive" target="_blank" href="http://hkrailway.uhome.net">香港鐵路廣播資料館</a></td>
    <td><font size=2><a style="color:olive" target="_blank" href="http://hkrailway.uhome.net">香港鐵路廣播資料館是一所綜合香港鐵路廣播(Public Address)的網站，可以即時收聽香港鐵路的廣播，還有一些特別的音效，挻有趣的。</a></td>
        <!--
        <td><font size=2><a href="mailto:mtrcorp28@hotmail.com">CEric</a></td>
        -->
</TR><TR  bgcolor=#edefd8>
      
    <TD NOWRAP align="center"><font size=2>4</TD>
	<TD NOWRAP><font size=2>2001/4/8</A></TD>
    <td><font size=2><a style="color:olive" target="_blank" href="http://美國地區">美國地區</a></td>
	<td><font size=2><a style="color:olive" target="_blank" href="http://Eurorailhobbies.com">火車專賣店</a></td>
    <td><font size=2><a style="color:olive" target="_blank" href="http://Eurorailhobbies.com">這是英文網站，但有中文服務，公司有講國、台語的專人為您服務…</a></td>
        <!--
        <td><font size=2><a href="mailto:jimmy@Eurorailhobbies.com">Jimmy</a></td>
        -->
</TR><TR  bgcolor=#edefd8>
      
    <TD NOWRAP align="center"><font size=2>5</TD>
	<TD NOWRAP><font size=2>2001/4/1</A></TD>
    <td><font size=2><a style="color:olive" target="_blank" href="http://製造工廠">製造工廠</a></td>
	<td><font size=2><a style="color:olive" target="_blank" href="http://www.bemo-modellbahn.de/index.htm">瑞士 BEMO </a></td>
    <td><font size=2><a style="color:olive" target="_blank" href="http://www.bemo-modellbahn.de/index.htm">瑞士高品質模型火車, 以HO為主, 另有HOe, HOm 比例火車.</a></td>
        <!--
        <td><font size=2><a href="mailto:jason_lee@ms9.url.com.tw">Jason Lee</a></td>
        -->
</TR><TR  bgcolor=#edefd8>
      
    <TD NOWRAP align="center"><font size=2>6</TD>
	<TD NOWRAP><font size=2>2001/3/31</A></TD>
    <td><font size=2><a style="color:olive" target="_blank" href="http://台灣地區">台灣地區</a></td>
	<td><font size=2><a style="color:olive" target="_blank" href="http://www.taconet.com.tw/sasa2121/">模型火車庫</a></td>
    <td><font size=2><a style="color:olive" target="_blank" href="http://www.taconet.com.tw/sasa2121/">一個值得一看的網站哦</a></td>
        <!--
        <td><font size=2><a href="mailto:sam2222@ms49.url.com.tw">sam</a></td>
        -->
</TR><TR  bgcolor=#edefd8>
      
    <TD NOWRAP align="center"><font size=2>7</TD>
	<TD NOWRAP><font size=2>2001/3/30</A></TD>
    <td><font size=2><a style="color:olive" target="_blank" href="http://製造工廠">製造工廠</a></td>
	<td><font size=2><a style="color:olive" target="_blank" href="http://www.geacities.com/culhps">九龍車站</a></td>
    <td><font size=2><a style="color:olive" target="_blank" href="http://www.geacities.com/culhps">介紹中國火車模型的網站</a></td>
        <!--
        <td><font size=2><a href="mailto:culhps@hotmail.com">九龍車站</a></td>
        -->
</TR><TR  bgcolor=#edefd8>
      
    <TD NOWRAP align="center"><font size=2>8</TD>
	<TD NOWRAP><font size=2>2001/3/19</A></TD>
    <td><font size=2><a style="color:olive" target="_blank" href="http://製造工廠">製造工廠</a></td>
	<td><font size=2><a style="color:olive" target="_blank" href="http://www.bachmannindustries.com">Bachmann </a></td>
    <td><font size=2><a style="color:olive" target="_blank" href="http://www.bachmannindustries.com">德國 Bachmann industries Inc,. 公司, 因其有很多生產線已轉移大陸, 故其產品居等價位, 也有很多代表作.</a></td>
        <!--
        <td><font size=2><a href="mailto:train_lee@yahoo.com">train_lee</a></td>
        -->
</TR><TR  bgcolor=#edefd8>
      
    <TD NOWRAP align="center"><font size=2>9</TD>
	<TD NOWRAP><font size=2>2001/3/15</A></TD>
    <td><font size=2><a style="color:olive" target="_blank" href="http://製造工廠">製造工廠</a></td>
	<td><font size=2><a style="color:olive" target="_blank" href="http://home.t-online.de/home/FR.model/">Z scale 製造工廠 </a></td>
    <td><font size=2><a style="color:olive" target="_blank" href="http://home.t-online.de/home/FR.model/">產品不多, 但銅件車體, 馬達有飛輪, 接近手工.</a></td>
        <!--
        <td><font size=2><a href="mailto:jason_lee@ms9.url.com.tw">jason Lee</a></td>
        -->
</TR><TR  bgcolor=#edefd8>
      
    <TD NOWRAP align="center"><font size=2>10</TD>
	<TD NOWRAP><font size=2>2001/3/15</A></TD>
    <td><font size=2><a style="color:olive" target="_blank" href="http://其它地區">其它地區</a></td>
	<td><font size=2><a style="color:olive" target="_blank" href="http://www.campbelltools.com">迷你車床</a></td>
    <td><font size=2><a style="color:olive" target="_blank" href="http://www.campbelltools.com">模型火車用迷你車床</a></td>
        <!--
        <td><font size=2><a href="mailto:train_lee@yahoo.com">Jason 站長</a></td>
        -->
</TR></TABLE></CENTER><A HREF=2link.asp?Page=2>下一頁</A>　<A HREF=2link.asp?Page=12>最後一頁</A>　
輸入頁次:<INPUT TYPE=TEXT Name=Page SIZE=3>　共:<FONT COLOR="Red">1/12</FONT>頁次

</BODY>
</HTML>






