--09:34:21--  http://www.mojjob.sk:80/
           => `www.mojjob.sk/index.html'
Connecting to www.mojjob.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]

    0K -> .....

09:34:23 (13.29 KB/s) - `www.mojjob.sk/index.html' saved [5823]

Loading robots.txt; please ignore errors.
--09:34:23--  http://www.mojjob.sk:80/no-robots.txt
           => `www.mojjob.sk/no-robots.txt'
Connecting to www.mojjob.sk:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
09:34:24 ERROR 404: Object Not Found.

--09:34:24--  http://www.mojjob.sk:80/hell.jpg
           => `www.mojjob.sk/hell.jpg'
Connecting to www.mojjob.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 13,862 [image/jpeg]

    0K -> .......... ...                                         [100%]

09:34:26 (9.05 KB/s) - `www.mojjob.sk/hell.jpg' saved [13862/13862]

Converting www.mojjob.sk/index.html... done.

FINISHED --09:34:28--
Downloaded: 19,685 bytes in 2 files
Converting www.mojjob.sk/index.html... done.
