--16:25:51--  http://www.fgi.org.gr:80/
           => `www.fgi.org.gr/index.html'
Connecting to www.fgi.org.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 43 [text/html]

    0K ->                                                        [100%]

16:25:52 (131.10 B/s) - `www.fgi.org.gr/index.html' saved [43/43]

Converting www.fgi.org.gr/index.html... done.

FINISHED --16:25:52--
Downloaded: 43 bytes in 1 files
