<HTML>
<TITLE>League Transactions</TITLE>
<BODY BGCOLOR="#FFFFFF">
<CENTER>
<H1>UFBA League Transactions</H1>
<TABLE>
<TR BGCOLOR=#006ff><B><TD>Date</TD><TD>Team</TD><TD>Transaction</TD></B></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Oct 30 11:50:04 2000
</TD><TD>Boom_Babies</TD><TD>Picked up <B>harrington,al</B> and dropped <B>harrington,othel</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Oct 30 12:30:58 2000
</TD><TD>Arsenal</TD><TD>Picked up <B>fortson,danny</B> and dropped <B>billups,chauncey</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Oct 30 20:04:31 2000
</TD><TD>Boom_Babies</TD><TD>Picked up <B>billups,chauncey</B> and dropped <B>marshall,donny</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Tue Oct 31 22:47:33 2000
</TD><TD>Mavs</TD><TD>Picked up <B>nash,steve</B> and dropped <B>starks,john</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Nov  1 12:45:44 2000
</TD><TD>Austinites</TD><TD>Picked up <B>jackson,bobby</B> and dropped <B>wright,lorenzen</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Nov  1 12:47:08 2000
</TD><TD>Austinites</TD><TD>Picked up <B>best,travis</B> and dropped <B>divac,vlade</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Thu Nov  2 12:16:29 2000
</TD><TD>Nanooks</TD><TD>Picked up <B>henderson,alan</B> and dropped <B>barry,brent</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Thu Nov  2 12:16:53 2000
</TD><TD>Nanooks</TD><TD>Picked up <B>lopez,felipe</B> and dropped <B>williams,jason</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Thu Nov  2 13:16:00 2000
</TD><TD>Austinites</TD><TD>Picked up <B>weatherspoon,cla</B> and dropped <B>murray,lamond</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Fri Nov  3 14:42:29 2000
</TD><TD>Sandstorm</TD><TD>Picked up <B>snow,eric</B> and dropped <B>ilgauskas,zydrun</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sun Nov  5 17:02:19 2000
</TD><TD>Austinites</TD><TD>Picked up <B>wallace,ben</B> and dropped <B>patterson,ruben</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sun Nov  5 21:56:58 2000
</TD><TD>Sandstorm</TD><TD>Picked up <B>mcinnis,jeff</B> and dropped <B>snow,eric</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sun Nov  5 23:47:30 2000
</TD><TD>Turbulence</TD><TD>Picked up <B>harrington,othel</B> and dropped <B>swift,stomile</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Nov  6 14:57:40 2000
</TD><TD>Sandstorm</TD><TD>Picked up <B>swift,stomile</B> and dropped <B>lafrentz,raef</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Nov  6 14:59:27 2000
</TD><TD>Sandstorm</TD><TD>Picked up <B>mcinnis,jeff</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Nov  6 15:44:04 2000
</TD><TD>Nanooks</TD><TD>Picked up <B>lenard,voshon</B> and dropped <B>lopez,felipe</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Tue Nov  7 12:18:43 2000
</TD><TD>Arsenal</TD><TD>Picked up <B>wright,lorenzen</B> and dropped <B>delk,tony</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Thu Nov  9 01:40:37 2000
</TD><TD>Austinites</TD><TD>Picked up <B>snow,eric</B> and dropped <B>jackson,bobby</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Thu Nov  9 01:55:22 2000
</TD><TD>Austinites</TD><TD>Picked up <B>lafrentz,raef</B> and dropped <B>wallace,ben</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Thu Nov  9 18:48:51 2000
</TD><TD>Sandstorm</TD><TD>Picked up <B>swift,stromile</B> and dropped <B>swift,stomile</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sun Nov 12 18:25:59 2000
</TD><TD>Austinites</TD><TD>Picked up <B>williams,jason</B> and dropped <B>weatherspoon,cla</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Nov 13 10:13:22 2000
</TD><TD>Boom_Babies</TD><TD>Picked up <B>williams,jerome</B> and dropped <B>bender,jonathan</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Nov 15 16:10:14 2000
</TD><TD>Turbulence</TD><TD>Picked up <B>outlaw,charles</B> and dropped <B>richmond,mitch</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sat Nov 18 15:15:19 2000
</TD><TD>Sandstorm</TD><TD>Picked up <B>divac,vlade</B> and dropped <B>maggette,corey</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sun Nov 19 19:36:28 2000
</TD><TD>Sandstorm</TD><TD>Picked up <B>rogers,rodney</B> and dropped <B>divac,vlade</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Nov 20 01:39:38 2000
</TD><TD>Austinites</TD><TD>Picked up <B>richmond,mitch</B> and dropped <B>lafrentz,raef</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Nov 22 20:25:18 2000
</TD><TD>Mavs</TD><TD>Picked up <B>weatherspoon,cla</B> and dropped <B>najera,eduardo</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sat Nov 25 00:24:27 2000
</TD><TD>Arsenal</TD><TD>Picked up <B>hamilton,richard</B> and dropped <B>wright,lorenzen</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sun Nov 26 15:48:11 2000
</TD><TD>Skanksters</TD><TD>Picked up <B>campbell,elden</B> and dropped <B>sealy,malik</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sun Nov 26 15:50:38 2000
</TD><TD>Skanksters</TD><TD>Picked up <B>blaylock,mookie</B> and dropped <B>laettner,christi</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sat Dec  2 00:27:23 2000
</TD><TD>Mavs</TD><TD>Picked up <B>richardson,quent</B> and dropped <B>kukoc,toni</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Dec  4 00:22:59 2000
</TD><TD>Sandstorm</TD><TD>Picked up <B>battie,tony</B> and dropped <B>rogers,rodney</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Dec  4 00:56:03 2000
</TD><TD>Turbulence</TD><TD>Picked up <B>harpring,matt</B> and dropped <B>sabonis,arvydas</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Tue Dec  5 01:43:32 2000
</TD><TD>Arsenal</TD><TD>Picked up <B>lafrentz,raef</B> and dropped <B>hamilton,richard</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Dec 13 13:48:11 2000
</TD><TD>Arsenal</TD><TD>Picked up <B>ilgauskas,zydrun</B> and dropped <B>lafrentz,raef</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Dec 13 23:29:55 2000
</TD><TD>Boom_Babies</TD><TD>Picked up <B>williams,aaron</B> and dropped <B>williams,jerome</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sun Dec 17 16:02:46 2000
</TD><TD>Skanksters</TD><TD>Picked up <B>lafrentz,raef</B> and dropped <B>rider,isaiah</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Tue Dec 19 11:12:50 2000
</TD><TD>Launch</TD><TD>Picked up <B>mckie,aaron</B> and dropped <B>anderson,shandon</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Dec 25 19:50:59 2000
</TD><TD>Arsenal</TD><TD>Picked up <B>wallace,ben</B> and dropped <B>ilgauskas,zydrun</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Tue Dec 26 16:42:29 2000
</TD><TD>Turbulence</TD><TD>Picked up <B>sabonis,arvydas</B> and dropped <B>fizer,marcus</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Dec 27 02:41:02 2000
</TD><TD>Austinites</TD><TD>Picked up <B>jackson,marc</B> and dropped <B>williams,jason</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sat Dec 30 01:26:32 2000
</TD><TD>Arsenal</TD><TD>Picked up <B>wright,lorenzen</B> and dropped <B>brown,p.j.</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sun Dec 31 14:20:57 2000
</TD><TD>Sandstorm</TD><TD>Picked up <B>rogers,rodney</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sun Dec 31 14:22:52 2000
</TD><TD>Sandstorm</TD><TD>Picked up <B>mcinnis,jeff</B> and dropped <B>swift,stromile</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Tue Jan  2 12:55:08 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>knight,brevin</B> and dropped <B>wallace,ben</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Jan  8 10:55:57 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>whitney,chris</B> and dropped <B>jackson,jimmy</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sun Jan 14 14:48:24 2001
</TD><TD>Austinites</TD><TD>Picked up <B>oakley,charles</B> and dropped <B>jackson,mark</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Jan 15 13:36:28 2001
</TD><TD>Launch</TD><TD>Picked up <B>thomas,kurt</B> and dropped <B>olajuwon,hakeem</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Jan 15 13:45:13 2001
</TD><TD>Launch</TD><TD>Picked up <B>wallace,ben</B> and dropped <B>mills,chris</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Jan 17 00:52:31 2001
</TD><TD>Ice</TD><TD>Picked up <B>wells,bonzi</B> and dropped <B>gill,kendall</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Jan 17 00:54:55 2001
</TD><TD>Ice</TD><TD>Picked up <B>patterson,ruben</B> and dropped <B>ewing,patrick</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Jan 17 01:00:07 2001
</TD><TD>Ice</TD><TD>Picked up <B>divac,vlade</B> and dropped <B>croshere,austin</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Jan 17 01:02:40 2001
</TD><TD>Ice</TD><TD>Picked up <B>hamilton,richard</B> and dropped <B>artest,ron</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sat Jan 20 19:24:40 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>gatling,chris</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sun Jan 21 18:00:57 2001
</TD><TD>Sandstorm</TD><TD>Picked up <B>jackson,mark</B> and dropped <B>battie,tony</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Jan 22 11:41:36 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>sura,bob</B> and dropped <B>gatling,chris</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Jan 22 14:59:20 2001
</TD><TD>Skanksters</TD><TD>Picked up <B>delk,tony</B> and dropped <B>coleman,derrick</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Jan 22 15:00:48 2001
</TD><TD>Skanksters</TD><TD>Picked up <B>gatling,chris</B> and dropped <B>kemp,shawn</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Tue Jan 30 00:06:26 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>brown,p.j.</B> and dropped <B>sura,bob</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Tue Jan 30 14:32:07 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>barry,brent</B> and dropped <B>brown,p.j.</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Thu Feb  1 16:27:02 2001
</TD><TD>Sandstorm</TD><TD>Picked up <B>jackson,jimmy</B> and dropped <B>mcinnis,jeff</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Fri Feb 16 14:59:22 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>olajuwon,hakeem</B> and dropped <B>knight,brevin</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Feb 19 12:27:37 2001
</TD><TD>Mavs</TD><TD>Picked up <B>jackson,bobby</B> and dropped <B>atkins,chucky</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Thu Feb 22 14:55:44 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>kukoc,toni</B> and dropped <B>barry,brent</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Feb 26 00:40:54 2001
</TD><TD>Sandstorm</TD><TD>Picked up <B>nesby,tyrone</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Feb 26 00:44:02 2001
</TD><TD>Sandstorm</TD><TD>Picked up <B>rogers,rodney</B> and dropped <B>jackson,jimmy</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Fri Mar  2 18:13:27 2001
</TD><TD>Sandstorm</TD><TD>Picked up <B>laettner,christi</B> and dropped <B>nesby,tyrone</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sat Mar 10 00:08:16 2001
</TD><TD>Skanksters</TD><TD>Picked up <B>artest,ron</B> and dropped <B>delk,tony</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sat Mar 10 00:09:16 2001
</TD><TD>Skanksters</TD><TD>Picked up <B>mcinnis,jeff</B> and dropped <B>anderson,kenny</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sat Mar 10 00:12:00 2001
</TD><TD>Skanksters</TD><TD>Picked up <B>brown,p.j.</B> and dropped <B>gatling,chris</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Mon Mar 12 00:17:34 2001
</TD><TD>Mavs</TD><TD>Picked up <B>maggette,corey</B> and dropped <B>hardaway,anferne</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Mar 14 00:20:40 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>williamson,corli</B> and dropped <B>olajuwon,hakeem</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Wed Mar 14 00:31:18 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>barry,brent</B> and dropped <B>wright,lorenzen</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sat Mar 17 02:13:37 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>fizer,marcus</B> and dropped <B>barry,brent</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Sat Mar 24 15:12:49 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>olajuwon,hakeem</B> and dropped <B>fizer,marcus</B></TD></TR>
<TR BGCOLOR=#DCDCDC><TD>Tue Mar 27 15:28:08 2001
</TD><TD>Arsenal</TD><TD>Picked up <B>newman,johnny</B> and dropped <B>williamson,corli</B></TD></TR>
</TABLE>
</BODY>
</HTML>
