<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>New Page 1</title>
</head>

<body>
<!-- Ad Code Generated by Led-Ads (PHP/MYSQL version .7) http://www.ledscripts.com --><center><IMG SRC="http://servicbfast.com/bfast/serve?bfmid=19187551&siteid=32617985&bfpage=homepage2" BORDER="0" WIDTH="1" HEIGHT="1" NOSAVE ><A HREF="http://service.bfast.com/bfast/click?bfmid=19187551&siteid=32617985&bfpage=homepage2" TARGET="_blank"><IMG SRC="http://a1964.g.akamaitech.net/7/1964/452/000000001/www.dealtime.com/about/affiliate/468x60_drop21.gif" BORDER="0" WIDTH="468" HEIGHT="60" ALT=""></A>e.</center><!-- End Ad Code --><p align="center"><img border="0" src="images/league.jpg" width="141" height="78"></p>
<table border="1" width="100%">
  <tr>
    <td width="33%" align="center"><b><u>Event</u></b></td>
    <td width="33%" align="center"><b><u>Date Begins</u></b></td>
    <td width="34%" align="center"><b><u>Counsel Representative</u></b></td>
  </tr>
  <tr>
    <td width="33%"><a href="leagues/tkoth_league.htm">DF2 TKOTH League</a></td>
    <td width="33%">Pending</td>
    <td width="34%">TBD</td>
  </tr>
  <tr>
    <td width="33%"><a href="leagues/tdm_league.htm">DF2 TDM League</a></td>
    <td width="33%">Pending</td>
    <td width="34%">TBD</td>
  </tr>
  <tr>
    <td width="33%"><a href="leagues/ad_league.htm">DF2 A&amp;D Series</a></td>
    <td width="33%">Pending</td>
    <td width="34%">TBD</td>
  </tr>
  <tr>
    <td width="33%"><a href="leagues/ctf_league.htm">DF2 CTF League</a></td>
    <td width="33%">Pending</td>
    <td width="34%">TBD</td>
  </tr>
</table>

<p>&nbsp;</p>
<p><b><font face="System" size="1">Copyright © 2000 Squadpage.com. Graphics By <a href="http://www.illusion-design.com/cg/" target="_blank">Clan
Graphics</a></font></b></p>

</body>

</html>
