--16:48:44--  http://www.vru.gov.ua:80/
           => `www.vru.gov.ua/index.html'
Connecting to www.vru.gov.ua:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]

    0K ->

16:48:45 (148.44 KB/s) - `www.vru.gov.ua/index.html' saved [152]

Converting www.vru.gov.ua/index.html... done.

FINISHED --16:48:46--
Downloaded: 152 bytes in 1 files
Converting www.vru.gov.ua/index.html... done.
