--02:03:21--  http://www.norton.sk:80/
           => `www.norton.sk/index.html'
Connecting to www.norton.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 73 [text/html]

    0K ->                                                        [100%]

02:03:22 (71.29 KB/s) - `www.norton.sk/index.html' saved [73/73]

Converting www.norton.sk/index.html... done.

FINISHED --02:03:22--
Downloaded: 73 bytes in 1 files
