--20:10:50--  http://www.lso.ms:80/
           => `www.lso.ms/index.html'
Connecting to www.lso.ms:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 23 [text/html]

    0K ->                                                        [100%]

20:10:50 (7.49 KB/s) - `www.lso.ms/index.html' saved [23/23]

Converting www.lso.ms/index.html... done.

FINISHED --20:10:50--
Downloaded: 23 bytes in 1 files
