<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 3.0//EN" "html.dtd">
<HTML>
<HEAD>
<TITLE>SPOTCHECK Sign-In</TITLE>
</HEAD>
<BODY BACKGROUND="images/backgrnd.gif" BGCOLOR="#fac0de">
<P align=left><A HREF="index.html"><IMG SRC="images/sp2.gif" ALT="SPOTCHECK LOGO" BORDER="0" WIDTH="82" HEIGHT="81"></A>
</P></CENTER>

	<p><h1 align=center>Welcome to SPOTCHECK's DEMO</h1></p>
	<p><h3 align=center>To experience a hands-on demonstration of the SPOTCHECK&reg product enter:</h3>
	<h3 align=center>memberid1 in the Provider LIC# Box</h3>
	<h3 align=center>memberpin1 in the SPOTCHECK PIN# Box</h3>
	<form action="/demo1.phtml" method="POST"><center>
	<table width=75% align=center cellspacing=0 cellpadding=1 border=1>
	<tr>
		<td align=right width=50%>
			Provider LIC #:
		</td>
		<td align=left width=50%>
			<input type="text" name="member_number" value="" size=24>
		</td>
	</tr>
	<tr>
		<td align=right width=50%>
			SPOTCHECK PIN #:
		</td>
		<td align=left width=50%>
			<input type="password" name="pass_word" value="" size=24>
		</td>
	</tr>
	<tr>
		<td align=right width=50%>
			<input type="submit" value="Validate">
		</td>
		<td align=left width=50%>
			<input type=RESET value="Clear Fields">
		</td>
	</tr>
</table>
Forget Your SPOTCHECK PIN Number?  That's O.K., We Can <a href="../support/index.htm">HELP!</a>
</center>
</form>
<h3 align=center>Membership information is available from our <a href="../support/index.htm">Membership FAQ</a>.</h3>
<H5 ALIGN="CENTER">SPOTCHECK&reg is a registered trade mark of Insurance Benefit Spot Check, Inc.</H5>
<H6 ALIGN="CENTER">&copy; 1997. <A HREF="../info/index.htm"> Insurance Benefit Spot Check, Inc.</A> ALL RIGHTS RESERVED.</H6>
</html>
