--12:20:19--  http://psara.iis.gr:80/
           => `psara.iis.gr/index.html'
Connecting to psara.iis.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]

    0K ->

12:20:21 (21.07 KB/s) - `psara.iis.gr/index.html' saved [755]

Loading robots.txt; please ignore errors.
--12:20:21--  http://psara.iis.gr:80/no-robots.txt
           => `psara.iis.gr/no-robots.txt'
Connecting to psara.iis.gr:80... connected!
HTTP request sent, awaiting response... 404 Not found
12:20:22 ERROR 404: Not found.

--12:20:22--  http://psara.iis.gr:80/evil1.jpg
           => `psara.iis.gr/evil1.jpg'
Connecting to psara.iis.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 10,570 [image/jpeg]

    0K -> ..........                                             [100%]

12:20:24 (5.58 KB/s) - `psara.iis.gr/evil1.jpg' saved [10570/10570]

Converting psara.iis.gr/index.html... done.

FINISHED --12:20:24--
Downloaded: 11,325 bytes in 2 files
Converting psara.iis.gr/index.html... done.
