--15:02:57--  http://www.autosector.com.ua:80/
           => `www.autosector.com.ua/index.html'
Connecting to www.autosector.com.ua:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 1,367 [text/html]

    0K -> .                                                      [100%]

15:02:59 (20.86 KB/s) - `www.autosector.com.ua/index.html' saved [1367/1367]

Loading robots.txt; please ignore errors.
--15:02:59--  http://www.autosector.com.ua:80/no-robots.txt
           => `www.autosector.com.ua/no-robots.txt'
Connecting to www.autosector.com.ua:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
15:03:01 ERROR 404: Object Not Found.

--15:03:01--  http://www.autosector.com.ua:80/jnb.swf
           => `www.autosector.com.ua/jnb.swf'
Connecting to www.autosector.com.ua:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
15:03:03 ERROR 404: Object Not Found.

Converting www.autosector.com.ua/index.html... done.

FINISHED --15:03:03--
Downloaded: 1,367 bytes in 1 files
Converting www.autosector.com.ua/index.html... done.
