--17:21:04--  http://www.dehs.bs:80/
           => `www.dehs.bs/index.html'
Connecting to www.dehs.bs:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 606 [text/html]

    0K ->                                                        [100%]

17:21:04 (591.80 KB/s) - `www.dehs.bs/index.html' saved [606/606]

Converting www.dehs.bs/index.html... done.

FINISHED --17:21:04--
Downloaded: 606 bytes in 1 files
