


	








	
	<HTML><HEAD><TITLE>At-Auction  </TITLE></HEAD><BODY BGCOLOR="white" TEXT="black" LINK="blue" ALINK="blue" VLINK="blue">
 



	<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH=600><TR><TD ALIGN=center>	<IMG SRC="images/logo.gif">	</TD></TR></TABLE><TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 WIDTH=600><TR><TD ALIGN=center>	<A HREF="http://www.At-Auction.com/index.cfm"><img src="images/navbarHome.gif" BORDER=0 ALT="Home"></A><A HREF="program/search.cfm"><img src="images/navbarSearch.gif" BORDER=0 ALT="Search"></A><A HREF="https://www.At-Auction.com/program/user.cfm"><img src="images/navbarRegister.gif" BORDER=0 ALT="Register"></A>	<A HREF="seller/helpSeller.cfm"><img src="images/navbarSellers.gif" BORDER=0 ALT="Sellers"></A><A HREF="program/list.cfm"><img src="images/navbarAllLots.gif" BORDER=0 ALT="List All Lots"></A><A HREF="program/editUser.cfm?bidStatus=1"><img src="images/navbarBidStatus.gif" BORDER=0 ALT="Bid Status"></A><A HREF="program/help.cfm"><img src="images/navbarHelp.gif" BORDER=0 ALT="Help"></A>
</TD></TR>	<TR><TD ALIGN=center BGCOLOR="white"><FONT SIZE=5 COLOR="navy" FACE="arial"><B> </B></FONT></TD></TR></TABLE><P>


<TABLE WIDTH="600" BORDER=0><TR>
<TD WIDTH="160" VALIGN="TOP" NOWRAP>
	<BR>
	<FORM METHOD=post ACTION="http://www.At-Auction.com/program/search.cfm">
	<INPUT TYPE=hidden NAME=first VALUE=1>
	<INPUT TYPE=text NAME="searchText" SIZE=15><BR>
	<INPUT TYPE=image NAME="search" SRC="images/buttonSearch.gif" BORDER=0>
	</FORM>

	<P>

	

	<FONT SIZE=4 COLOR="navy" FACE="arial"><B>Categories</B></FONT><BR>
	

	
		
		
		
		
		  <A HREF="category.cfm?categoryID=14">Computers</A> (0)<BR>
	
		
		
		
		
		  <A HREF="category.cfm?categoryID=26">Consumer Electronics</A> (0)<BR>
	
		
		
		
		
		  <A HREF="category.cfm?categoryID=22">Digital Cameras</A> (0)<BR>
	
		
		
		
		
		  <A HREF="category.cfm?categoryID=24">Drives</A> (0)<BR>
	
		
		
		
		
		  <A HREF="category.cfm?categoryID=25">General </A> (0)<BR>
	
		
		
		
		
		  <A HREF="category.cfm?categoryID=23">Macintosh</A> (0)<BR>
	
		
		
		
		
		  <A HREF="category.cfm?categoryID=18">Monitors</A> (0)<BR>
	
		
		
		
		
		  <A HREF="category.cfm?categoryID=21">Peripherals</A> (0)<BR>
	
		
		
		
		
		  <A HREF="category.cfm?categoryID=19">Printers</A> (0)<BR>
	
		
		
		
		
		  <A HREF="category.cfm?categoryID=20">Software</A> (0)<BR>
	
	<FONT SIZE=2><A HREF="program/allCategories.cfm">all categories...</A> (0)</FONT>

	<P>

	
	<FORM NAME=lot ACTION="http://www.At-Auction.com/lot.cfm">
	<FONT COLOR="navy" FACE="arial"><B>Lot: </B></FONT><INPUT TYPE=text NAME="lotID" SIZE=5>
	<INPUT TYPE=image NAME=go SRC="images/go.gif" HEIGHT=25 WIDTH=32 ALIGN=absbottom BORDER=0>
	
	</FORM>

	<P>

	<TABLE WIDTH="160" CELLSPACING="0" CELLPADDING="0">
	
	<TR><TD BGCOLOR="white" ALIGN=center><FONT SIZE=4 COLOR="navy" FACE="arial"><B>Announcements!</B></FONT></TD></TR>
	<TR><TD BGCOLOR="white"><BR>
	
	For a limited time only!No Posting Fees!Unless Bold or Featured Add-Ons are chosen.

	<BR><BR>
	</TD></TR></TABLE>

	<P>

	<TABLE CELLSPACING=0 CELLPADDING=0 WIDTH="160">
	
	<TR><TD BGCOLOR="white" ALIGN=center><FONT SIZE=4 COLOR="navy" FACE="arial"><B>User Features</B></FONT></TD></TR>
	<TR><TD BGCOLOR="white" ALIGN=center NOWRAP>
		<FORM METHOD=post ACTION="http://www.At-Auction.com/program/editUser.cfm">
	
	
	<FONT FACE="Arial" SIZE="2"><STRONG>Username:</STRONG></FONT><BR> 
	<INPUT TYPE=text NAME=username SIZE=15><BR>
	<FONT FACE="Arial" SIZE="2"><STRONG>Password:</STRONG></FONT><BR>
	<INPUT TYPE=password NAME=password SIZE=15><BR>
	
	<INPUT TYPE=image NAME=bidStatus SRC="images/buttonBidStatus.gif" BORDER=0 VSPACE=5><BR>
	
		<INPUT TYPE=image NAME=sellerHome SRC="images/buttonSeller.gif"  BORDER=0 VSPACE=3>
	
	
	</FORM>	
	</TD></TR></TABLE>
</TD>

<TD VALIGN=top>
	<TABLE WIDTH=100% CELLSPACING=0 CELLPADDING=0><TR><TD ALIGN=right>
	
	<FONT SIZE=2 COLOR="navy">  <B>Time:</B> </FONT>
	<FONT SIZE=2>January 16, 2000 / 07:39 PM EDT</FONT>
	
	</TD></TR></TABLE>

	<P>
	 

	<P>

	








	

	
	

	
	

	<P>
	 

	<P>

	
	
	
	

	
	

	<P>
	 

	<P>

	
	

	
	

</TD>
</TR></TABLE>

<P>
 

<P>

<!--
This page generated by Emaze Auction version 2.1, 05/24/1999
copyright 1998-1999 by Emaze Software Corporation
http://www.emaze.com, sales@emaze.com
-->

<P>
</BODY>
</HTML>

	
<!--
This page generated by Emaze Auction version 2.1, 05/24/1999
copyright 1998-1999 by Emaze Software Corporation
http://www.emaze.com, sales@emaze.com
-->

	



































	




	


	









	
		
	

	



	

	
		
		
	



