--06:22:16--  http://www.spsmyj.sk:80/
           => `www.spsmyj.sk/index.html'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,667 [text/html]

    0K -> ....                                                   [100%]

06:22:17 (10.83 KB/s) - `www.spsmyj.sk/index.html' saved [4667/4667]

Loading robots.txt; please ignore errors.
--06:22:17--  http://www.spsmyj.sk:80/no-robots.txt
           => `www.spsmyj.sk/no-robots.txt'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 404 Not Found
06:22:18 ERROR 404: Not Found.

--06:22:18--  http://www.spsmyj.sk:80/hth.gif
           => `www.spsmyj.sk/hth.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 18,312 [image/gif]

    0K -> .......... .......                                     [100%]

06:22:20 (13.13 KB/s) - `www.spsmyj.sk/hth.gif' saved [18312/18312]

--06:22:20--  http://www.spsmyj.sk:80/mirror.htm
           => `www.spsmyj.sk/mirror.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 10,351 [text/html]

    0K -> ..........                                             [100%]

06:22:21 (11.08 KB/s) - `www.spsmyj.sk/mirror.htm' saved [10351/10351]

--06:22:21--  http://www.spsmyj.sk:80/_private/jazyk/france.htm
           => `www.spsmyj.sk/_private/jazyk/france.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 9,431 [text/html]

    0K -> .........                                              [100%]

06:22:22 (12.33 KB/s) - `www.spsmyj.sk/_private/jazyk/france.htm' saved [9431/9431]

--06:22:22--  http://www.spsmyj.sk:80/images/vlajky/France.gif
           => `www.spsmyj.sk/images/vlajky/France.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 3,843 [image/gif]

    0K -> ...                                                    [100%]

06:22:23 (10.48 KB/s) - `www.spsmyj.sk/images/vlajky/France.gif' saved [3843/3843]

--06:22:23--  http://www.spsmyj.sk:80/_private/jazyk/deutsch.htm
           => `www.spsmyj.sk/_private/jazyk/deutsch.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 12,936 [text/html]

    0K -> .......... ..                                          [100%]

06:22:25 (12.08 KB/s) - `www.spsmyj.sk/_private/jazyk/deutsch.htm' saved [12936/12936]

--06:22:25--  http://www.spsmyj.sk:80/images/vlajky/Germany.gif
           => `www.spsmyj.sk/images/vlajky/Germany.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 2,821 [image/gif]

    0K -> ..                                                     [100%]

06:22:26 (8.10 KB/s) - `www.spsmyj.sk/images/vlajky/Germany.gif' saved [2821/2821]

--06:22:26--  http://www.spsmyj.sk:80/_private/jazyk/en.htm
           => `www.spsmyj.sk/_private/jazyk/en.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 4,006 [text/html]

    0K -> ...                                                    [100%]

06:22:27 (9.47 KB/s) - `www.spsmyj.sk/_private/jazyk/en.htm' saved [4006/4006]

--06:22:27--  http://www.spsmyj.sk:80/images/vlajky/anglicka.gif
           => `www.spsmyj.sk/images/vlajky/anglicka.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 3,966 [image/gif]

    0K -> ...                                                    [100%]

06:22:28 (9.88 KB/s) - `www.spsmyj.sk/images/vlajky/anglicka.gif' saved [3966/3966]

--06:22:28--  http://www.spsmyj.sk:80/images/tlacitka/logo.gif
           => `www.spsmyj.sk/images/tlacitka/logo.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 8,016 [image/gif]

    0K -> .......                                                [100%]

06:22:29 (10.45 KB/s) - `www.spsmyj.sk/images/tlacitka/logo.gif' saved [8016/8016]

--06:22:29--  http://www.spsmyj.sk:80/_private/comenius.htm
           => `www.spsmyj.sk/_private/comenius.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 7,669 [text/html]

    0K -> .......                                                [100%]

06:22:31 (10.20 KB/s) - `www.spsmyj.sk/_private/comenius.htm' saved [7669/7669]

--06:22:31--  http://www.spsmyj.sk:80/images/comenius.jpg
           => `www.spsmyj.sk/images/comenius.jpg'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 1,928 [image/jpeg]

    0K -> .                                                      [100%]

06:22:31 (55.38 KB/s) - `www.spsmyj.sk/images/comenius.jpg' saved [1928/1928]

--06:22:31--  http://www.spsmyj.sk:80/_private/oskole.htm
           => `www.spsmyj.sk/_private/oskole.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 3,337 [text/html]

    0K -> ...                                                    [100%]

06:22:32 (9.03 KB/s) - `www.spsmyj.sk/_private/oskole.htm' saved [3337/3337]

--06:22:32--  http://www.spsmyj.sk:80/images/tlacitka/o_Tkole.gif
           => `www.spsmyj.sk/images/tlacitka/o_Tkole.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 1,568 [image/gif]

    0K -> .                                                      [100%]

06:22:33 (90.07 KB/s) - `www.spsmyj.sk/images/tlacitka/o_Tkole.gif' saved [1568/1568]

--06:22:33--  http://www.spsmyj.sk:80/images/tlacitka/skola.gif
           => `www.spsmyj.sk/images/tlacitka/skola.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 17,785 [image/gif]

    0K -> .......... .......                                     [100%]

06:22:35 (13.56 KB/s) - `www.spsmyj.sk/images/tlacitka/skola.gif' saved [17785/17785]

--06:22:35--  http://www.spsmyj.sk:80/_private/stranky.htm
           => `www.spsmyj.sk/_private/stranky.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 821 [text/html]

    0K ->                                                        [100%]

06:22:35 (801.76 KB/s) - `www.spsmyj.sk/_private/stranky.htm' saved [821/821]

--06:22:35--  http://www.spsmyj.sk:80/images/tlacitka/stranky.gif
           => `www.spsmyj.sk/images/tlacitka/stranky.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 2,218 [image/gif]

    0K -> ..                                                     [100%]

06:22:36 (49.23 KB/s) - `www.spsmyj.sk/images/tlacitka/stranky.gif' saved [2218/2218]

--06:22:36--  http://www.spsmyj.sk:80/_private/domov.htm
           => `www.spsmyj.sk/_private/domov.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 1,922 [text/html]

    0K -> .                                                      [100%]

06:22:37 (53.63 KB/s) - `www.spsmyj.sk/_private/domov.htm' saved [1922/1922]

--06:22:37--  http://www.spsmyj.sk:80/images/tlacitka/domov.gif
           => `www.spsmyj.sk/images/tlacitka/domov.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 2,233 [image/gif]

    0K -> ..                                                     [100%]

06:22:37 (48.46 KB/s) - `www.spsmyj.sk/images/tlacitka/domov.gif' saved [2233/2233]

--06:22:37--  http://www.spsmyj.sk:80/_private/zaujimave.htm
           => `www.spsmyj.sk/_private/zaujimave.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 6,028 [text/html]

    0K -> .....                                                  [100%]

06:22:38 (12.61 KB/s) - `www.spsmyj.sk/_private/zaujimave.htm' saved [6028/6028]

--06:22:38--  http://www.spsmyj.sk:80/images/tlacitka/Zaujimave.gif
           => `www.spsmyj.sk/images/tlacitka/Zaujimave.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 2,468 [image/gif]

    0K -> ..                                                     [100%]

06:22:39 (43.82 KB/s) - `www.spsmyj.sk/images/tlacitka/Zaujimave.gif' saved [2468/2468]

--06:22:39--  http://www.spsmyj.sk:80/_private/odbory.htm
           => `www.spsmyj.sk/_private/odbory.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 1,212 [text/html]

    0K -> .                                                      [100%]

06:22:40 (1.16 MB/s) - `www.spsmyj.sk/_private/odbory.htm' saved [1212/1212]

--06:22:40--  http://www.spsmyj.sk:80/images/tlacitka/odbory.gif
           => `www.spsmyj.sk/images/tlacitka/odbory.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 2,413 [image/gif]

    0K -> ..                                                     [100%]

06:22:40 (45.32 KB/s) - `www.spsmyj.sk/images/tlacitka/odbory.gif' saved [2413/2413]

--06:22:40--  http://www.spsmyj.sk:80/_private/tvorbawww.htm
           => `www.spsmyj.sk/_private/tvorbawww.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 1,090 [text/html]

    0K -> .                                                      [100%]

06:22:41 (1.04 MB/s) - `www.spsmyj.sk/_private/tvorbawww.htm' saved [1090/1090]

--06:22:41--  http://www.spsmyj.sk:80/images/tlacitka/www.gif
           => `www.spsmyj.sk/images/tlacitka/www.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 2,124 [image/gif]

    0K -> ..                                                     [100%]

06:22:41 (51.86 KB/s) - `www.spsmyj.sk/images/tlacitka/www.gif' saved [2124/2124]

--06:22:41--  http://www.spsmyj.sk:80/_private/pomaturitne.htm
           => `www.spsmyj.sk/_private/pomaturitne.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 13,132 [text/html]

    0K -> .......... ..                                          [100%]

06:22:43 (11.12 KB/s) - `www.spsmyj.sk/_private/pomaturitne.htm' saved [13132/13132]

--06:22:43--  http://www.spsmyj.sk:80/images/tlacitka/pomaturitne.gif
           => `www.spsmyj.sk/images/tlacitka/pomaturitne.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 2,560 [image/gif]

    0K -> ..                                                     [100%]

06:22:44 (43.10 KB/s) - `www.spsmyj.sk/images/tlacitka/pomaturitne.gif' saved [2560/2560]

--06:22:44--  http://www.spsmyj.sk:80/_private/kontakt.htm
           => `www.spsmyj.sk/_private/kontakt.htm'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 2,138 [text/html]

    0K -> ..                                                     [100%]

06:22:45 (43.50 KB/s) - `www.spsmyj.sk/_private/kontakt.htm' saved [2138/2138]

--06:22:45--  http://www.spsmyj.sk:80/images/tlacitka/kontakt.gif
           => `www.spsmyj.sk/images/tlacitka/kontakt.gif'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 1,628 [image/gif]

    0K -> .                                                      [100%]

06:22:46 (99.37 KB/s) - `www.spsmyj.sk/images/tlacitka/kontakt.gif' saved [1628/1628]

--06:22:46--  http://www.spsmyj.sk:80/_vti_bin/fpcount.exe/?Page=mirror.htm%7CImage=3
           => `www.spsmyj.sk/_vti_bin/fpcount.exe/?Page=mirror.htm|Image=3'
Connecting to www.spsmyj.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: unspecified [image/gif]

    0K ->

06:22:47 (144.53 KB/s) - `www.spsmyj.sk/_vti_bin/fpcount.exe/?Page=mirror.htm|Image=3' saved [148]

Converting www.spsmyj.sk/mirror.htm... done.
Converting www.spsmyj.sk/index.html... done.

FINISHED --06:22:47--
Downloaded: 152,771 bytes in 30 files
Converting www.spsmyj.sk/index.html... done.
Converting www.spsmyj.sk/mirror.htm... done.
Converting www.spsmyj.sk/_private/jazyk/france.htm... done.
Converting www.spsmyj.sk/_private/jazyk/deutsch.htm... done.
Converting www.spsmyj.sk/_private/jazyk/en.htm... done.
Converting www.spsmyj.sk/_private/comenius.htm... done.
Converting www.spsmyj.sk/_private/oskole.htm... done.
Converting www.spsmyj.sk/_private/stranky.htm... done.
Converting www.spsmyj.sk/_private/domov.htm... done.
Converting www.spsmyj.sk/_private/zaujimave.htm... done.
Converting www.spsmyj.sk/_private/odbory.htm... done.
Converting www.spsmyj.sk/_private/tvorbawww.htm... done.
Converting www.spsmyj.sk/_private/pomaturitne.htm... done.
Converting www.spsmyj.sk/_private/kontakt.htm... done.
