<HTML><HEAD><TITLE>New Found Glory : news and updates</TITLE><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1"><META name="copyright" content="&copy;2000 MCA Records"><META name="publisher" content="Universal Music Group"><META name="author" content="Boogaloo Poe"><META name="description" content="The latest news about punk upstars New Found Glory (NFG) on Drive Thru / MCA Records (home of Blink 182 and Fenix TX)."><META name="keywords" content="new found glory, NFG, drive thru, punk rock, blink 182, fenix tx, mca records,drive thru records, Nothing Gold Can Stay, From The Screen To Your Stereo"><!-- new found glory, NFG, drive thru, punk rock, blink 182, fenix tx, mca records,drive thru records, Nothing Gold Can Stay, From The Screen To Your Stereo --><!-- ImageReady Preload Script (homenfg.PSD) --><link rel="stylesheet" href="/site.css"></HEAD><BODY BGCOLOR="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"><TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 width="223">  <TR>    <TD COLSPAN=3> <IMG SRC="images/spacer.gif" WIDTH=223 HEIGHT=16 alt=""></TD>    <TD> <IMG SRC="images/spacer.gif" WIDTH=1 HEIGHT=16 alt=""></TD>  </TR>  <TR>    <TD ROWSPAN=8> <IMG SRC="images/spacer.gif" WIDTH=9 HEIGHT=392 alt=""></TD>    <TD> <IMG NAME="news_13" SRC="images/news_13.gif" WIDTH=25 HEIGHT=25 alt="NFG loves classic Atari"></TD>    <TD ROWSPAN=2> <IMG SRC="images/spacer.gif" WIDTH=189 HEIGHT=32 alt=""></TD>    <TD> <IMG SRC="images/spacer.gif" WIDTH=1 HEIGHT=25 alt=""></TD>  </TR>  <TR>    <TD> <IMG SRC="images/spacer.gif" WIDTH=25 HEIGHT=7 alt=""></TD>    <TD> <IMG SRC="images/spacer.gif" WIDTH=1 HEIGHT=7 alt=""></TD>  </TR>  <TR>    <TD COLSPAN=2 ROWSPAN=6 align="left" valign="top">      

	<!-- NP v3.7.5 -->

	<a name="newsitem982361852,32577,"></a><span class="date">2.16.2001</span><br> <span class="headline">NFG Contest At DCN</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">Our friends at <a href="http://www.dcn.com/" target="contest">Digital Club Network</a> have NFG as their featured spotlight. There is also a contest up and running.  Enter to win autographed posters of the band as well as CDs and more! For more information, click <a href="http://www.dcn.com/contests/index_newfoundglory.html" target="contest">here</a>. The contest ends March 2, 2001.</span><br><br>
<a name="newsitem982294176,70018,"></a><span class="date">2.15.2001</span><br> <span class="headline">"Hit Or Miss" Is Online Now</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy"><p align="center"><A href="rtsp://boss.2.navisitestreaming.net/real/2/mca/MCA/newfoundglory/28-300_nfg_hitormissvid.smi"><img src="http://www.newfoundglory.com/images/videogirl.jpg" align="center"></A></p><br><br>Here it is, the video for "<A href="rtsp://boss.2.navisitestreaming.net/real/2/mca/MCA/newfoundglory/28-300_nfg_hitormissvid.smi">Hit Or Miss</A>" in <A href="http://www.real.com" target="_blank">RealVideo</A> format. Check it.</span><br><br>
<a name="newsitem981589612,57293,"></a><span class="date">2.7.2001</span><br> <span class="headline">NFG Message to the Fans at the Video Shoot.</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">You can access the message by clicking <a href="http://www.newfoundglory.com/letter/letter.htm" target="_blank">here</a>.</span><br><br>
<a name="newsitem981418399,63512,"></a><span class="date">2.5.2001</span><br> <span class="headline">Show Time Details</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">So you can plan your night, here ya go.<br><br>2/15 Atlanta GA on at 9:30, doors at 7<br>2/17 Washington DC on at 6:45 doors at 4<br>2/21 Pittsburgh PA on at 7:45 doors at 6</span><br><br>
<a name="newsitem980801707,26543,"></a><span class="date">1.29.2001</span><br> <span class="headline">NFG merchandise available online...</span><br>
<span class="byline">Posted by NewFoundGlory</span><br>
<span class="bodycopy">here's one for all of you that are wondering where you can find our t-shirts, cd's, etc. on the web.  go to the <A HREF="http://www.drivethrurecords.com" TARGET="_blank">drive-thru records website</A>, and click on "store"...there you will find tons of NFG merch, as well as other great drive-thru records merch, and some very hard to get items...be sure to also check out the website, where you can find info on all of the great bands on drive-thru records!</span><br><br>
<a name="newsitem980796974,17230,"></a> <span class="headline">New Found Glory on the "Ten Taxi"...</span><br>
<span class="byline">Posted by NewFoundGlory</span><br>
<span class="bodycopy">hey...for all you people here in south florida...be sure to tune in to channel 10 (WPLG) Eyewitness News tomorrow, which is Tuesday, January 30th, at 5:30.  New Found Glory will be featured in a segment titled "The Ten Taxi".  Oh, and in case you don't know, channel 10 is our south florida ABC affiliate.  Enjoy!</span><br><br>
<a name="newsitem980560168,54809,"></a><span class="date">1.26.2001</span><br> <span class="headline">New Found Glory On The Radio</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">Want to hear NFG on your local radio station or do you want to tell stations nationwide to play NFG?  Well, click <a href="http://www.mcarecords.com/radioalt.html" target="_blank">here </a> for a list of radio stations across the United States with their request lines.</span><br><br>
<a name="newsitem980559576,89110,"></a> <span class="headline">New Found Glory's Punk Ass Club</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">In case you didn't know there is an <b>Official New Found Glory Yahoo Club.</b> Voice chat with other fans, post messages, pictures and calendar events.  THIS IS YOUR CLUB to show your love for New Found Glory.  All you have to do is click <a href="http://clubs.yahoo.com/clubs/newfoundgloryspunkassclub" target="_blank">here</a> to join.  </span><br><br>
<a name="newsitem980534694,95488,"></a> <span class="headline">Ian's Thoughts On The Term, "Sell Out"</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">Read what Ian had to say about this on-going debate in RivalMag.com's <a href="http://www.rivalmag.com/Ian.php" target="_blank">Artist's Speak Out</a> section.</span><br><br>
<a name="newsitem979940868,83196,"></a><span class="date">1.19.2001</span><br> <span class="headline">Want To be In A New Found Glory Video?</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">New Found Glory are shooting the video for the single, &#8220;Hit or Miss&#8221; on Wednesday, January 24, 2001 and they need extras for the shoot. You will not be paid for your time, but NFG appreciates the support of their fans and hey, it's a chance to have fun and be in a music video!<br><br>Here&#8217;s what you need to do if you are in the Los Angeles area:<br><br>Fill out and sign the release form (click <A HREF="http://www.newfoundglory.com/waiver.pdf" TARGET="_blank">here</A> to get the release form &#8211; it&#8217;s a PDF Format so you&#8217;ll need <A HREF="http://www.adobe.com/products/acrobat/readstep2.html" TARGET="_blank">Adobe Acrobat</A> to read it. If you are under 18 you need your parent&#8217;s signature).  Bring the release form with you to the shoot.<br><br>The location is at: <br><br>Sun Chemical Bldg.<br>590 South Santa Fe<br>Los Angeles, CA 90013<br><br>Click <A HREF="http://www.mapquest.com/cgi-bin/ia_find?link=btwn%2Ftwn-map_results&random=884&event=find_search&uid=uus204vat764judd%3A855f8xuw2&SNVData=3mad3-9.fy%2528at2u67_%2529f82u67%253bah7-%253d%253a%2528_%253d%253abad672%253d%253d1su672%253d0%2Crb%253b7&country=United+States&address=590+South+Santa+Fe&city=Los+Angeles&State=CA&Zip=90013&Find+Map=Get+Map" TARGET="_blank">here</A> for directions via <A HREF="http://www.mapquest.com" TARGET="_blank">Mapquest</A>.<br><br>The approximate time for participants will be from 4:00PM - 10:00PM so, please arrive by 4:00PM.  (The shoot could go as late as midnight but the goal is to be done by 10:00PM.) Dress casual, as you would for a New Found Glory show and please, no clothing with logos.</span><br><br>
<a name="newsitem979772677,75823,"></a><span class="date">1.17.2001</span><br> <span class="headline">Directions To The Benefit Show</span><br>
<span class="byline">Posted by NewFoundGlory</span><br>
<span class="bodycopy">Hey everyone...here's directions to the show on January 19, 2001 at North Community Park in Coral Springs.<br><br>FROM THE SOUTH:<br>Take I-75 North...continue onto the Sawgrass Expressway (SR 869) North...exit on Coral Ridge Dr. and turn right off of the exit...turn left at the first light (Westview Dr.)...pass through the next light (Coral Springs Dr.) and the park entrance will be on the left.<br><br>FROM THE NORTH/EAST:<br>Take the Sawgrass Expressway (SR 869) South...exit on University Dr. and turn left off of the exit...turn right at the first light (Westview Dr.)...the park entrance is about a half-mile down on the right side, before the next light (Coral Springs Dr.)<br><br>The other bands playing the show are Where Fear and Weapons Meet, Junction 18, and Dashboard Confessional.  The show starts at 7PM, and will be over by 11PM.  Tickets are $10 or $8 with the donation of two(2) cans of food.  Proceeds will be going to the Broward Gold Coast Down Syndrome Organization, so come out and show your support!</span><br><br>
<a name="newsitem979535331,83068,"></a><span class="date">1.14.2001</span><br> <span class="headline">Zeta's Top 7 at 7, Part 2</span><br>
<span class="byline">Posted by NewFoundGlory</span><br>
<span class="bodycopy">We can't thank you guys enough...last Wednesday, because of each and everyone of you who requested "hit or miss" on 94.9 WZTA, we were voted the #1 song on their Top 7 at 7!  And, we repeated as #1 on Thursday as well!  We never expected it to happen, but somehow it did!  And, we'd love for it to happen again...on Friday we moved down a few spots, but we're sure that this can happen again if everyone requests "hit or miss" a few more times.  Call in your requests at 1-800-749-9490 (toll-free), or email your requests <A HREF="http://www.zetarocks.com/zetawillrock/html/top77_request.shtml" TARGET="_blank">here</A>.  Every time we're on this countdown a whole new crowd is exposed to our music.  And we want to prove to south Florida that punk rock is popular and deserves to get more recognition than it does.<br><br>So, thanks again, and please vote!<br><br>By the way, you can listen to the top 7 at 7 weekdays starting at 7PM.  Go to WZTA's <A HREF="http://www.zetarocks.com" TARGET="_blank">website</A> to listen online from anywhere in the world!</span><br><br>
<a name="newsitem979534381,45092,"></a> <span class="headline">New Tour Dates Explained</span><br>
<span class="byline">Posted by NewFoundGlory</span><br>
<span class="bodycopy">if you haven't noticed, the tour dates have updated.  you can view them on the <A HREF="http://www.newfoundglory.com/events1.asp">dates</A> page.  however, they don't give the details about the tours and/or shows, so here they are...<br><br>the show on January 19th is a benefit show for the Broward Gold Coast Down Syndrome Organization...it starts at 7PM and admission is either $10 or $8 if you donate two cans of food at the gate.  get there early, though, because tickets will only be sold at the gate!<br><br>the concert on January 31st is a radio show for <A HREF="http://www.whfs.com/home/index.html" TARGET="_blank">WHFS</A> in Washington, D.C.  tickets are on sale now, and are only $1 or something ridiculously cheap like that.  Listen to <A HREF="http://www.whfs.com/home/index.html" TARGET="_blank">WHFS</A> for more details about the show...<br><br>the dates starting on February 15th in atlanta will be with less than jake, anti-flag, and teen idols.  we're getting the opportunity to tour with one of our favorite bands again, less than jake, and we're so excited for these shows!  tickets are already on sale for a bunch of these shows, so make sure to get them early because they will probably run out quick!<br><br>so...hopefully that little explanation helped...click <A HREF="http://www.newfoundglory.com/events1.asp">here</A> to view the full list of dates.  please try and come out to one or more of our shows...show your support!  and to everyone who has already or will be seeing us soon, thanks so much!  you guys are the real reason why we're up there every night...your energy gives us energy...hope to see you soon!</span><br><br>
<a name="newsitem979115946,6854,"></a><span class="date">1.10.2001</span><br> <span class="headline">Zeta's Top 7 at 7</span><br>
<span class="byline">Posted by NewFoundGlory</span><br>
<span class="bodycopy">For the last three weeks, "hit or miss" has been featured on 94.9 Zeta's Top 7 at 7 here in south florida.  The highest we have been on the countdown is #3, but we'd love to see it at #1!  Call in your requests at 1-800-749-9490, or click <a href="http://www.zetarocks.com/zetawillrock/html/top77_request.shtml" TARGET="_blank">here</a> to email the request.  Everyone can vote, no matter where you live, as many times as you want.  You can even listen to the station through their <a href="http://www.zetarocks.com" TARGET="_blank">website</a>.  Tune in weekday nights at 7PM Eastern Time to hear the show.  <br><br>And a very big thank you to everyone who has been or will be calling and emailing your requests in...we love you guys!<br></span><br><br>
<a name="newsitem978659422,14553,"></a><span class="date">1.4.2001</span><br> <span class="headline">Benefit Show in Coral Springs</span><br>
<span class="byline">Posted by NewFoundGlory</span><br>
<span class="bodycopy">We're playing a benefit show for the Broward Gold Coast Down Syndrome Organization on January 19th in Coral Springs, Florida.  It will be held at North Community Park (Westview Dr. and Coral Springs Dr.) and will run from 7PM until 11PM.  Tickets will only be sold at the gate, and will be either $10 or $8 with the donation of two cans of food.  This show is going to be for a great cause, so please <br>come out and show your support!</span><br><br>
<a name="newsitem977361170,16039,"></a><span class="date">12.20.2000</span><br> <span class="headline">Swatch Boardercross World Tour</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">New Found Glory and <a href="http://www.fenixtx.com" target="_blank">Fenix*TX</a> will perform at the Swatch Boardercross World Tour show at Buttermilk Mountain - Aspen Colorado on January 13, 2001.  The show will be broadcast on the <a href="http://www.usanetwork.com/splash.html" target="_blank">USA Network</a> - airtime and date to be determined.</span><br><br>
<a name="newsitem976217082,84090,"></a><span class="date">12.7.2000</span><br> <span class="headline">Thoughts on Britney, N'Sync, and more . . .</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">Whats your fav. Britney song? <br>Ian: (Thinking) I like "Born To Make You Happy" on the first record. I think its called "When Your Eyes Say it" on the new record and "Don't Let Me Be The Last To Know." <br>Jordan: I think I'm liking Mandy Moore more than Britney Spears.<br><br> For more of NFG's thoughts on the important issues of the day check out this interview at <a href="http://www.rivalmag.com/interviews/nfg.php" target="_blank">RivalMag.com</a></span><br><br>
<a name="newsitem975955246,60582,"></a><span class="date">12.4.2000</span><br> <span class="headline">New Year's Eve</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">New Year's Eve show at Cox Arena, San Diego, California.....blink-182, Weezer, New Found Glory.</span><br><br>
<a name="newsitem973275745,92241,"></a><span class="date">11.3.2000</span><br> <span class="headline">NFG Bulletin Board</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">It's up and some of you already found it! Sign up and post away. Click <A href="http://www.mcarecords.com/bbs/FORUM.asp?FORUM_ID=11&CAT_ID=4&Forum_Title=New+Found+Glory" OnClick="window.open ('','image','toolbar=1,location=0,directories=0,status=0,menubar=0,scrollbars=1,width=580,height=440 resizable=0');" target="image">here</a</span><br><br>
<a name="newsitem973275601,75691,"></a> <span class="headline">New Headline Tour Dates </span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">Starting November 28th in Mesa, AZ NFG will be headlining shows with Midtown & Dashboard. They'll be headed through Texas to Atlanta, then up the coast and back on down til December 17th. Check the <a href="http://www.newfoundglory.com/events1.asp" target="right">Dates</a>  section for all the dates</span><br><br>
<a name="newsitem973218115,81902,"></a><span class="date">11.2.2000</span><br> <span class="headline">NFG on Nirve TV</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">Check out the Nirve TV interview in Real Video by clicking <A href="http://www.nirvemedia.com/newfoundglorytv/index.html" OnClick="window.open ('','image','toolbar=0,location=0,directories=0,status=0,menubar=0,scrollbars=0,width=288,height=286 resizable=0');" target="image">here</a></span><br><br>
<a name="newsitem970525950,12954,"></a><span class="date">10.2.2000</span><br> <span class="headline">Touring with Fenix TX </span><br>
<span class="byline">Posted by DriveThru</span><br>
<span class="bodycopy">After just finishing extensive touring with Face to Face and Saves the Day, NFG begins on the 4th of October in Va with Fenix Tx, so check the dates section to see when they are coming to a city near you!</span><br><br>
<a name="newsitem969330759,86492,"></a><span class="date">9.18.2000</span><br> <span class="headline">Live Shows on the Web</span><br>
<span class="byline">Posted by DriveThru</span><br>
<span class="bodycopy">If you still haven't caught NFG live on the web yet, you still haven't missed your chance.  Tune into <a href ="http://www.dcn.com"> DCN.COM </a> on Nov. 8, 9, 10, and December 16 to watch some great shows. For the times and more details check out the website at <a href ="http://www.dcn.com"> DCN.COM </a></span><br><br>
<a name="newsitem967509500,34170,"></a><span class="date">8.28.2000</span><br> <span class="headline">Nirve TV Interview</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">There will be a cool interview with the band up on <a href="http://www.nirvetv.com" target="NirveTV">http://www.nirvetv.com</a> very soon. Keep checkin' back!</span><br><br>
<a name="newsitem967509261,24831,"></a> <span class="headline">Hittin' The Road</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">New Found Glory is going all over the country with Face To Face,  Alkaline Trio, and Saves The Day. It's a great line up, so don't miss it. Dates are in the <a href="http://www.newfoundglory.com/events1.asp" target="right">Dates</a>  section. Duh!</span><br><br>
<a name="newsitem967509241,69747,"></a> <span class="headline">New Album Instores September 26th!</span><br>
<span class="byline">Posted by MCA</span><br>
<span class="bodycopy">The self titled new album from New Found Glory hits stores on September 26th. Sign up on the emailing list below and we'll remind ya'! Check out new sounds from the album in the <a href="http://www.newfoundglory.com/music1.asp" target="right">Music</a> section.</span><br><br>
 <IMG SRC="images/news_23.gif" WIDTH=214 HEIGHT=5 alt=""></TD>    <TD> <IMG SRC="images/spacer.gif" WIDTH=1 HEIGHT=25 alt=""></TD>  </TR>  <TR>    <TD> <IMG SRC="images/spacer.gif" WIDTH=1 HEIGHT=6 alt=""></TD>  </TR>  <TR>    <TD> <IMG SRC="images/spacer.gif" WIDTH=1 HEIGHT=25 alt=""></TD>  </TR>  <TR>    <TD> <IMG SRC="images/spacer.gif" WIDTH=1 HEIGHT=12 alt=""></TD>  </TR>  <TR>    <TD> <IMG SRC="images/spacer.gif" WIDTH=1 HEIGHT=236 alt=""></TD>  </TR>  <TR>    <TD> <IMG SRC="images/spacer.gif" WIDTH=1 HEIGHT=56 alt=""></TD>  </TR></TABLE><!-- End ImageReady Slices --></BODY></HTML>