--12:17:09--  http://www.brama.sk:80/
           => `www.brama.sk/index.html'
Connecting to www.brama.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 131 [text/html]

    0K ->                                                        [100%]

12:17:10 (63.96 KB/s) - `www.brama.sk/index.html' saved [131/131]

Loading robots.txt; please ignore errors.
--12:17:10--  http://www.brama.sk:80/no-robots.txt
           => `www.brama.sk/no-robots.txt'
Connecting to www.brama.sk:80... connected!
HTTP request sent, awaiting response... 404 Not Found
12:17:10 ERROR 404: Not Found.

--12:17:10--  http://www.brama.sk:80/hitech.gif
           => `www.brama.sk/hitech.gif'
Connecting to www.brama.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 23,352 [image/gif]

    0K -> .......... .......... ..                               [100%]

12:17:13 (14.31 KB/s) - `www.brama.sk/hitech.gif' saved [23352/23352]

Converting www.brama.sk/index.html... done.

FINISHED --12:17:13--
Downloaded: 23,483 bytes in 2 files
Converting www.brama.sk/index.html... done.
