--11:22:27--  http://eus.eurosoft.od.ua:80/
           => `eus.eurosoft.od.ua/index.html'
Connecting to eus.eurosoft.od.ua:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 237 [text/html]

    0K ->                                                        [100%]

11:22:28 (231.45 KB/s) - `eus.eurosoft.od.ua/index.html' saved [237/237]

Loading robots.txt; please ignore errors.
--11:22:28--  http://eus.eurosoft.od.ua:80/no-robots.txt
           => `eus.eurosoft.od.ua/no-robots.txt'
Connecting to eus.eurosoft.od.ua:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
11:22:29 ERROR 404: Object Not Found.

--11:22:29--  http://eus.eurosoft.od.ua:80/enter.html
           => `eus.eurosoft.od.ua/enter.html'
Connecting to eus.eurosoft.od.ua:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 1,189 [text/html]

    0K -> .                                                      [100%]

11:22:31 (1.13 MB/s) - `eus.eurosoft.od.ua/enter.html' saved [1189/1189]

Converting eus.eurosoft.od.ua/enter.html... done.
Converting eus.eurosoft.od.ua/index.html... done.

FINISHED --11:22:31--
Downloaded: 1,426 bytes in 2 files
Converting eus.eurosoft.od.ua/index.html... done.
