<HTML><HEAD>	<TITLE>KoRnWeb.com - Not Found</TITLE><META NAME="description" CONTENT="Join the Korn Kommunity! Korn Lyrics, Tabs, Audio, Downloads, Polls, KoRnWeb Friends Net Work, Discussion Forums and Much Much More!">
<META NAME="keywords" CONTENT="Korn, Follow the Leader, Life is Peachy, Hard Rock, Heavy Rock, Music, Got the Life, All in the Family, Guitar Tab, Lyrics, Downloads, Mp3, Desktop Themes, Screen Savers, KornWeb, Korn Kommunity, Jonathan Davis, HIV, James Scaffer, Munky, Brian Welch, Head, Reginald Arvizu, Fieldy, David Silveria, Freak on a Leash, Ball Tongue, Twist, Kill You, I Can Remember, Shoots and Ladders, Who Then Now, ADIDAS">
<META NAME="author" CONTENT="Copyright 1998, KoRnWeb">

<STYLE TYPE="text/css">
<!--
A:link {text-decoration: none; color:#FFFFEA; }
A:visited {text-decoration: none; color:#FFFFEA; }
A:active {text-decoration: none; color: #FFFFEA; }
-->
</STYLE>

<!-- LAUNCH OMG BANNER TAG  http://www.launch.com/omg -->
<SCRIPT LANGUAGE="JavaScript">
<!--
var axel = Math.random() + "";
var ord = axel * 1000000000000000000;
//-->
</SCRIPT>
<!-- end random # -->

</HEAD>

<BODY bgcolor="Black" background="/images/bkgrd.gif" text="#FFFFEA" link="#FFFFEA" vlink="#FFFFEA" alink="#FFFFEA">

<table width="750" border="0" cellspacing="0" cellpadding="0">
<tr>
	<td width="180" valign="top">
&nbsp; &nbsp; <img src="/images/korn_logo.gif" width=130 height=83 border=0 alt="Korn Logo">

<P><table border="0" cellspacing="0" cellpadding="0" width="180">
<TR>
<td width="15"></td>
<TD width="165" valign="top">


<font face="arial" size="2"><B>
<a href="http://www.kornweb.com/home.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">KoRnWeb Home</span></A>
<br><a href="http://www.kornweb.com/subscribe.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Subscribe to Korn</span></A>
<br><a href="http://www.kornweb.com/news/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">News &amp; Rumours</span></A>
<br><a href="http://www.kornweb.com/mailbag/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Kornweb Mailbag</span></A>
<br><a href="http://www.kornweb.com/faqs.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Korn FAQs</span></A>
<br><a href="http://www.kornweb.com/kornography/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Kornography</span></A>
<br><a href="http://www.kornweb.com/tour/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Korn Tour Info</span></A>
<br><a href="http://www.kornweb.com/downloads/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Korn Downloads</span></A>
<br><a href="http://www.kornweb.com/fiction/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Korn Fiction</span></A>
<br><a href="http://www.kornweb.com/articles/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Articles & Interviews</span></A>
<br><a href="http://www.kornweb.com/tab/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Guitar/Bass/Drum Tab</span></A>
<br><a href="http://www.kornweb.com/wwwbbs/config.pl"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Discussion Forum</span></A>
<br><a href="http://www.kornweb.com/chat/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Chat Forum</span></A>
<br><a href="http://www.kornweb.com/kampaign/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Korn Kampaign Pics</span></A>
<br><a href="http://www.kornweb.com/korn/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Korn Name Theories</span></A>
<br><a href="http://www.kornweb.com/links/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Korn Links</span></A>
<br><a href="http://www.kornweb.com/kornfans/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Fans of Korn</span></A>
<br><a href="http://www.kornweb.com/email/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Email Kornweb</span></A>

<p><u>Issues Coverage</u>
<BR><img src="/images/space.gif" width=1 height=4 border=0 alt="Space Invader"><br><font size="-2">
<a href="http://www.kornweb.com/issues/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Full Coverage</span></A>
<BR><a href="http://www.kornweb.com/issues/lyrics.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Issues Lyrics</span></A>
<BR><a href="http://www.kornweb.com/issues/review.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Issues Review</span></A>
<!-- <BR><a href="http://www.kornweb.com/issues/reviews/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Post A Review</span></A> -->
<BR><a href="http://www.kornweb.com/covers/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Cover Designs</span></A></font><br>

<p><u>KoRn Lyrics</u>
<BR><img src="/images/space.gif" width=1 height=4 border=0 alt="Space Invader"><br><font size="-2">
<a href="http://www.kornweb.com/issues/lyrics.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Issues</span></A>
<BR><a href="http://www.kornweb.com/ftl.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Follow the Leader</span></A>
<BR><a href="http://www.kornweb.com/lip.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Life is Peachy</span></A>
<BR><a href="http://www.kornweb.com/korn.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Korn</span></A>
<BR><a href="http://www.kornweb.com/b-sides.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Rare/B-sides</span></A></font><br>

<p><u>Song Meanings</u>
<BR><img src="/images/space.gif" width=1 height=4 border=0 alt="Space Invader"><br><font size="-2">
<a href="http://www.kornweb.com/issues/meanings/index.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Issues</span></A>
<BR><a href="http://www.kornweb.com/meanings/ftl.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Follow the Leader</span></A>
<BR><a href="http://www.kornweb.com/meanings/lip.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Life is Peachy</span></A>
<BR><a href="http://www.kornweb.com/meanings/korn.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Korn</span></A>
</font><br>

<p><u>Biographies</u>
<BR><img src="/images/space.gif" width=1 height=4 border=0 alt="Space Invader"><br><font size="-2">
<a href="http://www.kornweb.com/biography/bw.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Brian "Head" Welch</span></A>
<BR><a href="http://www.kornweb.com/biography/ds.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">David Silveria</span></A>
<BR><a href="http://www.kornweb.com/biography/js.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">James "Munky" Shaffer</span></A>
<br><a href="http://www.kornweb.com/biography/jd.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Jonathan "HIV" Davis</span></A>
<br><a href="http://www.kornweb.com/biography/ra.phtml"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Reginald "Fieldy" Arvizu</span></A>
</font><br>

<p><u>Shoutweb Sites</u>
<BR><img src="/images/space.gif" width=1 height=4 border=0 alt="Space Invader"><br><font size="-2">
<a href="http://www.kornweb.com"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Kornweb</span></A>
<BR><a href="http://www.slipknotweb.com"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Slipknotweb</span></A>
<BR><a href="http://www.bizkitweb.com"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Bizkitweb</span></A>
<br><a href="http://www.mansonweb.com"><SPAN style="color : #FFFFEA" onmouseover="this.style.color='#F78439'" onmouseout="this.style.color='#FFFFEA'">Mansonweb</span></A><br>

<p><a href="http://www.kornweb.com/clicktrack.phtml"><img src="/images/launch.gif" width=120 height=60 border=0 alt="KoRnWeb Banner"></a>

<img src="http://www.kornweb.com/hitcount/hitcounter.pl" border=0 alt="" width=1 height=1>
<!-- <IMG SRC="http://www.kornweb.com/ads/ads.pl?page=00" width="1" height="1" border=0> -->
</B></font>
</TD></TR></TABLE>

</td><TD valign="top" width="470">
<!-- START OMG BANNER -->
<SCRIPT LANGUAGE="JavaScript">

<!--
document.writeln("<IFRAME SRC='http://ad.doubleclick.net/adi/launch.kornweb/;sz=468x60;ord=" + ord +"?' WIDTH=468 HEIGHT=60 ALIGN=CENTER MARGINWIDTH=0 MARGINHEIGHT=0 HSPACE=0 VSPACE=0 FRAMEBORDER=0 SCROLLING=NO></IFRAME>");
document.writeln("<SCR" + "IPT language='JavaScript1.1' SRC='http://ad.doubleclick.net/adj/launch.kornweb/;abr=!ie;abr=!webtv;sz=468x60;ord=" + ord +"?'></SCR" + "IPT>");
//-->

</SCRIPT></SCRIPT>

<NOSCRIPT>
<A HREF="http://ad.doubleclick.net/jump/launch.kornweb/;sz=468x60" target="_top">
<IMG SRC="http://ad.doubleclick.net/ad/launch.kornweb/;sz=468x60" border=0 width="468" height="60"></a>
</NOSCRIPT>
<!-- END OMG BANNER -->

<P><table border="0" cellspacing="0" cellpadding="0" width="450">
<tr>
	<td width="200"><img src="/images/kk-logo.gif" width=212 height=67 border=0 alt="Visit the Korn Kommunity!"></td>
	<td width="50"></TD>
	<td valign=top width="200"><center>
<img src="../images/kornweb-logo1.gif" border=0 alt="www.kornweb.com"><br><font face="arial" size="-2">Error 404 File Not Found</font></center></td></tr></table><font face="arial" size="2"><P><img src="/images/line.gif" width=469 height=2 border=0 alt="Line"><P>
Sorry but the file you are trying to access has been moved or no longer exists on this server.

<P>Please return to <a href="../index.phtml" STYLE="color:#CA0F00;">KoRnWeb</A>.

<P><img src="../images/space.gif" width=1 height=350><P>
<P><img src="/images/line.gif" width=469 height=2 border=0 alt="Line">
</TD>
<td width="20"></td>
<td valign="top"><a href="http://www.launch.com/omg/?vo=o08o" target="new">
<img src="http://kornweb.com/images/omgB60.gif" width=60 height=60 border=0 alt="Online Music Group"></a></td>
</tr>
</table>

</BODY>
</HTML>