<HTML>
<HEAD>
<TITLE>青ポストあきた得々情報</TITLE>
<!--Generated by iDomo Ver.1.0-->
</HEAD>

<HTML>
<HEAD>
<TITLE>iﾎﾟｽﾄ</TITLE>
</HEAD>

<BODY>

<P>
<DIV ALIGN=CENTER>
<IMG SRC="img/ilg.gif" ALT="" WIDTH=92 HEIGHT=42><BR>
<!--006308<BR>-->
</DIV>
iﾎﾟｽﾄは得する情報を提供するｻｰﾋﾞｽです。<br>

<hr size=1>
<DIV ALIGN=CENTER>
<br>

<font color="red">無料ﾒｰﾘﾝｸﾞｻｰﾋﾞｽ利用者募集中!!</font><br>
<br>
<A HREF="NEC/About.asp">無料ﾒｰﾘﾝｸﾞｻｰﾋﾞｽとは?</A><br>
<br>
<A HREF="NEC/Tokuten.asp">登録するとこんな特典!!</A><br>
<br>
<hr size=1>
<A HREF="NEC/EntryForm2.asp">今すぐ登録!!</A><br>
</DIV>
<hr size=1>
<font color="red">iﾎﾟｽﾄのiはｲﾝﾌｫﾒｰｼｮﾝ,ｲﾝﾀｰﾈｯﾄ,iﾓｰﾄﾞなどの携帯端末を意味します。</font><br>
<hr size=1>
・ｲﾝﾀｰﾈｯﾄ版i-postも宜しくお願いします。<br>
・「<font color="blue"><b>青いﾎﾟｽﾄあきた</b></font>」毎週金曜日　無料配布<br>
</BODY>
</HTML>


</HTML>