--16:01:09--  http://www.royal.gr:80/
           => `www.royal.gr/index.html'
Connecting to www.royal.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 444 [text/html]

    0K ->                                                        [100%]

16:01:10 (433.59 KB/s) - `www.royal.gr/index.html' saved [444/444]

Loading robots.txt; please ignore errors.
--16:01:10--  http://www.royal.gr:80/no-robots.txt
           => `www.royal.gr/no-robots.txt'
Connecting to www.royal.gr:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
16:01:11 ERROR 404: Object Not Found.

--16:01:11--  http://www.royal.gr:80/logo.gif
           => `www.royal.gr/logo.gif'
Connecting to www.royal.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 18,037 [image/gif]

    0K -> .......... .......                                     [100%]

16:01:14 (6.74 KB/s) - `www.royal.gr/logo.gif' saved [18037/18037]

Converting www.royal.gr/index.html... done.

FINISHED --16:01:14--
Downloaded: 18,481 bytes in 2 files
Converting www.royal.gr/index.html... done.
