--06:58:15--  http://www.icbs.gr:80/
           => `www.icbs.gr/index.html'
Connecting to www.icbs.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]

    0K ->

06:58:16 (150.39 KB/s) - `www.icbs.gr/index.html' saved [154]

Loading robots.txt; please ignore errors.
--06:58:16--  http://www.icbs.gr:80/no-robots.txt
           => `www.icbs.gr/no-robots.txt'
Connecting to www.icbs.gr:80... connected!
HTTP request sent, awaiting response... 404 Object Not Found
06:58:17 ERROR 404: Object Not Found.

--06:58:17--  http://www.icbs.gr:80/scream.jpg
           => `www.icbs.gr/scream.jpg'
Connecting to www.icbs.gr:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 56,201 [image/jpeg]

    0K -> .......... .......... .......... .......... .......... [ 91%]
   50K -> ....                                                   [100%]

06:58:25 (7.10 KB/s) - `www.icbs.gr/scream.jpg' saved [56201/56201]

Converting www.icbs.gr/index.html... done.

FINISHED --06:58:25--
Downloaded: 56,355 bytes in 2 files
Converting www.icbs.gr/index.html... done.
