--16:40:36--  http://www.deiure.sk:80/
           => `www.deiure.sk/index.html'
Connecting to www.deiure.sk:80... connected!
HTTP request sent, awaiting response... 200 OK
Length: 3,934 [text/html]

    0K -> ...                                                    [100%]

16:40:37 (3.75 MB/s) - `www.deiure.sk/index.html' saved [3934/3934]

Converting www.deiure.sk/index.html... done.

FINISHED --16:40:38--
Downloaded: 3,934 bytes in 1 files
Converting www.deiure.sk/index.html... done.
